# Code generated by smithy-python-codegen DO NOT EDIT.

from types import MappingProxyType

from smithy_core.prelude import (
    BOOLEAN,
    BYTE,
    DOUBLE,
    FLOAT,
    INTEGER,
    LONG,
    SHORT,
    STRING,
)
from smithy_core.schemas import Schema
from smithy_core.shapes import ShapeID, ShapeType
from smithy_core.traits import Trait


NESTED_WITH_NAMESPACE = Schema.collection(
    id=ShapeID("aws.protocoltests.restxml.xmlns#NestedWithNamespace"),
    members={
        "attrField": {
            "target": STRING,
            "traits": [
                Trait.new(id=ShapeID("smithy.api#xmlName"), value="xsi:someName"),
                Trait.new(id=ShapeID("smithy.api#xmlAttribute")),
            ],
        }
    },
)

SIMPLE_SCALAR_PROPERTIES_INPUT = Schema.collection(
    id=ShapeID("aws.protocoltests.restxml.xmlns#SimpleScalarPropertiesInput"),
    traits=[
        Trait.new(
            id=ShapeID("smithy.synthetic#originalShapeId"),
            value="aws.protocoltests.restxml.xmlns#SimpleScalarPropertiesRequest",
        )
    ],
    members={
        "foo": {
            "target": STRING,
            "traits": [Trait.new(id=ShapeID("smithy.api#httpHeader"), value="X-Foo")],
        },
        "stringValue": {"target": STRING},
        "trueBooleanValue": {"target": BOOLEAN},
        "falseBooleanValue": {"target": BOOLEAN},
        "byteValue": {"target": BYTE},
        "shortValue": {"target": SHORT},
        "integerValue": {"target": INTEGER},
        "longValue": {"target": LONG},
        "floatValue": {"target": FLOAT},
        "Nested": {
            "target": NESTED_WITH_NAMESPACE,
            "traits": [
                Trait.new(
                    id=ShapeID("smithy.api#xmlNamespace"),
                    value=MappingProxyType(
                        {"prefix": "xsi", "uri": "https://example.com"}
                    ),
                )
            ],
        },
        "doubleValue": {
            "target": DOUBLE,
            "traits": [
                Trait.new(id=ShapeID("smithy.api#xmlName"), value="DoubleDribble")
            ],
        },
    },
)

SIMPLE_SCALAR_PROPERTIES_OUTPUT = Schema.collection(
    id=ShapeID("aws.protocoltests.restxml.xmlns#SimpleScalarPropertiesOutput"),
    traits=[
        Trait.new(
            id=ShapeID("smithy.synthetic#originalShapeId"),
            value="aws.protocoltests.restxml.xmlns#SimpleScalarPropertiesResponse",
        )
    ],
    members={
        "foo": {
            "target": STRING,
            "traits": [Trait.new(id=ShapeID("smithy.api#httpHeader"), value="X-Foo")],
        },
        "stringValue": {"target": STRING},
        "trueBooleanValue": {"target": BOOLEAN},
        "falseBooleanValue": {"target": BOOLEAN},
        "byteValue": {"target": BYTE},
        "shortValue": {"target": SHORT},
        "integerValue": {"target": INTEGER},
        "longValue": {"target": LONG},
        "floatValue": {"target": FLOAT},
        "Nested": {
            "target": NESTED_WITH_NAMESPACE,
            "traits": [
                Trait.new(
                    id=ShapeID("smithy.api#xmlNamespace"),
                    value=MappingProxyType(
                        {"prefix": "xsi", "uri": "https://example.com"}
                    ),
                )
            ],
        },
        "doubleValue": {
            "target": DOUBLE,
            "traits": [
                Trait.new(id=ShapeID("smithy.api#xmlName"), value="DoubleDribble")
            ],
        },
    },
)

SIMPLE_SCALAR_PROPERTIES = Schema(
    id=ShapeID("aws.protocoltests.restxml.xmlns#SimpleScalarProperties"),
    shape_type=ShapeType.OPERATION,
    traits=[
        Trait.new(
            id=ShapeID("smithy.api#http"),
            value=MappingProxyType({"uri": "/SimpleScalarProperties", "method": "PUT"}),
        )
    ],
)

REST_XML_WITH_NAMESPACE = Schema(
    id=ShapeID("aws.protocoltests.restxml.xmlns#RestXmlWithNamespace"),
    shape_type=ShapeType.SERVICE,
    traits=[
        Trait.new(
            id=ShapeID("smithy.api#xmlNamespace"),
            value=MappingProxyType({"uri": "https://example.com"}),
        )
    ],
)
