[GLOBAL]
pants_version = "2.18.0"

backend_packages = [
    "pants.backend.python",
    "pants.backend.python.lint.black",
    "pants.backend.python.lint.isort",
    "pants.backend.python.lint.flake8",
    "pants.backend.python.typecheck.mypy",
    "pants.backend.python.lint.pyupgrade",
    "pants.backend.python.lint.docformatter",
    "pants.backend.python.lint.bandit",
]

[source]
root_patterns = [
    "python-packages/*"
]

[python]
interpreter_constraints = [">=3.11"]
enable_resolves = true
resolves = { python-default = "python-default.lock" }
default_resolve = "python-default"

[pytest]
install_from_resolve = "python-default"
requirements = [
    "pytest-asyncio",
    "pytest-cov",
]
args = ['-v']

[test]
output = "all"
use_coverage = true

[black]
install_from_resolve = "python-default"
args = ["-t py311"]
interpreter_constraints = [">=3.11"]

[coverage-py]
interpreter_constraints = [">=3.11"]
report = [
    "xml",
    "html"
]

[mypy]
install_from_resolve = "python-default"
interpreter_constraints = [">=3.11"]

[flake8]
install_from_resolve = "python-default"
args = "--extend-ignore=W503"

[pyupgrade]
args = ["--py311-plus"]
interpreter_constraints = [">=3.11"]

[docformatter]
args = ["--wrap-summaries 88", "--wrap-descriptions 88"]
interpreter_constraints = [">=3.11"]

[bandit]
args = ["-x tests"]

[anonymous-telemetry]
enabled = false
