# Code generated by smithy-python-codegen DO NOT EDIT.

from copy import deepcopy
import logging
from typing import Any

from smithy_core.aio.client import AsyncClient, ClientCall, RequestPipeline
from smithy_core.deserializers import DeserializeableShape
from smithy_core.exceptions import ExpectationNotMetError
from smithy_core.schemas import APIOperation
from smithy_core.serializers import SerializeableShape
from smithy_http.plugins import user_agent_plugin

from .config import Config, Plugin
from .models import (
    EMPTY_INPUT_OUTPUT,
    EmptyInputOutputInput,
    EmptyInputOutputOutput,
    FLOAT16,
    FRACTIONAL_SECONDS,
    Float16Input,
    Float16Output,
    FractionalSecondsInput,
    FractionalSecondsOutput,
    GREETING_WITH_ERRORS,
    GreetingWithErrorsInput,
    GreetingWithErrorsOutput,
    NO_INPUT_OUTPUT,
    NoInputOutputInput,
    NoInputOutputOutput,
    OPERATION_WITH_DEFAULTS,
    OPTIONAL_INPUT_OUTPUT,
    OperationWithDefaultsInput,
    OperationWithDefaultsOutput,
    OptionalInputOutputInput,
    OptionalInputOutputOutput,
    RECURSIVE_SHAPES,
    RPC_V2_CBOR_DENSE_MAPS,
    RPC_V2_CBOR_LISTS,
    RPC_V2_CBOR_SPARSE_MAPS,
    RPC_V2_CBOR_UNIONS,
    RecursiveShapesInput,
    RecursiveShapesOutput,
    RpcV2CborDenseMapsInput,
    RpcV2CborDenseMapsOutput,
    RpcV2CborListsInput,
    RpcV2CborListsOutput,
    RpcV2CborSparseMapsInput,
    RpcV2CborSparseMapsOutput,
    RpcV2CborUnionsInput,
    RpcV2CborUnionsOutput,
    SIMPLE_SCALAR_PROPERTIES,
    SPARSE_NULLS_OPERATION,
    SimpleScalarPropertiesInput,
    SimpleScalarPropertiesOutput,
    SparseNullsOperationInput,
    SparseNullsOperationOutput,
)
from .user_agent import aws_user_agent_plugin


logger = logging.getLogger(__name__)


class RpcV2Protocol(AsyncClient):
    """Client for RpcV2Protocol"""

    def __init__(
        self, config: Config | None = None, plugins: list[Plugin] | None = None
    ):
        """
        Constructor for `RpcV2Protocol`.

        Args:
            config:
                Optional configuration for the client. Here you can set things like
                the endpoint for HTTP services or auth credentials.
            plugins:
                A list of callables applied once to the client's base configuration.
                Their changes are inherited by every operation invocation.
        """
        super().__init__()
        self._config = config
        self._plugins = plugins
        self._client_plugins: list[Plugin] = [aws_user_agent_plugin, user_agent_plugin]

    async def _ensure_setup(self) -> Config:
        if not self._setup_done:
            async with self._derive_lock:
                if self._closed:
                    raise RuntimeError(
                        "Cannot invoke an operation on a client that has been closed."
                    )
                if not self._setup_done:
                    if self._config is None:
                        config = Config()
                    else:
                        # Copy so plugins don't mutate the caller's config.
                        config = deepcopy(self._config)
                    for plugin in self._client_plugins:
                        plugin(config)
                    if self._plugins:
                        for plugin in self._plugins:
                            plugin(config)
                    # Publish state only after setup fully succeeds, so a
                    # failed _post_setup leaves the caller's config untouched
                    # (no re-applied plugins) and the transport closeable.
                    await self._post_setup(config)
                    self._transport = config.transport
                    self._config = config
                    self._setup_done = True
        assert self._config is not None
        return self._config

    async def _post_setup(self, config: Config) -> None:
        pass

    async def _prepare_call[I: SerializeableShape, O: DeserializeableShape](
        self,
        input: I,
        operation: APIOperation[I, O],
        default_plugins: list[Plugin],
        plugins: list[Plugin] | None,
    ) -> tuple[RequestPipeline[Any, Any], ClientCall[I, O]]:
        if self._closed:
            raise RuntimeError(
                "Cannot invoke an operation on a client that has been closed."
            )
        config = await self._ensure_setup()
        if default_plugins or plugins:
            # Keep operation-plugin mutations scoped to this call.
            config = deepcopy(config)
            for plugin in default_plugins:
                plugin(config)
            if plugins:
                for plugin in plugins:
                    plugin(config)
        if (
            config.protocol is None
            or config.transport is None
            or config.endpoint_resolver is None
            or config.auth_scheme_resolver is None
            or config.auth_schemes is None
        ):
            raise ExpectationNotMetError(
                "protocol, transport, endpoint_resolver, auth_scheme_resolver,"
                " and auth_schemes MUST be set on the config to make calls."
            )
        retry_strategy = await self._retry_strategy_resolver.resolve_retry_strategy(
            retry_strategy=config.retry_strategy
        )
        return self._build_call(
            input, operation, config=config, retry_strategy=retry_strategy
        )

    async def empty_input_output(
        self, input: EmptyInputOutputInput, plugins: list[Plugin] | None = None
    ) -> EmptyInputOutputOutput:
        """
        Invokes the EmptyInputOutput operation.

        Args:
            input:
                An instance of `EmptyInputOutputInput`.
            plugins:
                A list of callables that modify the configuration dynamically.
                Changes made by these plugins only apply for the duration of the
                operation execution and will not affect any other operation
                invocations.

        Returns:
            An instance of `EmptyInputOutputOutput`.
        """
        pipeline, call = await self._prepare_call(
            input, EMPTY_INPUT_OUTPUT, [], plugins
        )
        return await pipeline(call)

    async def float16(
        self, input: Float16Input, plugins: list[Plugin] | None = None
    ) -> Float16Output:
        """
        Invokes the Float16 operation.

        Args:
            input:
                An instance of `Float16Input`.
            plugins:
                A list of callables that modify the configuration dynamically.
                Changes made by these plugins only apply for the duration of the
                operation execution and will not affect any other operation
                invocations.

        Returns:
            An instance of `Float16Output`.
        """
        pipeline, call = await self._prepare_call(input, FLOAT16, [], plugins)
        return await pipeline(call)

    async def fractional_seconds(
        self, input: FractionalSecondsInput, plugins: list[Plugin] | None = None
    ) -> FractionalSecondsOutput:
        """
        Invokes the FractionalSeconds operation.

        Args:
            input:
                An instance of `FractionalSecondsInput`.
            plugins:
                A list of callables that modify the configuration dynamically.
                Changes made by these plugins only apply for the duration of the
                operation execution and will not affect any other operation
                invocations.

        Returns:
            An instance of `FractionalSecondsOutput`.
        """
        pipeline, call = await self._prepare_call(
            input, FRACTIONAL_SECONDS, [], plugins
        )
        return await pipeline(call)

    async def greeting_with_errors(
        self, input: GreetingWithErrorsInput, plugins: list[Plugin] | None = None
    ) -> GreetingWithErrorsOutput:
        """
        This operation has three possible return values:

        1.  A successful response in the form of GreetingWithErrorsOutput
        2.  An InvalidGreeting error.
        3.  A ComplexError error.

        Implementations must be able to successfully take a response and
        properly deserialize successful and error responses.

        Args:
            input:
                An instance of `GreetingWithErrorsInput`.
            plugins:
                A list of callables that modify the configuration dynamically.
                Changes made by these plugins only apply for the duration of the
                operation execution and will not affect any other operation
                invocations.

        Returns:
            An instance of `GreetingWithErrorsOutput`.
        """
        pipeline, call = await self._prepare_call(
            input, GREETING_WITH_ERRORS, [], plugins
        )
        return await pipeline(call)

    async def no_input_output(
        self, input: NoInputOutputInput, plugins: list[Plugin] | None = None
    ) -> NoInputOutputOutput:
        """
        Invokes the NoInputOutput operation.

        Args:
            input:
                An instance of `NoInputOutputInput`.
            plugins:
                A list of callables that modify the configuration dynamically.
                Changes made by these plugins only apply for the duration of the
                operation execution and will not affect any other operation
                invocations.

        Returns:
            An instance of `NoInputOutputOutput`.
        """
        pipeline, call = await self._prepare_call(input, NO_INPUT_OUTPUT, [], plugins)
        return await pipeline(call)

    async def operation_with_defaults(
        self, input: OperationWithDefaultsInput, plugins: list[Plugin] | None = None
    ) -> OperationWithDefaultsOutput:
        """
        Invokes the OperationWithDefaults operation.

        Args:
            input:
                An instance of `OperationWithDefaultsInput`.
            plugins:
                A list of callables that modify the configuration dynamically.
                Changes made by these plugins only apply for the duration of the
                operation execution and will not affect any other operation
                invocations.

        Returns:
            An instance of `OperationWithDefaultsOutput`.
        """
        pipeline, call = await self._prepare_call(
            input, OPERATION_WITH_DEFAULTS, [], plugins
        )
        return await pipeline(call)

    async def optional_input_output(
        self, input: OptionalInputOutputInput, plugins: list[Plugin] | None = None
    ) -> OptionalInputOutputOutput:
        """
        Invokes the OptionalInputOutput operation.

        Args:
            input:
                An instance of `OptionalInputOutputInput`.
            plugins:
                A list of callables that modify the configuration dynamically.
                Changes made by these plugins only apply for the duration of the
                operation execution and will not affect any other operation
                invocations.

        Returns:
            An instance of `OptionalInputOutputOutput`.
        """
        pipeline, call = await self._prepare_call(
            input, OPTIONAL_INPUT_OUTPUT, [], plugins
        )
        return await pipeline(call)

    async def recursive_shapes(
        self, input: RecursiveShapesInput, plugins: list[Plugin] | None = None
    ) -> RecursiveShapesOutput:
        """
        Invokes the RecursiveShapes operation.

        Args:
            input:
                An instance of `RecursiveShapesInput`.
            plugins:
                A list of callables that modify the configuration dynamically.
                Changes made by these plugins only apply for the duration of the
                operation execution and will not affect any other operation
                invocations.

        Returns:
            An instance of `RecursiveShapesOutput`.
        """
        pipeline, call = await self._prepare_call(input, RECURSIVE_SHAPES, [], plugins)
        return await pipeline(call)

    async def rpc_v2_cbor_dense_maps(
        self, input: RpcV2CborDenseMapsInput, plugins: list[Plugin] | None = None
    ) -> RpcV2CborDenseMapsOutput:
        """
        The example tests basic map serialization.

        Args:
            input:
                An instance of `RpcV2CborDenseMapsInput`.
            plugins:
                A list of callables that modify the configuration dynamically.
                Changes made by these plugins only apply for the duration of the
                operation execution and will not affect any other operation
                invocations.

        Returns:
            An instance of `RpcV2CborDenseMapsOutput`.
        """
        pipeline, call = await self._prepare_call(
            input, RPC_V2_CBOR_DENSE_MAPS, [], plugins
        )
        return await pipeline(call)

    async def rpc_v2_cbor_lists(
        self, input: RpcV2CborListsInput, plugins: list[Plugin] | None = None
    ) -> RpcV2CborListsOutput:
        """
        This test case serializes JSON lists for the following cases for both
        input and output:

        1.  Normal lists.
        2.  Normal sets.
        3.  Lists of lists.
        4.  Lists of structures.

        Args:
            input:
                An instance of `RpcV2CborListsInput`.
            plugins:
                A list of callables that modify the configuration dynamically.
                Changes made by these plugins only apply for the duration of the
                operation execution and will not affect any other operation
                invocations.

        Returns:
            An instance of `RpcV2CborListsOutput`.
        """
        pipeline, call = await self._prepare_call(input, RPC_V2_CBOR_LISTS, [], plugins)
        return await pipeline(call)

    async def rpc_v2_cbor_sparse_maps(
        self, input: RpcV2CborSparseMapsInput, plugins: list[Plugin] | None = None
    ) -> RpcV2CborSparseMapsOutput:
        """
        Invokes the RpcV2CborSparseMaps operation.

        Args:
            input:
                An instance of `RpcV2CborSparseMapsInput`.
            plugins:
                A list of callables that modify the configuration dynamically.
                Changes made by these plugins only apply for the duration of the
                operation execution and will not affect any other operation
                invocations.

        Returns:
            An instance of `RpcV2CborSparseMapsOutput`.
        """
        pipeline, call = await self._prepare_call(
            input, RPC_V2_CBOR_SPARSE_MAPS, [], plugins
        )
        return await pipeline(call)

    async def rpc_v2_cbor_unions(
        self, input: RpcV2CborUnionsInput, plugins: list[Plugin] | None = None
    ) -> RpcV2CborUnionsOutput:
        """
        This operation uses unions for inputs and outputs.

        Args:
            input:
                An instance of `RpcV2CborUnionsInput`.
            plugins:
                A list of callables that modify the configuration dynamically.
                Changes made by these plugins only apply for the duration of the
                operation execution and will not affect any other operation
                invocations.

        Returns:
            An instance of `RpcV2CborUnionsOutput`.
        """
        pipeline, call = await self._prepare_call(
            input, RPC_V2_CBOR_UNIONS, [], plugins
        )
        return await pipeline(call)

    async def simple_scalar_properties(
        self, input: SimpleScalarPropertiesInput, plugins: list[Plugin] | None = None
    ) -> SimpleScalarPropertiesOutput:
        """
        Invokes the SimpleScalarProperties operation.

        Args:
            input:
                An instance of `SimpleScalarPropertiesInput`.
            plugins:
                A list of callables that modify the configuration dynamically.
                Changes made by these plugins only apply for the duration of the
                operation execution and will not affect any other operation
                invocations.

        Returns:
            An instance of `SimpleScalarPropertiesOutput`.
        """
        pipeline, call = await self._prepare_call(
            input, SIMPLE_SCALAR_PROPERTIES, [], plugins
        )
        return await pipeline(call)

    async def sparse_nulls_operation(
        self, input: SparseNullsOperationInput, plugins: list[Plugin] | None = None
    ) -> SparseNullsOperationOutput:
        """
        Invokes the SparseNullsOperation operation.

        Args:
            input:
                An instance of `SparseNullsOperationInput`.
            plugins:
                A list of callables that modify the configuration dynamically.
                Changes made by these plugins only apply for the duration of the
                operation execution and will not affect any other operation
                invocations.

        Returns:
            An instance of `SparseNullsOperationOutput`.
        """
        pipeline, call = await self._prepare_call(
            input, SPARSE_NULLS_OPERATION, [], plugins
        )
        return await pipeline(call)
