# Code generated by smithy-python-codegen DO NOT EDIT.

import asyncio
from copy import deepcopy as _deepcopy
from datetime import datetime
import logging
from typing import Any, Self

from smithy_core.aio.client import ClientCall, RequestPipeline
from smithy_core.aio.retries import RetryStrategyResolver
from smithy_core.aio.utils import close
from smithy_core.exceptions import ExpectationNotMetError
from smithy_core.interceptors import InterceptorChain
from smithy_core.types import TypedProperties
from smithy_http.plugins import user_agent_plugin as _user_agent_plugin

from .config import Config, Plugin
from .models import (
    ClientOptionalDefaults,
    Defaults,
    EMPTY_INPUT_OUTPUT,
    EmptyInputOutputInput,
    EmptyInputOutputOutput,
    FLOAT16,
    FRACTIONAL_SECONDS,
    Float16Input,
    Float16Output,
    FractionalSecondsInput,
    FractionalSecondsOutput,
    GREETING_WITH_ERRORS,
    GreetingStruct,
    GreetingWithErrorsInput,
    GreetingWithErrorsOutput,
    NO_INPUT_OUTPUT,
    NoInputOutputInput,
    NoInputOutputOutput,
    OPERATION_WITH_DEFAULTS,
    OPTIONAL_INPUT_OUTPUT,
    OperationWithDefaultsInput,
    OperationWithDefaultsOutput,
    OptionalInputOutputInput,
    OptionalInputOutputOutput,
    RECURSIVE_SHAPES,
    RPC_V2_CBOR_DENSE_MAPS,
    RPC_V2_CBOR_LISTS,
    RPC_V2_CBOR_SPARSE_MAPS,
    RPC_V2_CBOR_UNIONS,
    RecursiveShapesInput,
    RecursiveShapesInputOutputNested1,
    RecursiveShapesOutput,
    RpcV2CborDenseMapsInput,
    RpcV2CborDenseMapsOutput,
    RpcV2CborListsInput,
    RpcV2CborListsOutput,
    RpcV2CborSparseMapsInput,
    RpcV2CborSparseMapsOutput,
    RpcV2CborUnion,
    RpcV2CborUnionsInput,
    RpcV2CborUnionsOutput,
    SIMPLE_SCALAR_PROPERTIES,
    SPARSE_NULLS_OPERATION,
    SimpleScalarPropertiesInput,
    SimpleScalarPropertiesOutput,
    SparseNullsOperationInput,
    SparseNullsOperationOutput,
    StructureListMember,
)
from .user_agent import aws_user_agent_plugin as _aws_user_agent_plugin


logger = logging.getLogger(__name__)


class RpcV2Protocol:
    """Client for RpcV2Protocol"""

    def __init__(
        self, config: Config | None = None, plugins: list[Plugin] | None = None
    ):
        """
        Constructor for `RpcV2Protocol`.

        Args:
            config:
                Optional configuration for the client. Here you can set things like
                the endpoint for HTTP services or auth credentials.
            plugins:
                A list of callables applied once to the client's base configuration.
                Their changes are inherited by every operation invocation.
        """
        self._config = config
        self._plugins = plugins
        self._derive_lock = asyncio.Lock()
        self._setup_done = False
        self._closed = False
        self._retry_strategy_resolver = RetryStrategyResolver()
        self._client_plugins: list[Plugin] = [
            _aws_user_agent_plugin,
            _user_agent_plugin,
        ]

    async def _ensure_setup(self) -> None:
        if not self._setup_done:
            async with self._derive_lock:
                if not self._setup_done:
                    if self._config is None:
                        config = Config()
                    else:
                        # Copy so plugins don't mutate the caller's config.
                        config = _deepcopy(self._config)
                    for plugin in self._client_plugins:
                        plugin(config)
                    if self._plugins:
                        for plugin in self._plugins:
                            plugin(config)
                    self._config = config

                    self._setup_done = True

    async def close(self) -> None:
        """Close this client and any resources held by its transport."""
        if self._closed:
            return
        async with self._derive_lock:
            if self._closed:
                return
            self._closed = True
            if self._setup_done and self._config is not None:
                await close(self._config.transport)

    async def __aenter__(self) -> Self:
        if self._closed:
            raise RuntimeError("Cannot enter a client that has been closed.")
        return self

    async def __aexit__(self, exc_type: Any, exc_value: Any, traceback: Any) -> None:
        await self.close()

    async def empty_input_output(
        self, *, plugins: list[Plugin] | None = None
    ) -> EmptyInputOutputOutput:
        """
        Invokes the EmptyInputOutput operation.

        Args:
            plugins:
                A list of callables that modify the configuration dynamically.
                Changes made by these plugins only apply for the duration of the
                operation execution and will not affect any other operation
                invocations.

        Returns:
            An instance of `EmptyInputOutputOutput`.
        """
        if self._closed:
            raise RuntimeError(
                "Cannot invoke an operation on a client that has been closed."
            )

        _input = EmptyInputOutputInput()
        _operation_plugins: list[Plugin] = []
        if plugins:
            _operation_plugins.extend(plugins)
        await self._ensure_setup()
        assert self._config is not None
        if _operation_plugins:
            # Keep operation-plugin mutations scoped to this call.
            _config = _deepcopy(self._config)
            for _plugin in _operation_plugins:
                _plugin(_config)
        else:
            _config = self._config
        if (
            _config.protocol is None
            or _config.transport is None
            or _config.endpoint_resolver is None
            or _config.auth_scheme_resolver is None
            or _config.auth_schemes is None
        ):
            raise ExpectationNotMetError(
                "protocol, transport, endpoint_resolver, auth_scheme_resolver,"
                " and auth_schemes MUST be set on the config to make calls."
            )

        _retry_strategy = await self._retry_strategy_resolver.resolve_retry_strategy(
            retry_strategy=_config.retry_strategy
        )

        _pipeline = RequestPipeline(
            protocol=_config.protocol, transport=_config.transport
        )
        _call = ClientCall(
            input=_input,
            operation=EMPTY_INPUT_OUTPUT,
            context=TypedProperties({"config": _config}),
            interceptor=InterceptorChain(_config.interceptors),
            auth_scheme_resolver=_config.auth_scheme_resolver,
            supported_auth_schemes=_config.auth_schemes,
            endpoint_resolver=_config.endpoint_resolver,
            retry_strategy=_retry_strategy,
        )

        return await _pipeline(_call)

    async def float16(self, *, plugins: list[Plugin] | None = None) -> Float16Output:
        """
        Invokes the Float16 operation.

        Args:
            plugins:
                A list of callables that modify the configuration dynamically.
                Changes made by these plugins only apply for the duration of the
                operation execution and will not affect any other operation
                invocations.

        Returns:
            An instance of `Float16Output`.
        """
        if self._closed:
            raise RuntimeError(
                "Cannot invoke an operation on a client that has been closed."
            )

        _input = Float16Input()
        _operation_plugins: list[Plugin] = []
        if plugins:
            _operation_plugins.extend(plugins)
        await self._ensure_setup()
        assert self._config is not None
        if _operation_plugins:
            # Keep operation-plugin mutations scoped to this call.
            _config = _deepcopy(self._config)
            for _plugin in _operation_plugins:
                _plugin(_config)
        else:
            _config = self._config
        if (
            _config.protocol is None
            or _config.transport is None
            or _config.endpoint_resolver is None
            or _config.auth_scheme_resolver is None
            or _config.auth_schemes is None
        ):
            raise ExpectationNotMetError(
                "protocol, transport, endpoint_resolver, auth_scheme_resolver,"
                " and auth_schemes MUST be set on the config to make calls."
            )

        _retry_strategy = await self._retry_strategy_resolver.resolve_retry_strategy(
            retry_strategy=_config.retry_strategy
        )

        _pipeline = RequestPipeline(
            protocol=_config.protocol, transport=_config.transport
        )
        _call = ClientCall(
            input=_input,
            operation=FLOAT16,
            context=TypedProperties({"config": _config}),
            interceptor=InterceptorChain(_config.interceptors),
            auth_scheme_resolver=_config.auth_scheme_resolver,
            supported_auth_schemes=_config.auth_schemes,
            endpoint_resolver=_config.endpoint_resolver,
            retry_strategy=_retry_strategy,
        )

        return await _pipeline(_call)

    async def fractional_seconds(
        self, *, plugins: list[Plugin] | None = None
    ) -> FractionalSecondsOutput:
        """
        Invokes the FractionalSeconds operation.

        Args:
            plugins:
                A list of callables that modify the configuration dynamically.
                Changes made by these plugins only apply for the duration of the
                operation execution and will not affect any other operation
                invocations.

        Returns:
            An instance of `FractionalSecondsOutput`.
        """
        if self._closed:
            raise RuntimeError(
                "Cannot invoke an operation on a client that has been closed."
            )

        _input = FractionalSecondsInput()
        _operation_plugins: list[Plugin] = []
        if plugins:
            _operation_plugins.extend(plugins)
        await self._ensure_setup()
        assert self._config is not None
        if _operation_plugins:
            # Keep operation-plugin mutations scoped to this call.
            _config = _deepcopy(self._config)
            for _plugin in _operation_plugins:
                _plugin(_config)
        else:
            _config = self._config
        if (
            _config.protocol is None
            or _config.transport is None
            or _config.endpoint_resolver is None
            or _config.auth_scheme_resolver is None
            or _config.auth_schemes is None
        ):
            raise ExpectationNotMetError(
                "protocol, transport, endpoint_resolver, auth_scheme_resolver,"
                " and auth_schemes MUST be set on the config to make calls."
            )

        _retry_strategy = await self._retry_strategy_resolver.resolve_retry_strategy(
            retry_strategy=_config.retry_strategy
        )

        _pipeline = RequestPipeline(
            protocol=_config.protocol, transport=_config.transport
        )
        _call = ClientCall(
            input=_input,
            operation=FRACTIONAL_SECONDS,
            context=TypedProperties({"config": _config}),
            interceptor=InterceptorChain(_config.interceptors),
            auth_scheme_resolver=_config.auth_scheme_resolver,
            supported_auth_schemes=_config.auth_schemes,
            endpoint_resolver=_config.endpoint_resolver,
            retry_strategy=_retry_strategy,
        )

        return await _pipeline(_call)

    async def greeting_with_errors(
        self, *, plugins: list[Plugin] | None = None
    ) -> GreetingWithErrorsOutput:
        """
        This operation has three possible return values:

        1.  A successful response in the form of GreetingWithErrorsOutput
        2.  An InvalidGreeting error.
        3.  A ComplexError error.

        Implementations must be able to successfully take a response and
        properly deserialize successful and error responses.

        Args:
            plugins:
                A list of callables that modify the configuration dynamically.
                Changes made by these plugins only apply for the duration of the
                operation execution and will not affect any other operation
                invocations.

        Returns:
            An instance of `GreetingWithErrorsOutput`.
        """
        if self._closed:
            raise RuntimeError(
                "Cannot invoke an operation on a client that has been closed."
            )

        _input = GreetingWithErrorsInput()
        _operation_plugins: list[Plugin] = []
        if plugins:
            _operation_plugins.extend(plugins)
        await self._ensure_setup()
        assert self._config is not None
        if _operation_plugins:
            # Keep operation-plugin mutations scoped to this call.
            _config = _deepcopy(self._config)
            for _plugin in _operation_plugins:
                _plugin(_config)
        else:
            _config = self._config
        if (
            _config.protocol is None
            or _config.transport is None
            or _config.endpoint_resolver is None
            or _config.auth_scheme_resolver is None
            or _config.auth_schemes is None
        ):
            raise ExpectationNotMetError(
                "protocol, transport, endpoint_resolver, auth_scheme_resolver,"
                " and auth_schemes MUST be set on the config to make calls."
            )

        _retry_strategy = await self._retry_strategy_resolver.resolve_retry_strategy(
            retry_strategy=_config.retry_strategy
        )

        _pipeline = RequestPipeline(
            protocol=_config.protocol, transport=_config.transport
        )
        _call = ClientCall(
            input=_input,
            operation=GREETING_WITH_ERRORS,
            context=TypedProperties({"config": _config}),
            interceptor=InterceptorChain(_config.interceptors),
            auth_scheme_resolver=_config.auth_scheme_resolver,
            supported_auth_schemes=_config.auth_schemes,
            endpoint_resolver=_config.endpoint_resolver,
            retry_strategy=_retry_strategy,
        )

        return await _pipeline(_call)

    async def no_input_output(
        self, *, plugins: list[Plugin] | None = None
    ) -> NoInputOutputOutput:
        """
        Invokes the NoInputOutput operation.

        Args:
            plugins:
                A list of callables that modify the configuration dynamically.
                Changes made by these plugins only apply for the duration of the
                operation execution and will not affect any other operation
                invocations.

        Returns:
            An instance of `NoInputOutputOutput`.
        """
        if self._closed:
            raise RuntimeError(
                "Cannot invoke an operation on a client that has been closed."
            )

        _input = NoInputOutputInput()
        _operation_plugins: list[Plugin] = []
        if plugins:
            _operation_plugins.extend(plugins)
        await self._ensure_setup()
        assert self._config is not None
        if _operation_plugins:
            # Keep operation-plugin mutations scoped to this call.
            _config = _deepcopy(self._config)
            for _plugin in _operation_plugins:
                _plugin(_config)
        else:
            _config = self._config
        if (
            _config.protocol is None
            or _config.transport is None
            or _config.endpoint_resolver is None
            or _config.auth_scheme_resolver is None
            or _config.auth_schemes is None
        ):
            raise ExpectationNotMetError(
                "protocol, transport, endpoint_resolver, auth_scheme_resolver,"
                " and auth_schemes MUST be set on the config to make calls."
            )

        _retry_strategy = await self._retry_strategy_resolver.resolve_retry_strategy(
            retry_strategy=_config.retry_strategy
        )

        _pipeline = RequestPipeline(
            protocol=_config.protocol, transport=_config.transport
        )
        _call = ClientCall(
            input=_input,
            operation=NO_INPUT_OUTPUT,
            context=TypedProperties({"config": _config}),
            interceptor=InterceptorChain(_config.interceptors),
            auth_scheme_resolver=_config.auth_scheme_resolver,
            supported_auth_schemes=_config.auth_schemes,
            endpoint_resolver=_config.endpoint_resolver,
            retry_strategy=_retry_strategy,
        )

        return await _pipeline(_call)

    async def operation_with_defaults(
        self,
        *,
        defaults: Defaults | None = None,
        client_optional_defaults: ClientOptionalDefaults | None = None,
        top_level_default: str = "hi",
        other_top_level_default: int = 0,
        plugins: list[Plugin] | None = None,
    ) -> OperationWithDefaultsOutput:
        """
        Invokes the OperationWithDefaults operation.

        Args:
            plugins:
                A list of callables that modify the configuration dynamically.
                Changes made by these plugins only apply for the duration of the
                operation execution and will not affect any other operation
                invocations.

        Returns:
            An instance of `OperationWithDefaultsOutput`.
        """
        if self._closed:
            raise RuntimeError(
                "Cannot invoke an operation on a client that has been closed."
            )

        _input = OperationWithDefaultsInput(
            defaults=defaults,
            client_optional_defaults=client_optional_defaults,
            top_level_default=top_level_default,
            other_top_level_default=other_top_level_default,
        )
        _operation_plugins: list[Plugin] = []
        if plugins:
            _operation_plugins.extend(plugins)
        await self._ensure_setup()
        assert self._config is not None
        if _operation_plugins:
            # Keep operation-plugin mutations scoped to this call.
            _config = _deepcopy(self._config)
            for _plugin in _operation_plugins:
                _plugin(_config)
        else:
            _config = self._config
        if (
            _config.protocol is None
            or _config.transport is None
            or _config.endpoint_resolver is None
            or _config.auth_scheme_resolver is None
            or _config.auth_schemes is None
        ):
            raise ExpectationNotMetError(
                "protocol, transport, endpoint_resolver, auth_scheme_resolver,"
                " and auth_schemes MUST be set on the config to make calls."
            )

        _retry_strategy = await self._retry_strategy_resolver.resolve_retry_strategy(
            retry_strategy=_config.retry_strategy
        )

        _pipeline = RequestPipeline(
            protocol=_config.protocol, transport=_config.transport
        )
        _call = ClientCall(
            input=_input,
            operation=OPERATION_WITH_DEFAULTS,
            context=TypedProperties({"config": _config}),
            interceptor=InterceptorChain(_config.interceptors),
            auth_scheme_resolver=_config.auth_scheme_resolver,
            supported_auth_schemes=_config.auth_schemes,
            endpoint_resolver=_config.endpoint_resolver,
            retry_strategy=_retry_strategy,
        )

        return await _pipeline(_call)

    async def optional_input_output(
        self, *, value: str | None = None, plugins: list[Plugin] | None = None
    ) -> OptionalInputOutputOutput:
        """
        Invokes the OptionalInputOutput operation.

        Args:
            plugins:
                A list of callables that modify the configuration dynamically.
                Changes made by these plugins only apply for the duration of the
                operation execution and will not affect any other operation
                invocations.

        Returns:
            An instance of `OptionalInputOutputOutput`.
        """
        if self._closed:
            raise RuntimeError(
                "Cannot invoke an operation on a client that has been closed."
            )

        _input = OptionalInputOutputInput(value=value)
        _operation_plugins: list[Plugin] = []
        if plugins:
            _operation_plugins.extend(plugins)
        await self._ensure_setup()
        assert self._config is not None
        if _operation_plugins:
            # Keep operation-plugin mutations scoped to this call.
            _config = _deepcopy(self._config)
            for _plugin in _operation_plugins:
                _plugin(_config)
        else:
            _config = self._config
        if (
            _config.protocol is None
            or _config.transport is None
            or _config.endpoint_resolver is None
            or _config.auth_scheme_resolver is None
            or _config.auth_schemes is None
        ):
            raise ExpectationNotMetError(
                "protocol, transport, endpoint_resolver, auth_scheme_resolver,"
                " and auth_schemes MUST be set on the config to make calls."
            )

        _retry_strategy = await self._retry_strategy_resolver.resolve_retry_strategy(
            retry_strategy=_config.retry_strategy
        )

        _pipeline = RequestPipeline(
            protocol=_config.protocol, transport=_config.transport
        )
        _call = ClientCall(
            input=_input,
            operation=OPTIONAL_INPUT_OUTPUT,
            context=TypedProperties({"config": _config}),
            interceptor=InterceptorChain(_config.interceptors),
            auth_scheme_resolver=_config.auth_scheme_resolver,
            supported_auth_schemes=_config.auth_schemes,
            endpoint_resolver=_config.endpoint_resolver,
            retry_strategy=_retry_strategy,
        )

        return await _pipeline(_call)

    async def recursive_shapes(
        self,
        *,
        nested: RecursiveShapesInputOutputNested1 | None = None,
        plugins: list[Plugin] | None = None,
    ) -> RecursiveShapesOutput:
        """
        Invokes the RecursiveShapes operation.

        Args:
            plugins:
                A list of callables that modify the configuration dynamically.
                Changes made by these plugins only apply for the duration of the
                operation execution and will not affect any other operation
                invocations.

        Returns:
            An instance of `RecursiveShapesOutput`.
        """
        if self._closed:
            raise RuntimeError(
                "Cannot invoke an operation on a client that has been closed."
            )

        _input = RecursiveShapesInput(nested=nested)
        _operation_plugins: list[Plugin] = []
        if plugins:
            _operation_plugins.extend(plugins)
        await self._ensure_setup()
        assert self._config is not None
        if _operation_plugins:
            # Keep operation-plugin mutations scoped to this call.
            _config = _deepcopy(self._config)
            for _plugin in _operation_plugins:
                _plugin(_config)
        else:
            _config = self._config
        if (
            _config.protocol is None
            or _config.transport is None
            or _config.endpoint_resolver is None
            or _config.auth_scheme_resolver is None
            or _config.auth_schemes is None
        ):
            raise ExpectationNotMetError(
                "protocol, transport, endpoint_resolver, auth_scheme_resolver,"
                " and auth_schemes MUST be set on the config to make calls."
            )

        _retry_strategy = await self._retry_strategy_resolver.resolve_retry_strategy(
            retry_strategy=_config.retry_strategy
        )

        _pipeline = RequestPipeline(
            protocol=_config.protocol, transport=_config.transport
        )
        _call = ClientCall(
            input=_input,
            operation=RECURSIVE_SHAPES,
            context=TypedProperties({"config": _config}),
            interceptor=InterceptorChain(_config.interceptors),
            auth_scheme_resolver=_config.auth_scheme_resolver,
            supported_auth_schemes=_config.auth_schemes,
            endpoint_resolver=_config.endpoint_resolver,
            retry_strategy=_retry_strategy,
        )

        return await _pipeline(_call)

    async def rpc_v2_cbor_dense_maps(
        self,
        *,
        dense_struct_map: dict[str, GreetingStruct] | None = None,
        dense_number_map: dict[str, int] | None = None,
        dense_boolean_map: dict[str, bool] | None = None,
        dense_string_map: dict[str, str] | None = None,
        dense_set_map: dict[str, list[str]] | None = None,
        plugins: list[Plugin] | None = None,
    ) -> RpcV2CborDenseMapsOutput:
        """
        The example tests basic map serialization.

        Args:
            plugins:
                A list of callables that modify the configuration dynamically.
                Changes made by these plugins only apply for the duration of the
                operation execution and will not affect any other operation
                invocations.

        Returns:
            An instance of `RpcV2CborDenseMapsOutput`.
        """
        if self._closed:
            raise RuntimeError(
                "Cannot invoke an operation on a client that has been closed."
            )

        _input = RpcV2CborDenseMapsInput(
            dense_struct_map=dense_struct_map,
            dense_number_map=dense_number_map,
            dense_boolean_map=dense_boolean_map,
            dense_string_map=dense_string_map,
            dense_set_map=dense_set_map,
        )
        _operation_plugins: list[Plugin] = []
        if plugins:
            _operation_plugins.extend(plugins)
        await self._ensure_setup()
        assert self._config is not None
        if _operation_plugins:
            # Keep operation-plugin mutations scoped to this call.
            _config = _deepcopy(self._config)
            for _plugin in _operation_plugins:
                _plugin(_config)
        else:
            _config = self._config
        if (
            _config.protocol is None
            or _config.transport is None
            or _config.endpoint_resolver is None
            or _config.auth_scheme_resolver is None
            or _config.auth_schemes is None
        ):
            raise ExpectationNotMetError(
                "protocol, transport, endpoint_resolver, auth_scheme_resolver,"
                " and auth_schemes MUST be set on the config to make calls."
            )

        _retry_strategy = await self._retry_strategy_resolver.resolve_retry_strategy(
            retry_strategy=_config.retry_strategy
        )

        _pipeline = RequestPipeline(
            protocol=_config.protocol, transport=_config.transport
        )
        _call = ClientCall(
            input=_input,
            operation=RPC_V2_CBOR_DENSE_MAPS,
            context=TypedProperties({"config": _config}),
            interceptor=InterceptorChain(_config.interceptors),
            auth_scheme_resolver=_config.auth_scheme_resolver,
            supported_auth_schemes=_config.auth_schemes,
            endpoint_resolver=_config.endpoint_resolver,
            retry_strategy=_retry_strategy,
        )

        return await _pipeline(_call)

    async def rpc_v2_cbor_lists(
        self,
        *,
        string_list: list[str] | None = None,
        string_set: list[str] | None = None,
        integer_list: list[int] | None = None,
        boolean_list: list[bool] | None = None,
        timestamp_list: list[datetime] | None = None,
        enum_list: list[str] | None = None,
        int_enum_list: list[int] | None = None,
        nested_string_list: list[list[str]] | None = None,
        structure_list: list[StructureListMember] | None = None,
        blob_list: list[bytes] | None = None,
        plugins: list[Plugin] | None = None,
    ) -> RpcV2CborListsOutput:
        """
        This test case serializes JSON lists for the following cases for both
        input and output:

        1.  Normal lists.
        2.  Normal sets.
        3.  Lists of lists.
        4.  Lists of structures.

        Args:
            nested_string_list:
                A list of lists of strings.
            plugins:
                A list of callables that modify the configuration dynamically.
                Changes made by these plugins only apply for the duration of the
                operation execution and will not affect any other operation
                invocations.

        Returns:
            An instance of `RpcV2CborListsOutput`.
        """
        if self._closed:
            raise RuntimeError(
                "Cannot invoke an operation on a client that has been closed."
            )

        _input = RpcV2CborListsInput(
            string_list=string_list,
            string_set=string_set,
            integer_list=integer_list,
            boolean_list=boolean_list,
            timestamp_list=timestamp_list,
            enum_list=enum_list,
            int_enum_list=int_enum_list,
            nested_string_list=nested_string_list,
            structure_list=structure_list,
            blob_list=blob_list,
        )
        _operation_plugins: list[Plugin] = []
        if plugins:
            _operation_plugins.extend(plugins)
        await self._ensure_setup()
        assert self._config is not None
        if _operation_plugins:
            # Keep operation-plugin mutations scoped to this call.
            _config = _deepcopy(self._config)
            for _plugin in _operation_plugins:
                _plugin(_config)
        else:
            _config = self._config
        if (
            _config.protocol is None
            or _config.transport is None
            or _config.endpoint_resolver is None
            or _config.auth_scheme_resolver is None
            or _config.auth_schemes is None
        ):
            raise ExpectationNotMetError(
                "protocol, transport, endpoint_resolver, auth_scheme_resolver,"
                " and auth_schemes MUST be set on the config to make calls."
            )

        _retry_strategy = await self._retry_strategy_resolver.resolve_retry_strategy(
            retry_strategy=_config.retry_strategy
        )

        _pipeline = RequestPipeline(
            protocol=_config.protocol, transport=_config.transport
        )
        _call = ClientCall(
            input=_input,
            operation=RPC_V2_CBOR_LISTS,
            context=TypedProperties({"config": _config}),
            interceptor=InterceptorChain(_config.interceptors),
            auth_scheme_resolver=_config.auth_scheme_resolver,
            supported_auth_schemes=_config.auth_schemes,
            endpoint_resolver=_config.endpoint_resolver,
            retry_strategy=_retry_strategy,
        )

        return await _pipeline(_call)

    async def rpc_v2_cbor_sparse_maps(
        self,
        *,
        sparse_struct_map: dict[str, GreetingStruct | None] | None = None,
        sparse_number_map: dict[str, int | None] | None = None,
        sparse_boolean_map: dict[str, bool | None] | None = None,
        sparse_string_map: dict[str, str | None] | None = None,
        sparse_set_map: dict[str, list[str] | None] | None = None,
        plugins: list[Plugin] | None = None,
    ) -> RpcV2CborSparseMapsOutput:
        """
        Invokes the RpcV2CborSparseMaps operation.

        Args:
            plugins:
                A list of callables that modify the configuration dynamically.
                Changes made by these plugins only apply for the duration of the
                operation execution and will not affect any other operation
                invocations.

        Returns:
            An instance of `RpcV2CborSparseMapsOutput`.
        """
        if self._closed:
            raise RuntimeError(
                "Cannot invoke an operation on a client that has been closed."
            )

        _input = RpcV2CborSparseMapsInput(
            sparse_struct_map=sparse_struct_map,
            sparse_number_map=sparse_number_map,
            sparse_boolean_map=sparse_boolean_map,
            sparse_string_map=sparse_string_map,
            sparse_set_map=sparse_set_map,
        )
        _operation_plugins: list[Plugin] = []
        if plugins:
            _operation_plugins.extend(plugins)
        await self._ensure_setup()
        assert self._config is not None
        if _operation_plugins:
            # Keep operation-plugin mutations scoped to this call.
            _config = _deepcopy(self._config)
            for _plugin in _operation_plugins:
                _plugin(_config)
        else:
            _config = self._config
        if (
            _config.protocol is None
            or _config.transport is None
            or _config.endpoint_resolver is None
            or _config.auth_scheme_resolver is None
            or _config.auth_schemes is None
        ):
            raise ExpectationNotMetError(
                "protocol, transport, endpoint_resolver, auth_scheme_resolver,"
                " and auth_schemes MUST be set on the config to make calls."
            )

        _retry_strategy = await self._retry_strategy_resolver.resolve_retry_strategy(
            retry_strategy=_config.retry_strategy
        )

        _pipeline = RequestPipeline(
            protocol=_config.protocol, transport=_config.transport
        )
        _call = ClientCall(
            input=_input,
            operation=RPC_V2_CBOR_SPARSE_MAPS,
            context=TypedProperties({"config": _config}),
            interceptor=InterceptorChain(_config.interceptors),
            auth_scheme_resolver=_config.auth_scheme_resolver,
            supported_auth_schemes=_config.auth_schemes,
            endpoint_resolver=_config.endpoint_resolver,
            retry_strategy=_retry_strategy,
        )

        return await _pipeline(_call)

    async def rpc_v2_cbor_unions(
        self,
        *,
        contents: RpcV2CborUnion | None = None,
        other_value: str | None = None,
        plugins: list[Plugin] | None = None,
    ) -> RpcV2CborUnionsOutput:
        """
        This operation uses unions for inputs and outputs.

        Args:
            plugins:
                A list of callables that modify the configuration dynamically.
                Changes made by these plugins only apply for the duration of the
                operation execution and will not affect any other operation
                invocations.

        Returns:
            An instance of `RpcV2CborUnionsOutput`.
        """
        if self._closed:
            raise RuntimeError(
                "Cannot invoke an operation on a client that has been closed."
            )

        _input = RpcV2CborUnionsInput(contents=contents, other_value=other_value)
        _operation_plugins: list[Plugin] = []
        if plugins:
            _operation_plugins.extend(plugins)
        await self._ensure_setup()
        assert self._config is not None
        if _operation_plugins:
            # Keep operation-plugin mutations scoped to this call.
            _config = _deepcopy(self._config)
            for _plugin in _operation_plugins:
                _plugin(_config)
        else:
            _config = self._config
        if (
            _config.protocol is None
            or _config.transport is None
            or _config.endpoint_resolver is None
            or _config.auth_scheme_resolver is None
            or _config.auth_schemes is None
        ):
            raise ExpectationNotMetError(
                "protocol, transport, endpoint_resolver, auth_scheme_resolver,"
                " and auth_schemes MUST be set on the config to make calls."
            )

        _retry_strategy = await self._retry_strategy_resolver.resolve_retry_strategy(
            retry_strategy=_config.retry_strategy
        )

        _pipeline = RequestPipeline(
            protocol=_config.protocol, transport=_config.transport
        )
        _call = ClientCall(
            input=_input,
            operation=RPC_V2_CBOR_UNIONS,
            context=TypedProperties({"config": _config}),
            interceptor=InterceptorChain(_config.interceptors),
            auth_scheme_resolver=_config.auth_scheme_resolver,
            supported_auth_schemes=_config.auth_schemes,
            endpoint_resolver=_config.endpoint_resolver,
            retry_strategy=_retry_strategy,
        )

        return await _pipeline(_call)

    async def simple_scalar_properties(
        self,
        *,
        true_boolean_value: bool | None = None,
        false_boolean_value: bool | None = None,
        byte_value: int | None = None,
        double_value: float | None = None,
        float_value: float | None = None,
        integer_value: int | None = None,
        long_value: int | None = None,
        short_value: int | None = None,
        string_value: str | None = None,
        blob_value: bytes | None = None,
        plugins: list[Plugin] | None = None,
    ) -> SimpleScalarPropertiesOutput:
        """
        Invokes the SimpleScalarProperties operation.

        Args:
            plugins:
                A list of callables that modify the configuration dynamically.
                Changes made by these plugins only apply for the duration of the
                operation execution and will not affect any other operation
                invocations.

        Returns:
            An instance of `SimpleScalarPropertiesOutput`.
        """
        if self._closed:
            raise RuntimeError(
                "Cannot invoke an operation on a client that has been closed."
            )

        _input = SimpleScalarPropertiesInput(
            true_boolean_value=true_boolean_value,
            false_boolean_value=false_boolean_value,
            byte_value=byte_value,
            double_value=double_value,
            float_value=float_value,
            integer_value=integer_value,
            long_value=long_value,
            short_value=short_value,
            string_value=string_value,
            blob_value=blob_value,
        )
        _operation_plugins: list[Plugin] = []
        if plugins:
            _operation_plugins.extend(plugins)
        await self._ensure_setup()
        assert self._config is not None
        if _operation_plugins:
            # Keep operation-plugin mutations scoped to this call.
            _config = _deepcopy(self._config)
            for _plugin in _operation_plugins:
                _plugin(_config)
        else:
            _config = self._config
        if (
            _config.protocol is None
            or _config.transport is None
            or _config.endpoint_resolver is None
            or _config.auth_scheme_resolver is None
            or _config.auth_schemes is None
        ):
            raise ExpectationNotMetError(
                "protocol, transport, endpoint_resolver, auth_scheme_resolver,"
                " and auth_schemes MUST be set on the config to make calls."
            )

        _retry_strategy = await self._retry_strategy_resolver.resolve_retry_strategy(
            retry_strategy=_config.retry_strategy
        )

        _pipeline = RequestPipeline(
            protocol=_config.protocol, transport=_config.transport
        )
        _call = ClientCall(
            input=_input,
            operation=SIMPLE_SCALAR_PROPERTIES,
            context=TypedProperties({"config": _config}),
            interceptor=InterceptorChain(_config.interceptors),
            auth_scheme_resolver=_config.auth_scheme_resolver,
            supported_auth_schemes=_config.auth_schemes,
            endpoint_resolver=_config.endpoint_resolver,
            retry_strategy=_retry_strategy,
        )

        return await _pipeline(_call)

    async def sparse_nulls_operation(
        self,
        *,
        sparse_string_list: list[str | None] | None = None,
        sparse_string_map: dict[str, str | None] | None = None,
        plugins: list[Plugin] | None = None,
    ) -> SparseNullsOperationOutput:
        """
        Invokes the SparseNullsOperation operation.

        Args:
            plugins:
                A list of callables that modify the configuration dynamically.
                Changes made by these plugins only apply for the duration of the
                operation execution and will not affect any other operation
                invocations.

        Returns:
            An instance of `SparseNullsOperationOutput`.
        """
        if self._closed:
            raise RuntimeError(
                "Cannot invoke an operation on a client that has been closed."
            )

        _input = SparseNullsOperationInput(
            sparse_string_list=sparse_string_list, sparse_string_map=sparse_string_map
        )
        _operation_plugins: list[Plugin] = []
        if plugins:
            _operation_plugins.extend(plugins)
        await self._ensure_setup()
        assert self._config is not None
        if _operation_plugins:
            # Keep operation-plugin mutations scoped to this call.
            _config = _deepcopy(self._config)
            for _plugin in _operation_plugins:
                _plugin(_config)
        else:
            _config = self._config
        if (
            _config.protocol is None
            or _config.transport is None
            or _config.endpoint_resolver is None
            or _config.auth_scheme_resolver is None
            or _config.auth_schemes is None
        ):
            raise ExpectationNotMetError(
                "protocol, transport, endpoint_resolver, auth_scheme_resolver,"
                " and auth_schemes MUST be set on the config to make calls."
            )

        _retry_strategy = await self._retry_strategy_resolver.resolve_retry_strategy(
            retry_strategy=_config.retry_strategy
        )

        _pipeline = RequestPipeline(
            protocol=_config.protocol, transport=_config.transport
        )
        _call = ClientCall(
            input=_input,
            operation=SPARSE_NULLS_OPERATION,
            context=TypedProperties({"config": _config}),
            interceptor=InterceptorChain(_config.interceptors),
            auth_scheme_resolver=_config.auth_scheme_resolver,
            supported_auth_schemes=_config.auth_schemes,
            endpoint_resolver=_config.endpoint_resolver,
            retry_strategy=_retry_strategy,
        )

        return await _pipeline(_call)
