# Code generated by smithy-python-codegen DO NOT EDIT.

from dataclasses import dataclass
from typing import Any, Callable, TypeAlias, Union

from smithy_aws_core.endpoints.standard_regional import (
    StandardRegionalEndpointsResolver,
)
from smithy_core.aio.interfaces import ClientProtocol, ClientTransport, EndpointResolver
from smithy_core.aio.interfaces.auth import AuthScheme
from smithy_core.aio.interfaces.retries import RetryStrategy
from smithy_core.auth import DefaultAuthResolver
from smithy_core.interceptors import Interceptor
from smithy_core.interfaces import URI
from smithy_core.retries import RetryStrategyOptions
from smithy_core.shapes import ShapeID
from smithy_http.aio.aiohttp import AIOHTTPClient
from smithy_http.aio.protocols import RpcV2CborClientProtocol
from smithy_http.interfaces import HTTPRequestConfiguration

from ._private.schemas import RPC_V2_PROTOCOL as _SCHEMA_RPC_V2_PROTOCOL
from .models import (
    EmptyInputOutputInput,
    EmptyInputOutputOutput,
    Float16Input,
    Float16Output,
    FractionalSecondsInput,
    FractionalSecondsOutput,
    GreetingWithErrorsInput,
    GreetingWithErrorsOutput,
    NoInputOutputInput,
    NoInputOutputOutput,
    OperationWithDefaultsInput,
    OperationWithDefaultsOutput,
    OptionalInputOutputInput,
    OptionalInputOutputOutput,
    RecursiveShapesInput,
    RecursiveShapesOutput,
    RpcV2CborDenseMapsInput,
    RpcV2CborDenseMapsOutput,
    RpcV2CborListsInput,
    RpcV2CborListsOutput,
    RpcV2CborSparseMapsInput,
    RpcV2CborSparseMapsOutput,
    RpcV2CborUnionsInput,
    RpcV2CborUnionsOutput,
    SimpleScalarPropertiesInput,
    SimpleScalarPropertiesOutput,
    SparseNullsOperationInput,
    SparseNullsOperationOutput,
)


_ServiceInterceptor = Union[
    Interceptor[EmptyInputOutputInput, EmptyInputOutputOutput, Any, Any],
    Interceptor[Float16Input, Float16Output, Any, Any],
    Interceptor[FractionalSecondsInput, FractionalSecondsOutput, Any, Any],
    Interceptor[GreetingWithErrorsInput, GreetingWithErrorsOutput, Any, Any],
    Interceptor[NoInputOutputInput, NoInputOutputOutput, Any, Any],
    Interceptor[OperationWithDefaultsInput, OperationWithDefaultsOutput, Any, Any],
    Interceptor[OptionalInputOutputInput, OptionalInputOutputOutput, Any, Any],
    Interceptor[RecursiveShapesInput, RecursiveShapesOutput, Any, Any],
    Interceptor[RpcV2CborDenseMapsInput, RpcV2CborDenseMapsOutput, Any, Any],
    Interceptor[RpcV2CborListsInput, RpcV2CborListsOutput, Any, Any],
    Interceptor[RpcV2CborSparseMapsInput, RpcV2CborSparseMapsOutput, Any, Any],
    Interceptor[RpcV2CborUnionsInput, RpcV2CborUnionsOutput, Any, Any],
    Interceptor[SimpleScalarPropertiesInput, SimpleScalarPropertiesOutput, Any, Any],
    Interceptor[SparseNullsOperationInput, SparseNullsOperationOutput, Any, Any],
]


@dataclass(init=False)
class Config:
    """Configuration for RpcV2Protocol."""

    auth_scheme_resolver: DefaultAuthResolver
    """
    An auth scheme resolver that determines the auth scheme for each
    operation.
    """

    auth_schemes: dict[ShapeID, AuthScheme[Any, Any, Any, Any]]
    """A map of auth scheme ids to auth schemes."""

    endpoint_resolver: EndpointResolver
    """
    The endpoint resolver used to resolve the final endpoint per-operation
    based on the configuration.
    """

    endpoint_uri: str | URI | None
    """A static URI to route requests to."""

    http_request_config: HTTPRequestConfiguration | None
    """Configuration for individual HTTP requests."""

    interceptors: list[_ServiceInterceptor]
    """
    The list of interceptors, which are hooks that are called during the
    execution of a request.
    """

    protocol: ClientProtocol[Any, Any] | None
    """The protocol to serialize and deserialize requests with."""

    region: str | None
    """
    The AWS region to connect to. The configured region is used to determine
    the service endpoint.
    """

    retry_strategy: RetryStrategy | RetryStrategyOptions | None
    """
    The retry strategy or options for configuring retry behavior. Can be
    either a configured RetryStrategy or RetryStrategyOptions to create one.
    """

    sdk_ua_app_id: str | None
    """
    A unique and opaque application ID that is appended to the User-Agent
    header.
    """

    transport: ClientTransport[Any, Any] | None
    """
    The transport to use to send requests (e.g. an HTTP client). Operations
    with bidirectional event streams require a DuplexClientTransport, such
    as AWSCRTHTTPClient. Transports are assumed not to support duplex
    streaming unless they explicitly set SUPPORTS_DUPLEX_STREAMING to True.
    """

    user_agent_extra: str | None
    """Additional suffix to be added to the User-Agent header."""

    def __init__(
        self,
        *,
        auth_scheme_resolver: DefaultAuthResolver | None = None,
        auth_schemes: dict[ShapeID, AuthScheme[Any, Any, Any, Any]] | None = None,
        endpoint_resolver: EndpointResolver | None = None,
        endpoint_uri: str | URI | None = None,
        http_request_config: HTTPRequestConfiguration | None = None,
        interceptors: list[_ServiceInterceptor] | None = None,
        protocol: ClientProtocol[Any, Any] | None = None,
        region: str | None = None,
        retry_strategy: RetryStrategy | RetryStrategyOptions | None = None,
        sdk_ua_app_id: str | None = None,
        transport: ClientTransport[Any, Any] | None = None,
        user_agent_extra: str | None = None,
    ):
        self.auth_scheme_resolver = auth_scheme_resolver or DefaultAuthResolver()
        self.auth_schemes = auth_schemes or {}
        self.endpoint_resolver = endpoint_resolver or StandardRegionalEndpointsResolver(
            endpoint_prefix="RpcV2Protocol"
        )
        self.endpoint_uri = endpoint_uri
        self.http_request_config = http_request_config
        self.interceptors = interceptors or []
        self.protocol = protocol or RpcV2CborClientProtocol(_SCHEMA_RPC_V2_PROTOCOL)
        self.region = region
        self.retry_strategy = retry_strategy
        self.sdk_ua_app_id = sdk_ua_app_id
        self.transport = transport or AIOHTTPClient()
        self.user_agent_extra = user_agent_extra


Plugin: TypeAlias = Callable[[Config], None]
"""
A callable that customizes a client configuration. Service-level plugins
are applied once to the base configuration inherited by every operation.
Operation-level plugins apply only to a single operation invocation.
"""
