[project]
name = "smithy_http"
version = "0.0.1"
description = "HTTP components for Smithy tooling."
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "smithy-core",
]

[project.optional-dependencies]
awscrt = [
    "awscrt>=0.23.10",
]
aiohttp = [
    "aiohttp>=3.11.12",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build]
exclude = [
  "tests",
]

[tool.hatch.build.hooks.version]
path = "src/smithy_http/__init__.py"
pattern = "__version__: str = \"(?P<version>.+)\""

[tool.ruff]
src = ["src"]
