[project]
name = "smithy-http"
version = "0.0.1"
description = "HTTP components for Smithy tooling."
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "smithy-core",
]

[project.optional-dependencies]
awscrt = [
    "awscrt>=0.27.2",
]
aiohttp = [
    "aiohttp>=3.11.12, <4.0",
    "yarl"
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build]
exclude = [
  "tests",
]

[tool.ruff]
src = ["src"]
