[project]
name = "smithy_http"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Hayden Baker", email = "haydebak@amazon.com" }
]
requires-python = ">=3.12"
dependencies = [
    "smithy-core",
]

[project.optional-dependencies]
awscrt = [
    "awscrt>=0.23.10",
]
aiohttp = [
    "aiohttp>=3.11.12",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
