# Code generated by smithy-python-codegen DO NOT EDIT.

from types import MappingProxyType

from smithy_core.schemas import Schema
from smithy_core.shapes import ShapeID, ShapeType
from smithy_core.traits import Trait


ACCESS_KEY_ID_TYPE = Schema(
    id=ShapeID("com.amazonaws.sts#accessKeyIdType"),
    shape_type=ShapeType.STRING,
    traits=[
        Trait.new(
            id=ShapeID("smithy.api#length"),
            value=MappingProxyType({"min": 16, "max": 128}),
        ),
        Trait.new(id=ShapeID("smithy.api#pattern"), value="^[\\w]*$"),
    ],
)

ACCESS_KEY_SECRET_TYPE = Schema(
    id=ShapeID("com.amazonaws.sts#accessKeySecretType"),
    shape_type=ShapeType.STRING,
    traits=[Trait.new(id=ShapeID("smithy.api#sensitive"))],
)

ARN_TYPE = Schema(
    id=ShapeID("com.amazonaws.sts#arnType"),
    shape_type=ShapeType.STRING,
    traits=[
        Trait.new(
            id=ShapeID("smithy.api#length"),
            value=MappingProxyType({"min": 20, "max": 2048}),
        ),
        Trait.new(
            id=ShapeID("smithy.api#pattern"),
            value="^[\\u0009\\u000A\\u000D\\u0020-\\u007E\\u0085\\u00A0-\\uD7FF\\uE000-\\uFFFD\\u10000-\\u10FFFF]+$",
        ),
    ],
)

ASSUMED_ROLE_ID_TYPE = Schema(
    id=ShapeID("com.amazonaws.sts#assumedRoleIdType"),
    shape_type=ShapeType.STRING,
    traits=[
        Trait.new(
            id=ShapeID("smithy.api#length"),
            value=MappingProxyType({"min": 2, "max": 193}),
        ),
        Trait.new(id=ShapeID("smithy.api#pattern"), value="^[\\w+=,.@:-]*$"),
    ],
)

ASSUMED_ROLE_USER = Schema.collection(
    id=ShapeID("com.amazonaws.sts#AssumedRoleUser"),
    members={
        "AssumedRoleId": {
            "target": ASSUMED_ROLE_ID_TYPE,
            "traits": [Trait.new(id=ShapeID("smithy.api#required"))],
        },
        "Arn": {
            "target": ARN_TYPE,
            "traits": [Trait.new(id=ShapeID("smithy.api#required"))],
        },
    },
)

ROLE_DURATION_SECONDS_TYPE = Schema(
    id=ShapeID("com.amazonaws.sts#roleDurationSecondsType"),
    shape_type=ShapeType.INTEGER,
    traits=[
        Trait.new(id=ShapeID("smithy.api#box")),
        Trait.new(
            id=ShapeID("smithy.api#range"),
            value=MappingProxyType({"min": 900, "max": 43200}),
        ),
    ],
)

EXTERNAL_ID_TYPE = Schema(
    id=ShapeID("com.amazonaws.sts#externalIdType"),
    shape_type=ShapeType.STRING,
    traits=[
        Trait.new(
            id=ShapeID("smithy.api#length"),
            value=MappingProxyType({"min": 2, "max": 1224}),
        ),
        Trait.new(id=ShapeID("smithy.api#pattern"), value="^[\\w+=,.@:\\/-]*$"),
    ],
)

UNRESTRICTED_SESSION_POLICY_DOCUMENT_TYPE = Schema(
    id=ShapeID("com.amazonaws.sts#unrestrictedSessionPolicyDocumentType"),
    shape_type=ShapeType.STRING,
    traits=[
        Trait.new(id=ShapeID("smithy.api#length"), value=MappingProxyType({"min": 1})),
        Trait.new(
            id=ShapeID("smithy.api#pattern"),
            value="^[\\u0009\\u000A\\u000D\\u0020-\\u00FF]+$",
        ),
    ],
)

POLICY_DESCRIPTOR_TYPE = Schema.collection(
    id=ShapeID("com.amazonaws.sts#PolicyDescriptorType"),
    members={"arn": {"target": ARN_TYPE}},
)

POLICY_DESCRIPTOR_LIST_TYPE = Schema.collection(
    id=ShapeID("com.amazonaws.sts#policyDescriptorListType"),
    shape_type=ShapeType.LIST,
    members={"member": {"target": POLICY_DESCRIPTOR_TYPE}},
)

CONTEXT_ASSERTION_TYPE = Schema(
    id=ShapeID("com.amazonaws.sts#contextAssertionType"),
    shape_type=ShapeType.STRING,
    traits=[
        Trait.new(
            id=ShapeID("smithy.api#length"),
            value=MappingProxyType({"min": 4, "max": 2048}),
        )
    ],
)

PROVIDED_CONTEXT = Schema.collection(
    id=ShapeID("com.amazonaws.sts#ProvidedContext"),
    members={
        "ProviderArn": {"target": ARN_TYPE},
        "ContextAssertion": {"target": CONTEXT_ASSERTION_TYPE},
    },
)

PROVIDED_CONTEXTS_LIST_TYPE = Schema.collection(
    id=ShapeID("com.amazonaws.sts#ProvidedContextsListType"),
    shape_type=ShapeType.LIST,
    traits=[
        Trait.new(
            id=ShapeID("smithy.api#length"),
            value=MappingProxyType({"min": 1, "max": 5}),
        )
    ],
    members={"member": {"target": PROVIDED_CONTEXT}},
)

ROLE_SESSION_NAME_TYPE = Schema(
    id=ShapeID("com.amazonaws.sts#roleSessionNameType"),
    shape_type=ShapeType.STRING,
    traits=[
        Trait.new(
            id=ShapeID("smithy.api#length"),
            value=MappingProxyType({"min": 2, "max": 64}),
        ),
        Trait.new(id=ShapeID("smithy.api#pattern"), value="^[\\w+=,.@-]*$"),
    ],
)

SERIAL_NUMBER_TYPE = Schema(
    id=ShapeID("com.amazonaws.sts#serialNumberType"),
    shape_type=ShapeType.STRING,
    traits=[
        Trait.new(
            id=ShapeID("smithy.api#length"),
            value=MappingProxyType({"min": 9, "max": 256}),
        ),
        Trait.new(id=ShapeID("smithy.api#pattern"), value="^[\\w+=/:,.@-]*$"),
    ],
)

SOURCE_IDENTITY_TYPE = Schema(
    id=ShapeID("com.amazonaws.sts#sourceIdentityType"),
    shape_type=ShapeType.STRING,
    traits=[
        Trait.new(
            id=ShapeID("smithy.api#length"),
            value=MappingProxyType({"min": 2, "max": 64}),
        ),
        Trait.new(id=ShapeID("smithy.api#pattern"), value="^[\\w+=,.@-]*$"),
    ],
)

TAG_KEY_TYPE = Schema(
    id=ShapeID("com.amazonaws.sts#tagKeyType"),
    shape_type=ShapeType.STRING,
    traits=[
        Trait.new(
            id=ShapeID("smithy.api#length"),
            value=MappingProxyType({"min": 1, "max": 128}),
        ),
        Trait.new(
            id=ShapeID("smithy.api#pattern"), value="^[\\p{L}\\p{Z}\\p{N}_.:/=+\\-@]+$"
        ),
    ],
)

TAG_VALUE_TYPE = Schema(
    id=ShapeID("com.amazonaws.sts#tagValueType"),
    shape_type=ShapeType.STRING,
    traits=[
        Trait.new(
            id=ShapeID("smithy.api#length"),
            value=MappingProxyType({"min": 0, "max": 256}),
        ),
        Trait.new(
            id=ShapeID("smithy.api#pattern"), value="^[\\p{L}\\p{Z}\\p{N}_.:/=+\\-@]*$"
        ),
    ],
)

TAG = Schema.collection(
    id=ShapeID("com.amazonaws.sts#Tag"),
    members={
        "Key": {
            "target": TAG_KEY_TYPE,
            "traits": [Trait.new(id=ShapeID("smithy.api#required"))],
        },
        "Value": {
            "target": TAG_VALUE_TYPE,
            "traits": [Trait.new(id=ShapeID("smithy.api#required"))],
        },
    },
)

TAG_LIST_TYPE = Schema.collection(
    id=ShapeID("com.amazonaws.sts#tagListType"),
    shape_type=ShapeType.LIST,
    traits=[
        Trait.new(
            id=ShapeID("smithy.api#length"),
            value=MappingProxyType({"min": 0, "max": 50}),
        )
    ],
    members={"member": {"target": TAG}},
)

TOKEN_CODE_TYPE = Schema(
    id=ShapeID("com.amazonaws.sts#tokenCodeType"),
    shape_type=ShapeType.STRING,
    traits=[
        Trait.new(
            id=ShapeID("smithy.api#length"),
            value=MappingProxyType({"min": 6, "max": 6}),
        ),
        Trait.new(id=ShapeID("smithy.api#pattern"), value="^[\\d]*$"),
    ],
)

TAG_KEY_LIST_TYPE = Schema.collection(
    id=ShapeID("com.amazonaws.sts#tagKeyListType"),
    shape_type=ShapeType.LIST,
    traits=[
        Trait.new(
            id=ShapeID("smithy.api#length"),
            value=MappingProxyType({"min": 0, "max": 50}),
        )
    ],
    members={"member": {"target": TAG_KEY_TYPE}},
)

ASSUME_ROLE_INPUT = Schema.collection(
    id=ShapeID("com.amazonaws.sts#AssumeRoleInput"),
    traits=[
        Trait.new(
            id=ShapeID("smithy.synthetic#originalShapeId"),
            value="com.amazonaws.sts#AssumeRoleRequest",
        ),
        Trait.new(id=ShapeID("smithy.api#input")),
    ],
    members={
        "RoleArn": {
            "target": ARN_TYPE,
            "traits": [Trait.new(id=ShapeID("smithy.api#required"))],
        },
        "RoleSessionName": {
            "target": ROLE_SESSION_NAME_TYPE,
            "traits": [Trait.new(id=ShapeID("smithy.api#required"))],
        },
        "PolicyArns": {"target": POLICY_DESCRIPTOR_LIST_TYPE},
        "Policy": {"target": UNRESTRICTED_SESSION_POLICY_DOCUMENT_TYPE},
        "DurationSeconds": {"target": ROLE_DURATION_SECONDS_TYPE},
        "Tags": {"target": TAG_LIST_TYPE},
        "TransitiveTagKeys": {"target": TAG_KEY_LIST_TYPE},
        "ExternalId": {"target": EXTERNAL_ID_TYPE},
        "SerialNumber": {"target": SERIAL_NUMBER_TYPE},
        "TokenCode": {"target": TOKEN_CODE_TYPE},
        "SourceIdentity": {"target": SOURCE_IDENTITY_TYPE},
        "ProvidedContexts": {"target": PROVIDED_CONTEXTS_LIST_TYPE},
    },
)

DATE_TYPE = Schema(
    id=ShapeID("com.amazonaws.sts#dateType"), shape_type=ShapeType.TIMESTAMP
)

TOKEN_TYPE = Schema(
    id=ShapeID("com.amazonaws.sts#tokenType"), shape_type=ShapeType.STRING
)

CREDENTIALS = Schema.collection(
    id=ShapeID("com.amazonaws.sts#Credentials"),
    members={
        "AccessKeyId": {
            "target": ACCESS_KEY_ID_TYPE,
            "traits": [Trait.new(id=ShapeID("smithy.api#required"))],
        },
        "SecretAccessKey": {
            "target": ACCESS_KEY_SECRET_TYPE,
            "traits": [Trait.new(id=ShapeID("smithy.api#required"))],
        },
        "SessionToken": {
            "target": TOKEN_TYPE,
            "traits": [Trait.new(id=ShapeID("smithy.api#required"))],
        },
        "Expiration": {
            "target": DATE_TYPE,
            "traits": [Trait.new(id=ShapeID("smithy.api#required"))],
        },
    },
)

NON_NEGATIVE_INTEGER_TYPE = Schema(
    id=ShapeID("com.amazonaws.sts#nonNegativeIntegerType"),
    shape_type=ShapeType.INTEGER,
    traits=[
        Trait.new(id=ShapeID("smithy.api#box")),
        Trait.new(id=ShapeID("smithy.api#range"), value=MappingProxyType({"min": 0})),
    ],
)

ASSUME_ROLE_OUTPUT = Schema.collection(
    id=ShapeID("com.amazonaws.sts#AssumeRoleOutput"),
    traits=[
        Trait.new(
            id=ShapeID("smithy.synthetic#originalShapeId"),
            value="com.amazonaws.sts#AssumeRoleResponse",
        ),
        Trait.new(id=ShapeID("smithy.api#output")),
    ],
    members={
        "Credentials": {"target": CREDENTIALS},
        "AssumedRoleUser": {"target": ASSUMED_ROLE_USER},
        "PackedPolicySize": {"target": NON_NEGATIVE_INTEGER_TYPE},
        "SourceIdentity": {"target": SOURCE_IDENTITY_TYPE},
    },
)

EXPIRED_IDENTITY_TOKEN_MESSAGE = Schema(
    id=ShapeID("com.amazonaws.sts#expiredIdentityTokenMessage"),
    shape_type=ShapeType.STRING,
)

EXPIRED_TOKEN_EXCEPTION = Schema.collection(
    id=ShapeID("com.amazonaws.sts#ExpiredTokenException"),
    traits=[
        Trait.new(id=ShapeID("smithy.api#error"), value="client"),
        Trait.new(id=ShapeID("smithy.api#httpError"), value=400),
        Trait.new(
            id=ShapeID("aws.protocols#awsQueryError"),
            value=MappingProxyType(
                {"code": "ExpiredTokenException", "httpResponseCode": 400}
            ),
        ),
    ],
    members={"message": {"target": EXPIRED_IDENTITY_TOKEN_MESSAGE}},
)

MALFORMED_POLICY_DOCUMENT_MESSAGE = Schema(
    id=ShapeID("com.amazonaws.sts#malformedPolicyDocumentMessage"),
    shape_type=ShapeType.STRING,
)

MALFORMED_POLICY_DOCUMENT_EXCEPTION = Schema.collection(
    id=ShapeID("com.amazonaws.sts#MalformedPolicyDocumentException"),
    traits=[
        Trait.new(id=ShapeID("smithy.api#error"), value="client"),
        Trait.new(id=ShapeID("smithy.api#httpError"), value=400),
        Trait.new(
            id=ShapeID("aws.protocols#awsQueryError"),
            value=MappingProxyType(
                {"code": "MalformedPolicyDocument", "httpResponseCode": 400}
            ),
        ),
    ],
    members={"message": {"target": MALFORMED_POLICY_DOCUMENT_MESSAGE}},
)

PACKED_POLICY_TOO_LARGE_MESSAGE = Schema(
    id=ShapeID("com.amazonaws.sts#packedPolicyTooLargeMessage"),
    shape_type=ShapeType.STRING,
)

PACKED_POLICY_TOO_LARGE_EXCEPTION = Schema.collection(
    id=ShapeID("com.amazonaws.sts#PackedPolicyTooLargeException"),
    traits=[
        Trait.new(id=ShapeID("smithy.api#error"), value="client"),
        Trait.new(id=ShapeID("smithy.api#httpError"), value=400),
        Trait.new(
            id=ShapeID("aws.protocols#awsQueryError"),
            value=MappingProxyType(
                {"code": "PackedPolicyTooLarge", "httpResponseCode": 400}
            ),
        ),
    ],
    members={"message": {"target": PACKED_POLICY_TOO_LARGE_MESSAGE}},
)

REGION_DISABLED_MESSAGE = Schema(
    id=ShapeID("com.amazonaws.sts#regionDisabledMessage"), shape_type=ShapeType.STRING
)

REGION_DISABLED_EXCEPTION = Schema.collection(
    id=ShapeID("com.amazonaws.sts#RegionDisabledException"),
    traits=[
        Trait.new(id=ShapeID("smithy.api#error"), value="client"),
        Trait.new(id=ShapeID("smithy.api#httpError"), value=403),
        Trait.new(
            id=ShapeID("aws.protocols#awsQueryError"),
            value=MappingProxyType(
                {"code": "RegionDisabledException", "httpResponseCode": 403}
            ),
        ),
    ],
    members={"message": {"target": REGION_DISABLED_MESSAGE}},
)

ASSUME_ROLE = Schema(
    id=ShapeID("com.amazonaws.sts#AssumeRole"), shape_type=ShapeType.OPERATION
)

AWS_SECURITY_TOKEN_SERVICE_V20110615 = Schema(
    id=ShapeID("com.amazonaws.sts#AWSSecurityTokenServiceV20110615"),
    shape_type=ShapeType.SERVICE,
    traits=[
        Trait.new(
            id=ShapeID("aws.auth#sigv4"), value=MappingProxyType({"name": "sts"})
        ),
        Trait.new(id=ShapeID("smithy.api#title"), value="AWS Security Token Service"),
        Trait.new(
            id=ShapeID("aws.auth#sigv4a"), value=MappingProxyType({"name": "sts"})
        ),
        Trait.new(id=ShapeID("aws.protocols#awsQuery")),
        Trait.new(
            id=ShapeID("smithy.api#auth"), value=("aws.auth#sigv4", "aws.auth#sigv4a")
        ),
        Trait.new(
            id=ShapeID("aws.api#service"),
            value=MappingProxyType(
                {
                    "sdkId": "STS",
                    "arnNamespace": "sts",
                    "cloudFormationName": "STS",
                    "cloudTrailEventSource": "sts.amazonaws.com",
                    "endpointPrefix": "sts",
                }
            ),
        ),
        Trait.new(
            id=ShapeID("smithy.api#xmlNamespace"),
            value=MappingProxyType(
                {"uri": "https://sts.amazonaws.com/doc/2011-06-15/"}
            ),
        ),
    ],
)
