python_test_utils(
    name="test_utils",
    sources=[
        "**/__init__.py",
    ],
)

python_tests(
    name="tests",
    dependencies=[":test_utils"],
    sources=[
        "**/test_*.py",
    ],
)
