# Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: Apache-2.0

from __future__ import annotations

from ..context import GenerationContext
from ..docs import DocumentationConverter
from ..writer import GENERATED_HEADER


class SetupGenerator:
    def __init__(self, context: GenerationContext) -> None:
        self.context = context

    def run(self) -> None:
        module = self.context.settings.module_name
        self.context.write(
            f"src/{module}/__init__.py",
            f"{GENERATED_HEADER}\n__version__: str = {self.context.settings.module_version!r}\n",
            section="package.init",
        )
        self.context.write(
            f"src/{module}/_private/__init__.py",
            f"{GENERATED_HEADER}\n",
            section="package.private_init",
        )
        self.context.write(
            "pyproject.toml", self._pyproject(), section="package.pyproject"
        )
        self.context.write("README.md", self._readme(), section="package.readme")
        self.context.write(f"src/{module}/py.typed", "", section="package.py_typed")

    def _pyproject(self) -> str:
        settings = self.context.settings
        dependencies = sorted(
            dependency.requirement for dependency in self.context.dependencies
        )
        dependency_lines = "\n".join(
            f'    "{requirement}",' for requirement in dependencies
        )
        test_dependencies = ""
        if any(str(path).startswith("tests/") for path in self.context.manifest.files):
            test_dependencies = """
[dependency-groups]
test = [
    "pytest>=9,<10",
    "pytest-asyncio>=1,<2",
]
"""
        return f"""# Code generated by smithy-python. DO NOT EDIT.

[project]
name = {settings.module_name!r}
version = {settings.module_version!r}
description = {settings.description!r}
readme = "README.md"
requires-python = ">=3.12"
license = {{text = "Apache-2.0"}}
dependencies = [
{dependency_lines}
]
{test_dependencies}

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.pyright]
typeCheckingMode = "strict"
enableExperimentalFeatures = true

[tool.ruff]
target-version = "py312"
"""

    def _readme(self) -> str:
        service = self.context.service
        title = (
            service.id.name
            if service is not None
            else self.context.settings.module_name
        )
        if service is not None:
            trait_title = service.trait("smithy.api#title")
            if isinstance(trait_title, str):
                title = trait_title
        result = [f"# {title}", "", self.context.settings.description]
        if service is not None and isinstance(
            documentation := service.trait("smithy.api#documentation"), str
        ):
            result.extend(("", DocumentationConverter().convert(documentation)))
        return "\n".join(result).rstrip() + "\n"
