# Code generated by smithy-python-codegen DO NOT EDIT.

from dataclasses import dataclass, field
from datetime import datetime
import logging
from typing import Any, Literal, Self

from smithy_core.deserializers import ShapeDeserializer
from smithy_core.documents import TypeRegistry
from smithy_core.exceptions import ModeledError
from smithy_core.schemas import APIOperation, Schema
from smithy_core.serializers import ShapeSerializer
from smithy_core.shapes import ShapeID

from ._private.schemas import (
    ASSUMED_ROLE_USER as _SCHEMA_ASSUMED_ROLE_USER,
    ASSUME_ROLE as _SCHEMA_ASSUME_ROLE,
    ASSUME_ROLE_INPUT as _SCHEMA_ASSUME_ROLE_INPUT,
    ASSUME_ROLE_OUTPUT as _SCHEMA_ASSUME_ROLE_OUTPUT,
    CREDENTIALS as _SCHEMA_CREDENTIALS,
    EXPIRED_TOKEN_EXCEPTION as _SCHEMA_EXPIRED_TOKEN_EXCEPTION,
    MALFORMED_POLICY_DOCUMENT_EXCEPTION as _SCHEMA_MALFORMED_POLICY_DOCUMENT_EXCEPTION,
    PACKED_POLICY_TOO_LARGE_EXCEPTION as _SCHEMA_PACKED_POLICY_TOO_LARGE_EXCEPTION,
    POLICY_DESCRIPTOR_TYPE as _SCHEMA_POLICY_DESCRIPTOR_TYPE,
    PROVIDED_CONTEXT as _SCHEMA_PROVIDED_CONTEXT,
    REGION_DISABLED_EXCEPTION as _SCHEMA_REGION_DISABLED_EXCEPTION,
    TAG as _SCHEMA_TAG,
)


logger = logging.getLogger(__name__)


class ServiceError(ModeledError):
    """
    Base error for all errors in the service.

    Some exceptions do not extend from this class, including
    synthetic, implicit, and shared exception types.
    """


@dataclass(kw_only=True)
class AssumedRoleUser:
    """Dataclass for AssumedRoleUser structure."""

    assumed_role_id: str

    arn: str

    def serialize(self, serializer: ShapeSerializer):
        serializer.write_struct(_SCHEMA_ASSUMED_ROLE_USER, self)

    def serialize_members(self, serializer: ShapeSerializer):
        serializer.write_string(
            _SCHEMA_ASSUMED_ROLE_USER.members["AssumedRoleId"], self.assumed_role_id
        )
        serializer.write_string(_SCHEMA_ASSUMED_ROLE_USER.members["Arn"], self.arn)

    @classmethod
    def deserialize(cls, deserializer: ShapeDeserializer) -> Self:
        return cls(**cls.deserialize_kwargs(deserializer))

    @classmethod
    def deserialize_kwargs(cls, deserializer: ShapeDeserializer) -> dict[str, Any]:
        kwargs: dict[str, Any] = {}

        def _consumer(schema: Schema, de: ShapeDeserializer) -> None:
            match schema.expect_member_index():
                case 0:
                    kwargs["assumed_role_id"] = de.read_string(
                        _SCHEMA_ASSUMED_ROLE_USER.members["AssumedRoleId"]
                    )

                case 1:
                    kwargs["arn"] = de.read_string(
                        _SCHEMA_ASSUMED_ROLE_USER.members["Arn"]
                    )

                case _:
                    logger.debug("Unexpected member schema: %s", schema)

        deserializer.read_struct(_SCHEMA_ASSUMED_ROLE_USER, consumer=_consumer)
        return kwargs


@dataclass(kw_only=True)
class PolicyDescriptorType:
    """Dataclass for PolicyDescriptorType structure."""

    arn: str | None = None

    def serialize(self, serializer: ShapeSerializer):
        serializer.write_struct(_SCHEMA_POLICY_DESCRIPTOR_TYPE, self)

    def serialize_members(self, serializer: ShapeSerializer):
        if self.arn is not None:
            serializer.write_string(
                _SCHEMA_POLICY_DESCRIPTOR_TYPE.members["arn"], self.arn
            )

    @classmethod
    def deserialize(cls, deserializer: ShapeDeserializer) -> Self:
        return cls(**cls.deserialize_kwargs(deserializer))

    @classmethod
    def deserialize_kwargs(cls, deserializer: ShapeDeserializer) -> dict[str, Any]:
        kwargs: dict[str, Any] = {}

        def _consumer(schema: Schema, de: ShapeDeserializer) -> None:
            match schema.expect_member_index():
                case 0:
                    kwargs["arn"] = de.read_string(
                        _SCHEMA_POLICY_DESCRIPTOR_TYPE.members["arn"]
                    )

                case _:
                    logger.debug("Unexpected member schema: %s", schema)

        deserializer.read_struct(_SCHEMA_POLICY_DESCRIPTOR_TYPE, consumer=_consumer)
        return kwargs


def _serialize_policy_descriptor_list_type(
    serializer: ShapeSerializer, schema: Schema, value: list[PolicyDescriptorType]
) -> None:
    member_schema = schema.members["member"]
    with serializer.begin_list(schema, len(value)) as ls:
        for e in value:
            ls.write_struct(member_schema, e)


def _deserialize_policy_descriptor_list_type(
    deserializer: ShapeDeserializer, schema: Schema
) -> list[PolicyDescriptorType]:
    result: list[PolicyDescriptorType] = []

    def _read_value(d: ShapeDeserializer):
        if d.is_null():
            d.read_null()

        else:
            result.append(PolicyDescriptorType.deserialize(d))

    deserializer.read_list(schema, _read_value)
    return result


@dataclass(kw_only=True)
class ProvidedContext:
    """Dataclass for ProvidedContext structure."""

    provider_arn: str | None = None

    context_assertion: str | None = None

    def serialize(self, serializer: ShapeSerializer):
        serializer.write_struct(_SCHEMA_PROVIDED_CONTEXT, self)

    def serialize_members(self, serializer: ShapeSerializer):
        if self.provider_arn is not None:
            serializer.write_string(
                _SCHEMA_PROVIDED_CONTEXT.members["ProviderArn"], self.provider_arn
            )

        if self.context_assertion is not None:
            serializer.write_string(
                _SCHEMA_PROVIDED_CONTEXT.members["ContextAssertion"],
                self.context_assertion,
            )

    @classmethod
    def deserialize(cls, deserializer: ShapeDeserializer) -> Self:
        return cls(**cls.deserialize_kwargs(deserializer))

    @classmethod
    def deserialize_kwargs(cls, deserializer: ShapeDeserializer) -> dict[str, Any]:
        kwargs: dict[str, Any] = {}

        def _consumer(schema: Schema, de: ShapeDeserializer) -> None:
            match schema.expect_member_index():
                case 0:
                    kwargs["provider_arn"] = de.read_string(
                        _SCHEMA_PROVIDED_CONTEXT.members["ProviderArn"]
                    )

                case 1:
                    kwargs["context_assertion"] = de.read_string(
                        _SCHEMA_PROVIDED_CONTEXT.members["ContextAssertion"]
                    )

                case _:
                    logger.debug("Unexpected member schema: %s", schema)

        deserializer.read_struct(_SCHEMA_PROVIDED_CONTEXT, consumer=_consumer)
        return kwargs


def _serialize_provided_contexts_list_type(
    serializer: ShapeSerializer, schema: Schema, value: list[ProvidedContext]
) -> None:
    member_schema = schema.members["member"]
    with serializer.begin_list(schema, len(value)) as ls:
        for e in value:
            ls.write_struct(member_schema, e)


def _deserialize_provided_contexts_list_type(
    deserializer: ShapeDeserializer, schema: Schema
) -> list[ProvidedContext]:
    result: list[ProvidedContext] = []

    def _read_value(d: ShapeDeserializer):
        if d.is_null():
            d.read_null()

        else:
            result.append(ProvidedContext.deserialize(d))

    deserializer.read_list(schema, _read_value)
    return result


@dataclass(kw_only=True)
class Tag:
    """Dataclass for Tag structure."""

    key: str

    value: str

    def serialize(self, serializer: ShapeSerializer):
        serializer.write_struct(_SCHEMA_TAG, self)

    def serialize_members(self, serializer: ShapeSerializer):
        serializer.write_string(_SCHEMA_TAG.members["Key"], self.key)
        serializer.write_string(_SCHEMA_TAG.members["Value"], self.value)

    @classmethod
    def deserialize(cls, deserializer: ShapeDeserializer) -> Self:
        return cls(**cls.deserialize_kwargs(deserializer))

    @classmethod
    def deserialize_kwargs(cls, deserializer: ShapeDeserializer) -> dict[str, Any]:
        kwargs: dict[str, Any] = {}

        def _consumer(schema: Schema, de: ShapeDeserializer) -> None:
            match schema.expect_member_index():
                case 0:
                    kwargs["key"] = de.read_string(_SCHEMA_TAG.members["Key"])

                case 1:
                    kwargs["value"] = de.read_string(_SCHEMA_TAG.members["Value"])

                case _:
                    logger.debug("Unexpected member schema: %s", schema)

        deserializer.read_struct(_SCHEMA_TAG, consumer=_consumer)
        return kwargs


def _serialize_tag_list_type(
    serializer: ShapeSerializer, schema: Schema, value: list[Tag]
) -> None:
    member_schema = schema.members["member"]
    with serializer.begin_list(schema, len(value)) as ls:
        for e in value:
            ls.write_struct(member_schema, e)


def _deserialize_tag_list_type(
    deserializer: ShapeDeserializer, schema: Schema
) -> list[Tag]:
    result: list[Tag] = []

    def _read_value(d: ShapeDeserializer):
        if d.is_null():
            d.read_null()

        else:
            result.append(Tag.deserialize(d))

    deserializer.read_list(schema, _read_value)
    return result


def _serialize_tag_key_list_type(
    serializer: ShapeSerializer, schema: Schema, value: list[str]
) -> None:
    member_schema = schema.members["member"]
    with serializer.begin_list(schema, len(value)) as ls:
        for e in value:
            ls.write_string(member_schema, e)


def _deserialize_tag_key_list_type(
    deserializer: ShapeDeserializer, schema: Schema
) -> list[str]:
    result: list[str] = []
    member_schema = schema.members["member"]

    def _read_value(d: ShapeDeserializer):
        if d.is_null():
            d.read_null()

        else:
            result.append(d.read_string(member_schema))

    deserializer.read_list(schema, _read_value)
    return result


@dataclass(kw_only=True)
class AssumeRoleInput:
    """Dataclass for AssumeRoleInput structure."""

    role_arn: str | None = None

    role_session_name: str | None = None

    policy_arns: list[PolicyDescriptorType] | None = None

    policy: str | None = None

    duration_seconds: int | None = None

    tags: list[Tag] | None = None

    transitive_tag_keys: list[str] | None = None

    external_id: str | None = None

    serial_number: str | None = None

    token_code: str | None = None

    source_identity: str | None = None

    provided_contexts: list[ProvidedContext] | None = None

    def serialize(self, serializer: ShapeSerializer):
        serializer.write_struct(_SCHEMA_ASSUME_ROLE_INPUT, self)

    def serialize_members(self, serializer: ShapeSerializer):
        if self.role_arn is not None:
            serializer.write_string(
                _SCHEMA_ASSUME_ROLE_INPUT.members["RoleArn"], self.role_arn
            )

        if self.role_session_name is not None:
            serializer.write_string(
                _SCHEMA_ASSUME_ROLE_INPUT.members["RoleSessionName"],
                self.role_session_name,
            )

        if self.policy_arns is not None:
            _serialize_policy_descriptor_list_type(
                serializer,
                _SCHEMA_ASSUME_ROLE_INPUT.members["PolicyArns"],
                self.policy_arns,
            )

        if self.policy is not None:
            serializer.write_string(
                _SCHEMA_ASSUME_ROLE_INPUT.members["Policy"], self.policy
            )

        if self.duration_seconds is not None:
            serializer.write_integer(
                _SCHEMA_ASSUME_ROLE_INPUT.members["DurationSeconds"],
                self.duration_seconds,
            )

        if self.tags is not None:
            _serialize_tag_list_type(
                serializer, _SCHEMA_ASSUME_ROLE_INPUT.members["Tags"], self.tags
            )

        if self.transitive_tag_keys is not None:
            _serialize_tag_key_list_type(
                serializer,
                _SCHEMA_ASSUME_ROLE_INPUT.members["TransitiveTagKeys"],
                self.transitive_tag_keys,
            )

        if self.external_id is not None:
            serializer.write_string(
                _SCHEMA_ASSUME_ROLE_INPUT.members["ExternalId"], self.external_id
            )

        if self.serial_number is not None:
            serializer.write_string(
                _SCHEMA_ASSUME_ROLE_INPUT.members["SerialNumber"], self.serial_number
            )

        if self.token_code is not None:
            serializer.write_string(
                _SCHEMA_ASSUME_ROLE_INPUT.members["TokenCode"], self.token_code
            )

        if self.source_identity is not None:
            serializer.write_string(
                _SCHEMA_ASSUME_ROLE_INPUT.members["SourceIdentity"],
                self.source_identity,
            )

        if self.provided_contexts is not None:
            _serialize_provided_contexts_list_type(
                serializer,
                _SCHEMA_ASSUME_ROLE_INPUT.members["ProvidedContexts"],
                self.provided_contexts,
            )

    @classmethod
    def deserialize(cls, deserializer: ShapeDeserializer) -> Self:
        return cls(**cls.deserialize_kwargs(deserializer))

    @classmethod
    def deserialize_kwargs(cls, deserializer: ShapeDeserializer) -> dict[str, Any]:
        kwargs: dict[str, Any] = {}

        def _consumer(schema: Schema, de: ShapeDeserializer) -> None:
            match schema.expect_member_index():
                case 0:
                    kwargs["role_arn"] = de.read_string(
                        _SCHEMA_ASSUME_ROLE_INPUT.members["RoleArn"]
                    )

                case 1:
                    kwargs["role_session_name"] = de.read_string(
                        _SCHEMA_ASSUME_ROLE_INPUT.members["RoleSessionName"]
                    )

                case 2:
                    kwargs["policy_arns"] = _deserialize_policy_descriptor_list_type(
                        de, _SCHEMA_ASSUME_ROLE_INPUT.members["PolicyArns"]
                    )

                case 3:
                    kwargs["policy"] = de.read_string(
                        _SCHEMA_ASSUME_ROLE_INPUT.members["Policy"]
                    )

                case 4:
                    kwargs["duration_seconds"] = de.read_integer(
                        _SCHEMA_ASSUME_ROLE_INPUT.members["DurationSeconds"]
                    )

                case 5:
                    kwargs["tags"] = _deserialize_tag_list_type(
                        de, _SCHEMA_ASSUME_ROLE_INPUT.members["Tags"]
                    )

                case 6:
                    kwargs["transitive_tag_keys"] = _deserialize_tag_key_list_type(
                        de, _SCHEMA_ASSUME_ROLE_INPUT.members["TransitiveTagKeys"]
                    )

                case 7:
                    kwargs["external_id"] = de.read_string(
                        _SCHEMA_ASSUME_ROLE_INPUT.members["ExternalId"]
                    )

                case 8:
                    kwargs["serial_number"] = de.read_string(
                        _SCHEMA_ASSUME_ROLE_INPUT.members["SerialNumber"]
                    )

                case 9:
                    kwargs["token_code"] = de.read_string(
                        _SCHEMA_ASSUME_ROLE_INPUT.members["TokenCode"]
                    )

                case 10:
                    kwargs["source_identity"] = de.read_string(
                        _SCHEMA_ASSUME_ROLE_INPUT.members["SourceIdentity"]
                    )

                case 11:
                    kwargs["provided_contexts"] = (
                        _deserialize_provided_contexts_list_type(
                            de, _SCHEMA_ASSUME_ROLE_INPUT.members["ProvidedContexts"]
                        )
                    )

                case _:
                    logger.debug("Unexpected member schema: %s", schema)

        deserializer.read_struct(_SCHEMA_ASSUME_ROLE_INPUT, consumer=_consumer)
        return kwargs


@dataclass(kw_only=True)
class Credentials:
    """Dataclass for Credentials structure."""

    access_key_id: str

    secret_access_key: str = field(repr=False)

    session_token: str

    expiration: datetime

    def serialize(self, serializer: ShapeSerializer):
        serializer.write_struct(_SCHEMA_CREDENTIALS, self)

    def serialize_members(self, serializer: ShapeSerializer):
        serializer.write_string(
            _SCHEMA_CREDENTIALS.members["AccessKeyId"], self.access_key_id
        )
        serializer.write_string(
            _SCHEMA_CREDENTIALS.members["SecretAccessKey"], self.secret_access_key
        )
        serializer.write_string(
            _SCHEMA_CREDENTIALS.members["SessionToken"], self.session_token
        )
        serializer.write_timestamp(
            _SCHEMA_CREDENTIALS.members["Expiration"], self.expiration
        )

    @classmethod
    def deserialize(cls, deserializer: ShapeDeserializer) -> Self:
        return cls(**cls.deserialize_kwargs(deserializer))

    @classmethod
    def deserialize_kwargs(cls, deserializer: ShapeDeserializer) -> dict[str, Any]:
        kwargs: dict[str, Any] = {}

        def _consumer(schema: Schema, de: ShapeDeserializer) -> None:
            match schema.expect_member_index():
                case 0:
                    kwargs["access_key_id"] = de.read_string(
                        _SCHEMA_CREDENTIALS.members["AccessKeyId"]
                    )

                case 1:
                    kwargs["secret_access_key"] = de.read_string(
                        _SCHEMA_CREDENTIALS.members["SecretAccessKey"]
                    )

                case 2:
                    kwargs["session_token"] = de.read_string(
                        _SCHEMA_CREDENTIALS.members["SessionToken"]
                    )

                case 3:
                    kwargs["expiration"] = de.read_timestamp(
                        _SCHEMA_CREDENTIALS.members["Expiration"]
                    )

                case _:
                    logger.debug("Unexpected member schema: %s", schema)

        deserializer.read_struct(_SCHEMA_CREDENTIALS, consumer=_consumer)
        return kwargs


@dataclass(kw_only=True)
class AssumeRoleOutput:
    """Dataclass for AssumeRoleOutput structure."""

    credentials: Credentials | None = None

    assumed_role_user: AssumedRoleUser | None = None

    packed_policy_size: int | None = None

    source_identity: str | None = None

    def serialize(self, serializer: ShapeSerializer):
        serializer.write_struct(_SCHEMA_ASSUME_ROLE_OUTPUT, self)

    def serialize_members(self, serializer: ShapeSerializer):
        if self.credentials is not None:
            serializer.write_struct(
                _SCHEMA_ASSUME_ROLE_OUTPUT.members["Credentials"], self.credentials
            )

        if self.assumed_role_user is not None:
            serializer.write_struct(
                _SCHEMA_ASSUME_ROLE_OUTPUT.members["AssumedRoleUser"],
                self.assumed_role_user,
            )

        if self.packed_policy_size is not None:
            serializer.write_integer(
                _SCHEMA_ASSUME_ROLE_OUTPUT.members["PackedPolicySize"],
                self.packed_policy_size,
            )

        if self.source_identity is not None:
            serializer.write_string(
                _SCHEMA_ASSUME_ROLE_OUTPUT.members["SourceIdentity"],
                self.source_identity,
            )

    @classmethod
    def deserialize(cls, deserializer: ShapeDeserializer) -> Self:
        return cls(**cls.deserialize_kwargs(deserializer))

    @classmethod
    def deserialize_kwargs(cls, deserializer: ShapeDeserializer) -> dict[str, Any]:
        kwargs: dict[str, Any] = {}

        def _consumer(schema: Schema, de: ShapeDeserializer) -> None:
            match schema.expect_member_index():
                case 0:
                    kwargs["credentials"] = Credentials.deserialize(de)

                case 1:
                    kwargs["assumed_role_user"] = AssumedRoleUser.deserialize(de)

                case 2:
                    kwargs["packed_policy_size"] = de.read_integer(
                        _SCHEMA_ASSUME_ROLE_OUTPUT.members["PackedPolicySize"]
                    )

                case 3:
                    kwargs["source_identity"] = de.read_string(
                        _SCHEMA_ASSUME_ROLE_OUTPUT.members["SourceIdentity"]
                    )

                case _:
                    logger.debug("Unexpected member schema: %s", schema)

        deserializer.read_struct(_SCHEMA_ASSUME_ROLE_OUTPUT, consumer=_consumer)
        return kwargs


@dataclass(kw_only=True)
class ExpiredTokenException(ServiceError):
    """Dataclass for ExpiredTokenException structure."""

    fault: Literal["client", "server"] | None = "client"

    def serialize(self, serializer: ShapeSerializer):
        serializer.write_struct(_SCHEMA_EXPIRED_TOKEN_EXCEPTION, self)

    def serialize_members(self, serializer: ShapeSerializer):
        if self.message is not None:
            serializer.write_string(
                _SCHEMA_EXPIRED_TOKEN_EXCEPTION.members["message"], self.message
            )

    @classmethod
    def deserialize(cls, deserializer: ShapeDeserializer) -> Self:
        return cls(**cls.deserialize_kwargs(deserializer))

    @classmethod
    def deserialize_kwargs(cls, deserializer: ShapeDeserializer) -> dict[str, Any]:
        kwargs: dict[str, Any] = {}

        def _consumer(schema: Schema, de: ShapeDeserializer) -> None:
            match schema.expect_member_index():
                case 0:
                    kwargs["message"] = de.read_string(
                        _SCHEMA_EXPIRED_TOKEN_EXCEPTION.members["message"]
                    )

                case _:
                    logger.debug("Unexpected member schema: %s", schema)

        deserializer.read_struct(_SCHEMA_EXPIRED_TOKEN_EXCEPTION, consumer=_consumer)
        return kwargs


@dataclass(kw_only=True)
class MalformedPolicyDocumentException(ServiceError):
    """Dataclass for MalformedPolicyDocumentException structure."""

    fault: Literal["client", "server"] | None = "client"

    def serialize(self, serializer: ShapeSerializer):
        serializer.write_struct(_SCHEMA_MALFORMED_POLICY_DOCUMENT_EXCEPTION, self)

    def serialize_members(self, serializer: ShapeSerializer):
        if self.message is not None:
            serializer.write_string(
                _SCHEMA_MALFORMED_POLICY_DOCUMENT_EXCEPTION.members["message"],
                self.message,
            )

    @classmethod
    def deserialize(cls, deserializer: ShapeDeserializer) -> Self:
        return cls(**cls.deserialize_kwargs(deserializer))

    @classmethod
    def deserialize_kwargs(cls, deserializer: ShapeDeserializer) -> dict[str, Any]:
        kwargs: dict[str, Any] = {}

        def _consumer(schema: Schema, de: ShapeDeserializer) -> None:
            match schema.expect_member_index():
                case 0:
                    kwargs["message"] = de.read_string(
                        _SCHEMA_MALFORMED_POLICY_DOCUMENT_EXCEPTION.members["message"]
                    )

                case _:
                    logger.debug("Unexpected member schema: %s", schema)

        deserializer.read_struct(
            _SCHEMA_MALFORMED_POLICY_DOCUMENT_EXCEPTION, consumer=_consumer
        )
        return kwargs


@dataclass(kw_only=True)
class PackedPolicyTooLargeException(ServiceError):
    """Dataclass for PackedPolicyTooLargeException structure."""

    fault: Literal["client", "server"] | None = "client"

    def serialize(self, serializer: ShapeSerializer):
        serializer.write_struct(_SCHEMA_PACKED_POLICY_TOO_LARGE_EXCEPTION, self)

    def serialize_members(self, serializer: ShapeSerializer):
        if self.message is not None:
            serializer.write_string(
                _SCHEMA_PACKED_POLICY_TOO_LARGE_EXCEPTION.members["message"],
                self.message,
            )

    @classmethod
    def deserialize(cls, deserializer: ShapeDeserializer) -> Self:
        return cls(**cls.deserialize_kwargs(deserializer))

    @classmethod
    def deserialize_kwargs(cls, deserializer: ShapeDeserializer) -> dict[str, Any]:
        kwargs: dict[str, Any] = {}

        def _consumer(schema: Schema, de: ShapeDeserializer) -> None:
            match schema.expect_member_index():
                case 0:
                    kwargs["message"] = de.read_string(
                        _SCHEMA_PACKED_POLICY_TOO_LARGE_EXCEPTION.members["message"]
                    )

                case _:
                    logger.debug("Unexpected member schema: %s", schema)

        deserializer.read_struct(
            _SCHEMA_PACKED_POLICY_TOO_LARGE_EXCEPTION, consumer=_consumer
        )
        return kwargs


@dataclass(kw_only=True)
class RegionDisabledException(ServiceError):
    """Dataclass for RegionDisabledException structure."""

    fault: Literal["client", "server"] | None = "client"

    def serialize(self, serializer: ShapeSerializer):
        serializer.write_struct(_SCHEMA_REGION_DISABLED_EXCEPTION, self)

    def serialize_members(self, serializer: ShapeSerializer):
        if self.message is not None:
            serializer.write_string(
                _SCHEMA_REGION_DISABLED_EXCEPTION.members["message"], self.message
            )

    @classmethod
    def deserialize(cls, deserializer: ShapeDeserializer) -> Self:
        return cls(**cls.deserialize_kwargs(deserializer))

    @classmethod
    def deserialize_kwargs(cls, deserializer: ShapeDeserializer) -> dict[str, Any]:
        kwargs: dict[str, Any] = {}

        def _consumer(schema: Schema, de: ShapeDeserializer) -> None:
            match schema.expect_member_index():
                case 0:
                    kwargs["message"] = de.read_string(
                        _SCHEMA_REGION_DISABLED_EXCEPTION.members["message"]
                    )

                case _:
                    logger.debug("Unexpected member schema: %s", schema)

        deserializer.read_struct(_SCHEMA_REGION_DISABLED_EXCEPTION, consumer=_consumer)
        return kwargs


ASSUME_ROLE = APIOperation(
    input=AssumeRoleInput,
    output=AssumeRoleOutput,
    schema=_SCHEMA_ASSUME_ROLE,
    input_schema=_SCHEMA_ASSUME_ROLE_INPUT,
    output_schema=_SCHEMA_ASSUME_ROLE_OUTPUT,
    error_registry=TypeRegistry(
        {
            ShapeID("com.amazonaws.sts#ExpiredTokenException"): ExpiredTokenException,
            ShapeID(
                "com.amazonaws.sts#MalformedPolicyDocumentException"
            ): MalformedPolicyDocumentException,
            ShapeID(
                "com.amazonaws.sts#PackedPolicyTooLargeException"
            ): PackedPolicyTooLargeException,
            ShapeID(
                "com.amazonaws.sts#RegionDisabledException"
            ): RegionDisabledException,
        }
    ),
    effective_auth_schemes=[ShapeID("aws.auth#sigv4"), ShapeID("aws.auth#sigv4a")],
    error_schemas=[
        _SCHEMA_EXPIRED_TOKEN_EXCEPTION,
        _SCHEMA_MALFORMED_POLICY_DOCUMENT_EXCEPTION,
        _SCHEMA_PACKED_POLICY_TOO_LARGE_EXCEPTION,
        _SCHEMA_REGION_DISABLED_EXCEPTION,
    ],
)
