# Code generated by smithy-python-codegen DO NOT EDIT.

from types import MappingProxyType

from smithy_core.prelude import (
    BLOB,
    BOOLEAN,
    BYTE,
    DOUBLE,
    FLOAT,
    INTEGER,
    LONG,
    SHORT,
    STRING,
    TIMESTAMP,
    UNIT,
)
from smithy_core.schemas import Schema
from smithy_core.shapes import ShapeID, ShapeType
from smithy_core.traits import Trait


DATETIME_OFFSETS_INPUT = Schema.collection(
    id=ShapeID("aws.protocoltests.query#DatetimeOffsetsInput"),
    traits=[
        Trait.new(
            id=ShapeID("smithy.synthetic#originalShapeId"), value="smithy.api#Unit"
        )
    ],
)

DATE_TIME = Schema(
    id=ShapeID("aws.protocoltests.shared#DateTime"),
    shape_type=ShapeType.TIMESTAMP,
    traits=[Trait.new(id=ShapeID("smithy.api#timestampFormat"), value="date-time")],
)

DATETIME_OFFSETS_OUTPUT = Schema.collection(
    id=ShapeID("aws.protocoltests.query#DatetimeOffsetsOutput"),
    members={"datetime": {"target": DATE_TIME}},
)

DATETIME_OFFSETS = Schema(
    id=ShapeID("aws.protocoltests.query#DatetimeOffsets"),
    shape_type=ShapeType.OPERATION,
)

EMPTY_INPUT_AND_EMPTY_OUTPUT_INPUT = Schema.collection(
    id=ShapeID("aws.protocoltests.query#EmptyInputAndEmptyOutputInput")
)

EMPTY_INPUT_AND_EMPTY_OUTPUT_OUTPUT = Schema.collection(
    id=ShapeID("aws.protocoltests.query#EmptyInputAndEmptyOutputOutput")
)

EMPTY_INPUT_AND_EMPTY_OUTPUT = Schema(
    id=ShapeID("aws.protocoltests.query#EmptyInputAndEmptyOutput"),
    shape_type=ShapeType.OPERATION,
)

ENDPOINT_OPERATION_INPUT = Schema.collection(
    id=ShapeID("aws.protocoltests.query#EndpointOperationInput"),
    traits=[
        Trait.new(
            id=ShapeID("smithy.synthetic#originalShapeId"), value="smithy.api#Unit"
        )
    ],
)

ENDPOINT_OPERATION_OUTPUT = Schema.collection(
    id=ShapeID("aws.protocoltests.query#EndpointOperationOutput"),
    traits=[
        Trait.new(
            id=ShapeID("smithy.synthetic#originalShapeId"), value="smithy.api#Unit"
        )
    ],
)

ENDPOINT_OPERATION = Schema(
    id=ShapeID("aws.protocoltests.query#EndpointOperation"),
    shape_type=ShapeType.OPERATION,
    traits=[
        Trait.new(
            id=ShapeID("smithy.api#endpoint"),
            value=MappingProxyType({"hostPrefix": "foo."}),
        )
    ],
)

ENDPOINT_WITH_HOST_LABEL_OPERATION_INPUT = Schema.collection(
    id=ShapeID("aws.protocoltests.query#EndpointWithHostLabelOperationInput"),
    traits=[
        Trait.new(
            id=ShapeID("smithy.synthetic#originalShapeId"),
            value="aws.protocoltests.query#HostLabelInput",
        )
    ],
    members={
        "label": {
            "target": STRING,
            "traits": [
                Trait.new(id=ShapeID("smithy.api#hostLabel")),
                Trait.new(id=ShapeID("smithy.api#required")),
            ],
        }
    },
)

ENDPOINT_WITH_HOST_LABEL_OPERATION_OUTPUT = Schema.collection(
    id=ShapeID("aws.protocoltests.query#EndpointWithHostLabelOperationOutput"),
    traits=[
        Trait.new(
            id=ShapeID("smithy.synthetic#originalShapeId"), value="smithy.api#Unit"
        )
    ],
)

ENDPOINT_WITH_HOST_LABEL_OPERATION = Schema(
    id=ShapeID("aws.protocoltests.query#EndpointWithHostLabelOperation"),
    shape_type=ShapeType.OPERATION,
    traits=[
        Trait.new(
            id=ShapeID("smithy.api#endpoint"),
            value=MappingProxyType({"hostPrefix": "foo.{label}."}),
        )
    ],
)

FLATTENED_XML_MAP_INPUT = Schema.collection(
    id=ShapeID("aws.protocoltests.query#FlattenedXmlMapInput"),
    traits=[
        Trait.new(
            id=ShapeID("smithy.synthetic#originalShapeId"), value="smithy.api#Unit"
        )
    ],
)

FOO_ENUM = Schema.collection(
    id=ShapeID("aws.protocoltests.shared#FooEnum"),
    shape_type=ShapeType.ENUM,
    members={
        "FOO": {"target": UNIT},
        "BAZ": {"target": UNIT},
        "BAR": {"target": UNIT},
        "ONE": {"target": UNIT},
        "ZERO": {"target": UNIT},
    },
)

FOO_ENUM_MAP = Schema.collection(
    id=ShapeID("aws.protocoltests.shared#FooEnumMap"),
    shape_type=ShapeType.MAP,
    members={"key": {"target": STRING}, "value": {"target": FOO_ENUM}},
)

FLATTENED_XML_MAP_OUTPUT = Schema.collection(
    id=ShapeID("aws.protocoltests.query#FlattenedXmlMapOutput"),
    members={
        "myMap": {
            "target": FOO_ENUM_MAP,
            "traits": [Trait.new(id=ShapeID("smithy.api#xmlFlattened"))],
        }
    },
)

FLATTENED_XML_MAP = Schema(
    id=ShapeID("aws.protocoltests.query#FlattenedXmlMap"),
    shape_type=ShapeType.OPERATION,
)

FLATTENED_XML_MAP_WITH_XML_NAME_INPUT = Schema.collection(
    id=ShapeID("aws.protocoltests.query#FlattenedXmlMapWithXmlNameInput"),
    traits=[
        Trait.new(
            id=ShapeID("smithy.synthetic#originalShapeId"), value="smithy.api#Unit"
        )
    ],
)

FLATTENED_XML_MAP_WITH_XML_NAME_OUTPUT_MAP = Schema.collection(
    id=ShapeID("aws.protocoltests.query#FlattenedXmlMapWithXmlNameOutputMap"),
    shape_type=ShapeType.MAP,
    members={
        "key": {
            "target": STRING,
            "traits": [Trait.new(id=ShapeID("smithy.api#xmlName"), value="K")],
        },
        "value": {
            "target": STRING,
            "traits": [Trait.new(id=ShapeID("smithy.api#xmlName"), value="V")],
        },
    },
)

FLATTENED_XML_MAP_WITH_XML_NAME_OUTPUT = Schema.collection(
    id=ShapeID("aws.protocoltests.query#FlattenedXmlMapWithXmlNameOutput"),
    members={
        "myMap": {
            "target": FLATTENED_XML_MAP_WITH_XML_NAME_OUTPUT_MAP,
            "traits": [
                Trait.new(id=ShapeID("smithy.api#xmlName"), value="KVP"),
                Trait.new(id=ShapeID("smithy.api#xmlFlattened")),
            ],
        }
    },
)

FLATTENED_XML_MAP_WITH_XML_NAME = Schema(
    id=ShapeID("aws.protocoltests.query#FlattenedXmlMapWithXmlName"),
    shape_type=ShapeType.OPERATION,
)

FLATTENED_XML_MAP_WITH_XML_NAMESPACE_INPUT = Schema.collection(
    id=ShapeID("aws.protocoltests.query#FlattenedXmlMapWithXmlNamespaceInput"),
    traits=[
        Trait.new(
            id=ShapeID("smithy.synthetic#originalShapeId"), value="smithy.api#Unit"
        )
    ],
)

FLATTENED_XML_MAP_WITH_XML_NAMESPACE_OUTPUT_MAP = Schema.collection(
    id=ShapeID("aws.protocoltests.query#FlattenedXmlMapWithXmlNamespaceOutputMap"),
    shape_type=ShapeType.MAP,
    members={
        "key": {
            "target": STRING,
            "traits": [
                Trait.new(id=ShapeID("smithy.api#xmlName"), value="K"),
                Trait.new(
                    id=ShapeID("smithy.api#xmlNamespace"),
                    value=MappingProxyType({"uri": "https://the-key.example.com"}),
                ),
            ],
        },
        "value": {
            "target": STRING,
            "traits": [
                Trait.new(id=ShapeID("smithy.api#xmlName"), value="V"),
                Trait.new(
                    id=ShapeID("smithy.api#xmlNamespace"),
                    value=MappingProxyType({"uri": "https://the-value.example.com"}),
                ),
            ],
        },
    },
)

FLATTENED_XML_MAP_WITH_XML_NAMESPACE_OUTPUT = Schema.collection(
    id=ShapeID("aws.protocoltests.query#FlattenedXmlMapWithXmlNamespaceOutput"),
    members={
        "myMap": {
            "target": FLATTENED_XML_MAP_WITH_XML_NAMESPACE_OUTPUT_MAP,
            "traits": [
                Trait.new(id=ShapeID("smithy.api#xmlName"), value="KVP"),
                Trait.new(id=ShapeID("smithy.api#xmlFlattened")),
                Trait.new(
                    id=ShapeID("smithy.api#xmlNamespace"),
                    value=MappingProxyType({"uri": "https://the-member.example.com"}),
                ),
            ],
        }
    },
)

FLATTENED_XML_MAP_WITH_XML_NAMESPACE = Schema(
    id=ShapeID("aws.protocoltests.query#FlattenedXmlMapWithXmlNamespace"),
    shape_type=ShapeType.OPERATION,
)

FRACTIONAL_SECONDS_INPUT = Schema.collection(
    id=ShapeID("aws.protocoltests.query#FractionalSecondsInput"),
    traits=[
        Trait.new(
            id=ShapeID("smithy.synthetic#originalShapeId"), value="smithy.api#Unit"
        )
    ],
)

FRACTIONAL_SECONDS_OUTPUT = Schema.collection(
    id=ShapeID("aws.protocoltests.query#FractionalSecondsOutput"),
    members={"datetime": {"target": DATE_TIME}},
)

FRACTIONAL_SECONDS = Schema(
    id=ShapeID("aws.protocoltests.query#FractionalSeconds"),
    shape_type=ShapeType.OPERATION,
)

COMPLEX_NESTED_ERROR_DATA = Schema.collection(
    id=ShapeID("aws.protocoltests.query#ComplexNestedErrorData"),
    members={"Foo": {"target": STRING}},
)

COMPLEX_ERROR = Schema.collection(
    id=ShapeID("aws.protocoltests.query#ComplexError"),
    traits=[Trait.new(id=ShapeID("smithy.api#error"), value="client")],
    members={
        "TopLevel": {"target": STRING},
        "Nested": {"target": COMPLEX_NESTED_ERROR_DATA},
    },
)

CUSTOM_CODE_ERROR = Schema.collection(
    id=ShapeID("aws.protocoltests.query#CustomCodeError"),
    traits=[
        Trait.new(id=ShapeID("smithy.api#error"), value="client"),
        Trait.new(
            id=ShapeID("aws.protocols#awsQueryError"),
            value=MappingProxyType({"code": "Customized", "httpResponseCode": 402}),
        ),
    ],
    members={"Message": {"target": STRING}},
)

GREETING_WITH_ERRORS_INPUT = Schema.collection(
    id=ShapeID("aws.protocoltests.query#GreetingWithErrorsInput"),
    traits=[
        Trait.new(
            id=ShapeID("smithy.synthetic#originalShapeId"), value="smithy.api#Unit"
        )
    ],
)

GREETING_WITH_ERRORS_OUTPUT = Schema.collection(
    id=ShapeID("aws.protocoltests.query#GreetingWithErrorsOutput"),
    members={"greeting": {"target": STRING}},
)

INVALID_GREETING = Schema.collection(
    id=ShapeID("aws.protocoltests.query#InvalidGreeting"),
    traits=[Trait.new(id=ShapeID("smithy.api#error"), value="client")],
    members={"Message": {"target": STRING}},
)

GREETING_WITH_ERRORS = Schema(
    id=ShapeID("aws.protocoltests.query#GreetingWithErrors"),
    shape_type=ShapeType.OPERATION,
)

HOST_WITH_PATH_OPERATION_INPUT = Schema.collection(
    id=ShapeID("aws.protocoltests.query#HostWithPathOperationInput"),
    traits=[
        Trait.new(
            id=ShapeID("smithy.synthetic#originalShapeId"), value="smithy.api#Unit"
        )
    ],
)

HOST_WITH_PATH_OPERATION_OUTPUT = Schema.collection(
    id=ShapeID("aws.protocoltests.query#HostWithPathOperationOutput"),
    traits=[
        Trait.new(
            id=ShapeID("smithy.synthetic#originalShapeId"), value="smithy.api#Unit"
        )
    ],
)

HOST_WITH_PATH_OPERATION = Schema(
    id=ShapeID("aws.protocoltests.query#HostWithPathOperation"),
    shape_type=ShapeType.OPERATION,
)

IGNORES_WRAPPING_XML_NAME_INPUT = Schema.collection(
    id=ShapeID("aws.protocoltests.query#IgnoresWrappingXmlNameInput"),
    traits=[
        Trait.new(
            id=ShapeID("smithy.synthetic#originalShapeId"), value="smithy.api#Unit"
        )
    ],
)

IGNORES_WRAPPING_XML_NAME_OUTPUT = Schema.collection(
    id=ShapeID("aws.protocoltests.query#IgnoresWrappingXmlNameOutput"),
    traits=[Trait.new(id=ShapeID("smithy.api#xmlName"), value="IgnoreMe")],
    members={"foo": {"target": STRING}},
)

IGNORES_WRAPPING_XML_NAME = Schema(
    id=ShapeID("aws.protocoltests.query#IgnoresWrappingXmlName"),
    shape_type=ShapeType.OPERATION,
)

NESTED_STRUCTURES_OUTPUT = Schema.collection(
    id=ShapeID("aws.protocoltests.query#NestedStructuresOutput"),
    traits=[
        Trait.new(
            id=ShapeID("smithy.synthetic#originalShapeId"), value="smithy.api#Unit"
        )
    ],
)

NO_INPUT_AND_NO_OUTPUT_INPUT = Schema.collection(
    id=ShapeID("aws.protocoltests.query#NoInputAndNoOutputInput"),
    traits=[
        Trait.new(
            id=ShapeID("smithy.synthetic#originalShapeId"), value="smithy.api#Unit"
        )
    ],
)

NO_INPUT_AND_NO_OUTPUT_OUTPUT = Schema.collection(
    id=ShapeID("aws.protocoltests.query#NoInputAndNoOutputOutput"),
    traits=[
        Trait.new(
            id=ShapeID("smithy.synthetic#originalShapeId"), value="smithy.api#Unit"
        )
    ],
)

NO_INPUT_AND_NO_OUTPUT = Schema(
    id=ShapeID("aws.protocoltests.query#NoInputAndNoOutput"),
    shape_type=ShapeType.OPERATION,
)

NO_INPUT_AND_OUTPUT_INPUT = Schema.collection(
    id=ShapeID("aws.protocoltests.query#NoInputAndOutputInput")
)

NO_INPUT_AND_OUTPUT_OUTPUT = Schema.collection(
    id=ShapeID("aws.protocoltests.query#NoInputAndOutputOutput")
)

NO_INPUT_AND_OUTPUT = Schema(
    id=ShapeID("aws.protocoltests.query#NoInputAndOutput"),
    shape_type=ShapeType.OPERATION,
)

PUT_WITH_CONTENT_ENCODING_INPUT = Schema.collection(
    id=ShapeID("aws.protocoltests.query#PutWithContentEncodingInput"),
    members={
        "encoding": {
            "target": STRING,
            "traits": [
                Trait.new(id=ShapeID("smithy.api#httpHeader"), value="Content-Encoding")
            ],
        },
        "data": {"target": STRING},
    },
)

PUT_WITH_CONTENT_ENCODING_OUTPUT = Schema.collection(
    id=ShapeID("aws.protocoltests.query#PutWithContentEncodingOutput"),
    traits=[
        Trait.new(
            id=ShapeID("smithy.synthetic#originalShapeId"), value="smithy.api#Unit"
        )
    ],
)

PUT_WITH_CONTENT_ENCODING = Schema(
    id=ShapeID("aws.protocoltests.query#PutWithContentEncoding"),
    shape_type=ShapeType.OPERATION,
    traits=[
        Trait.new(
            id=ShapeID("smithy.api#requestCompression"),
            value=MappingProxyType({"encodings": ("gzip",)}),
        )
    ],
)

QUERY_IDEMPOTENCY_TOKEN_AUTO_FILL_INPUT = Schema.collection(
    id=ShapeID("aws.protocoltests.query#QueryIdempotencyTokenAutoFillInput"),
    members={
        "token": {
            "target": STRING,
            "traits": [Trait.new(id=ShapeID("smithy.api#idempotencyToken"))],
        }
    },
)

QUERY_IDEMPOTENCY_TOKEN_AUTO_FILL_OUTPUT = Schema.collection(
    id=ShapeID("aws.protocoltests.query#QueryIdempotencyTokenAutoFillOutput"),
    traits=[
        Trait.new(
            id=ShapeID("smithy.synthetic#originalShapeId"), value="smithy.api#Unit"
        )
    ],
)

QUERY_IDEMPOTENCY_TOKEN_AUTO_FILL = Schema(
    id=ShapeID("aws.protocoltests.query#QueryIdempotencyTokenAutoFill"),
    shape_type=ShapeType.OPERATION,
)

GREETING_STRUCT = Schema.collection(
    id=ShapeID("aws.protocoltests.shared#GreetingStruct"),
    members={"hi": {"target": STRING}},
)

GREETING_LIST = Schema.collection(
    id=ShapeID("aws.protocoltests.shared#GreetingList"),
    shape_type=ShapeType.LIST,
    members={"member": {"target": GREETING_STRUCT}},
)

STRING_LIST = Schema.collection(
    id=ShapeID("aws.protocoltests.shared#StringList"),
    shape_type=ShapeType.LIST,
    members={"member": {"target": STRING}},
)

LIST_WITH_XML_NAME = Schema.collection(
    id=ShapeID("aws.protocoltests.query#ListWithXmlName"),
    shape_type=ShapeType.LIST,
    members={
        "member": {
            "target": STRING,
            "traits": [Trait.new(id=ShapeID("smithy.api#xmlName"), value="item")],
        }
    },
)

NESTED_STRUCT_WITH_LIST = Schema.collection(
    id=ShapeID("aws.protocoltests.query#NestedStructWithList"),
    members={"ListArg": {"target": STRING_LIST}},
)

QUERY_LISTS_INPUT = Schema.collection(
    id=ShapeID("aws.protocoltests.query#QueryListsInput"),
    members={
        "ListArg": {"target": STRING_LIST},
        "ComplexListArg": {"target": GREETING_LIST},
        "FlattenedListArg": {
            "target": STRING_LIST,
            "traits": [Trait.new(id=ShapeID("smithy.api#xmlFlattened"))],
        },
        "ListArgWithXmlNameMember": {"target": LIST_WITH_XML_NAME},
        "FlattenedListArgWithXmlName": {
            "target": LIST_WITH_XML_NAME,
            "traits": [
                Trait.new(id=ShapeID("smithy.api#xmlName"), value="Hi"),
                Trait.new(id=ShapeID("smithy.api#xmlFlattened")),
            ],
        },
        "NestedWithList": {"target": NESTED_STRUCT_WITH_LIST},
    },
)

QUERY_LISTS_OUTPUT = Schema.collection(
    id=ShapeID("aws.protocoltests.query#QueryListsOutput"),
    traits=[
        Trait.new(
            id=ShapeID("smithy.synthetic#originalShapeId"), value="smithy.api#Unit"
        )
    ],
)

QUERY_LISTS = Schema(
    id=ShapeID("aws.protocoltests.query#QueryLists"), shape_type=ShapeType.OPERATION
)

COMPLEX_MAP = Schema.collection(
    id=ShapeID("aws.protocoltests.query#ComplexMap"),
    shape_type=ShapeType.MAP,
    members={"key": {"target": STRING}, "value": {"target": GREETING_STRUCT}},
)

STRING_MAP = Schema.collection(
    id=ShapeID("aws.protocoltests.shared#StringMap"),
    shape_type=ShapeType.MAP,
    members={"key": {"target": STRING}, "value": {"target": STRING}},
)

MAP_WITH_XML_NAME = Schema.collection(
    id=ShapeID("aws.protocoltests.query#MapWithXmlName"),
    shape_type=ShapeType.MAP,
    members={
        "key": {
            "target": STRING,
            "traits": [Trait.new(id=ShapeID("smithy.api#xmlName"), value="K")],
        },
        "value": {
            "target": STRING,
            "traits": [Trait.new(id=ShapeID("smithy.api#xmlName"), value="V")],
        },
    },
)

MAP_OF_LISTS = Schema.collection(
    id=ShapeID("aws.protocoltests.query#MapOfLists"),
    shape_type=ShapeType.MAP,
    members={"key": {"target": STRING}, "value": {"target": STRING_LIST}},
)

NESTED_STRUCT_WITH_MAP = Schema.collection(
    id=ShapeID("aws.protocoltests.query#NestedStructWithMap"),
    members={"MapArg": {"target": STRING_MAP}},
)

QUERY_MAPS_INPUT = Schema.collection(
    id=ShapeID("aws.protocoltests.query#QueryMapsInput"),
    members={
        "MapArg": {"target": STRING_MAP},
        "RenamedMapArg": {
            "target": STRING_MAP,
            "traits": [Trait.new(id=ShapeID("smithy.api#xmlName"), value="Foo")],
        },
        "ComplexMapArg": {"target": COMPLEX_MAP},
        "MapWithXmlMemberName": {"target": MAP_WITH_XML_NAME},
        "FlattenedMap": {
            "target": STRING_MAP,
            "traits": [Trait.new(id=ShapeID("smithy.api#xmlFlattened"))],
        },
        "FlattenedMapWithXmlName": {
            "target": MAP_WITH_XML_NAME,
            "traits": [
                Trait.new(id=ShapeID("smithy.api#xmlName"), value="Hi"),
                Trait.new(id=ShapeID("smithy.api#xmlFlattened")),
            ],
        },
        "MapOfLists": {"target": MAP_OF_LISTS},
        "NestedStructWithMap": {"target": NESTED_STRUCT_WITH_MAP},
    },
)

QUERY_MAPS_OUTPUT = Schema.collection(
    id=ShapeID("aws.protocoltests.query#QueryMapsOutput"),
    traits=[
        Trait.new(
            id=ShapeID("smithy.synthetic#originalShapeId"), value="smithy.api#Unit"
        )
    ],
)

QUERY_MAPS = Schema(
    id=ShapeID("aws.protocoltests.query#QueryMaps"), shape_type=ShapeType.OPERATION
)

EPOCH_SECONDS = Schema(
    id=ShapeID("aws.protocoltests.shared#EpochSeconds"),
    shape_type=ShapeType.TIMESTAMP,
    traits=[Trait.new(id=ShapeID("smithy.api#timestampFormat"), value="epoch-seconds")],
)

QUERY_TIMESTAMPS_INPUT = Schema.collection(
    id=ShapeID("aws.protocoltests.query#QueryTimestampsInput"),
    members={
        "normalFormat": {"target": TIMESTAMP},
        "epochMember": {
            "target": TIMESTAMP,
            "traits": [
                Trait.new(
                    id=ShapeID("smithy.api#timestampFormat"), value="epoch-seconds"
                )
            ],
        },
        "epochTarget": {"target": EPOCH_SECONDS},
    },
)

QUERY_TIMESTAMPS_OUTPUT = Schema.collection(
    id=ShapeID("aws.protocoltests.query#QueryTimestampsOutput"),
    traits=[
        Trait.new(
            id=ShapeID("smithy.synthetic#originalShapeId"), value="smithy.api#Unit"
        )
    ],
)

QUERY_TIMESTAMPS = Schema(
    id=ShapeID("aws.protocoltests.query#QueryTimestamps"),
    shape_type=ShapeType.OPERATION,
)

RECURSIVE_XML_SHAPES_INPUT = Schema.collection(
    id=ShapeID("aws.protocoltests.query#RecursiveXmlShapesInput"),
    traits=[
        Trait.new(
            id=ShapeID("smithy.synthetic#originalShapeId"), value="smithy.api#Unit"
        )
    ],
)

INTEGER_ENUM = Schema.collection(
    id=ShapeID("aws.protocoltests.shared#IntegerEnum"),
    shape_type=ShapeType.INT_ENUM,
    members={"A": {"target": UNIT}, "B": {"target": UNIT}, "C": {"target": UNIT}},
)

SIMPLE_INPUT_PARAMS_INPUT = Schema.collection(
    id=ShapeID("aws.protocoltests.query#SimpleInputParamsInput"),
    members={
        "Foo": {"target": STRING},
        "Bar": {"target": STRING},
        "Baz": {"target": BOOLEAN},
        "Bam": {"target": INTEGER},
        "FloatValue": {"target": FLOAT},
        "Boo": {"target": DOUBLE},
        "Qux": {"target": BLOB},
        "FooEnum": {"target": FOO_ENUM},
        "IntegerEnum": {"target": INTEGER_ENUM},
    },
)

SIMPLE_INPUT_PARAMS_OUTPUT = Schema.collection(
    id=ShapeID("aws.protocoltests.query#SimpleInputParamsOutput"),
    traits=[
        Trait.new(
            id=ShapeID("smithy.synthetic#originalShapeId"), value="smithy.api#Unit"
        )
    ],
)

SIMPLE_INPUT_PARAMS = Schema(
    id=ShapeID("aws.protocoltests.query#SimpleInputParams"),
    shape_type=ShapeType.OPERATION,
)

SIMPLE_SCALAR_XML_PROPERTIES_INPUT = Schema.collection(
    id=ShapeID("aws.protocoltests.query#SimpleScalarXmlPropertiesInput"),
    traits=[
        Trait.new(
            id=ShapeID("smithy.synthetic#originalShapeId"), value="smithy.api#Unit"
        )
    ],
)

SIMPLE_SCALAR_XML_PROPERTIES_OUTPUT = Schema.collection(
    id=ShapeID("aws.protocoltests.query#SimpleScalarXmlPropertiesOutput"),
    members={
        "stringValue": {"target": STRING},
        "emptyStringValue": {"target": STRING},
        "trueBooleanValue": {"target": BOOLEAN},
        "falseBooleanValue": {"target": BOOLEAN},
        "byteValue": {"target": BYTE},
        "shortValue": {"target": SHORT},
        "integerValue": {"target": INTEGER},
        "longValue": {"target": LONG},
        "floatValue": {"target": FLOAT},
        "doubleValue": {
            "target": DOUBLE,
            "traits": [
                Trait.new(id=ShapeID("smithy.api#xmlName"), value="DoubleDribble")
            ],
        },
    },
)

SIMPLE_SCALAR_XML_PROPERTIES = Schema(
    id=ShapeID("aws.protocoltests.query#SimpleScalarXmlProperties"),
    shape_type=ShapeType.OPERATION,
)

XML_BLOBS_INPUT = Schema.collection(
    id=ShapeID("aws.protocoltests.query#XmlBlobsInput"),
    traits=[
        Trait.new(
            id=ShapeID("smithy.synthetic#originalShapeId"), value="smithy.api#Unit"
        )
    ],
)

XML_BLOBS_OPERATION_OUTPUT = Schema.collection(
    id=ShapeID("aws.protocoltests.query#XmlBlobsOperationOutput"),
    traits=[
        Trait.new(
            id=ShapeID("smithy.synthetic#originalShapeId"),
            value="aws.protocoltests.query#XmlBlobsOutput",
        )
    ],
    members={"data": {"target": BLOB}},
)

XML_BLOBS = Schema(
    id=ShapeID("aws.protocoltests.query#XmlBlobs"), shape_type=ShapeType.OPERATION
)

XML_EMPTY_BLOBS_INPUT = Schema.collection(
    id=ShapeID("aws.protocoltests.query#XmlEmptyBlobsInput"),
    traits=[
        Trait.new(
            id=ShapeID("smithy.synthetic#originalShapeId"), value="smithy.api#Unit"
        )
    ],
)

XML_EMPTY_BLOBS_OUTPUT = Schema.collection(
    id=ShapeID("aws.protocoltests.query#XmlEmptyBlobsOutput"),
    traits=[
        Trait.new(
            id=ShapeID("smithy.synthetic#originalShapeId"),
            value="aws.protocoltests.query#XmlBlobsOutput",
        )
    ],
    members={"data": {"target": BLOB}},
)

XML_EMPTY_BLOBS = Schema(
    id=ShapeID("aws.protocoltests.query#XmlEmptyBlobs"), shape_type=ShapeType.OPERATION
)

XML_EMPTY_LISTS_INPUT = Schema.collection(
    id=ShapeID("aws.protocoltests.query#XmlEmptyListsInput"),
    traits=[
        Trait.new(
            id=ShapeID("smithy.synthetic#originalShapeId"), value="smithy.api#Unit"
        )
    ],
)

BOOLEAN_LIST = Schema.collection(
    id=ShapeID("aws.protocoltests.shared#BooleanList"),
    shape_type=ShapeType.LIST,
    members={"member": {"target": BOOLEAN}},
)

FOO_ENUM_LIST = Schema.collection(
    id=ShapeID("aws.protocoltests.shared#FooEnumList"),
    shape_type=ShapeType.LIST,
    members={"member": {"target": FOO_ENUM}},
)

RENAMED_LIST_MEMBERS = Schema.collection(
    id=ShapeID("aws.protocoltests.query#RenamedListMembers"),
    shape_type=ShapeType.LIST,
    members={
        "member": {
            "target": STRING,
            "traits": [Trait.new(id=ShapeID("smithy.api#xmlName"), value="item")],
        }
    },
)

LIST_WITH_MEMBER_NAMESPACE = Schema.collection(
    id=ShapeID("aws.protocoltests.query#ListWithMemberNamespace"),
    shape_type=ShapeType.LIST,
    traits=[
        Trait.new(
            id=ShapeID("smithy.api#xmlNamespace"),
            value=MappingProxyType({"uri": "https://xml-list.example.com"}),
        )
    ],
    members={
        "member": {
            "target": STRING,
            "traits": [
                Trait.new(
                    id=ShapeID("smithy.api#xmlNamespace"),
                    value=MappingProxyType({"uri": "https://xml-member.example.com"}),
                )
            ],
        }
    },
)

LIST_WITH_NAMESPACE = Schema.collection(
    id=ShapeID("aws.protocoltests.query#ListWithNamespace"),
    shape_type=ShapeType.LIST,
    traits=[
        Trait.new(
            id=ShapeID("smithy.api#xmlNamespace"),
            value=MappingProxyType({"uri": "https://xml-list.example.com"}),
        )
    ],
    members={"member": {"target": STRING}},
)

INTEGER_LIST = Schema.collection(
    id=ShapeID("aws.protocoltests.shared#IntegerList"),
    shape_type=ShapeType.LIST,
    members={"member": {"target": INTEGER}},
)

INTEGER_ENUM_LIST = Schema.collection(
    id=ShapeID("aws.protocoltests.shared#IntegerEnumList"),
    shape_type=ShapeType.LIST,
    members={"member": {"target": INTEGER_ENUM}},
)

NESTED_STRING_LIST = Schema.collection(
    id=ShapeID("aws.protocoltests.shared#NestedStringList"),
    shape_type=ShapeType.LIST,
    members={"member": {"target": STRING_LIST}},
)

STRING_SET = Schema.collection(
    id=ShapeID("aws.protocoltests.shared#StringSet"),
    shape_type=ShapeType.LIST,
    members={"member": {"target": STRING}},
)

STRUCTURE_LIST_MEMBER = Schema.collection(
    id=ShapeID("aws.protocoltests.query#StructureListMember"),
    members={
        "a": {
            "target": STRING,
            "traits": [Trait.new(id=ShapeID("smithy.api#xmlName"), value="value")],
        },
        "b": {
            "target": STRING,
            "traits": [Trait.new(id=ShapeID("smithy.api#xmlName"), value="other")],
        },
    },
)

STRUCTURE_LIST = Schema.collection(
    id=ShapeID("aws.protocoltests.query#StructureList"),
    shape_type=ShapeType.LIST,
    members={
        "member": {
            "target": STRUCTURE_LIST_MEMBER,
            "traits": [Trait.new(id=ShapeID("smithy.api#xmlName"), value="item")],
        }
    },
)

TIMESTAMP_LIST = Schema.collection(
    id=ShapeID("aws.protocoltests.shared#TimestampList"),
    shape_type=ShapeType.LIST,
    members={"member": {"target": TIMESTAMP}},
)

XML_EMPTY_LISTS_OUTPUT = Schema.collection(
    id=ShapeID("aws.protocoltests.query#XmlEmptyListsOutput"),
    traits=[
        Trait.new(
            id=ShapeID("smithy.synthetic#originalShapeId"),
            value="aws.protocoltests.query#XmlListsOutput",
        )
    ],
    members={
        "stringList": {"target": STRING_LIST},
        "stringSet": {"target": STRING_SET},
        "integerList": {"target": INTEGER_LIST},
        "booleanList": {"target": BOOLEAN_LIST},
        "timestampList": {"target": TIMESTAMP_LIST},
        "enumList": {"target": FOO_ENUM_LIST},
        "intEnumList": {"target": INTEGER_ENUM_LIST},
        "nestedStringList": {"target": NESTED_STRING_LIST},
        "renamedListMembers": {
            "target": RENAMED_LIST_MEMBERS,
            "traits": [Trait.new(id=ShapeID("smithy.api#xmlName"), value="renamed")],
        },
        "flattenedList": {
            "target": RENAMED_LIST_MEMBERS,
            "traits": [Trait.new(id=ShapeID("smithy.api#xmlFlattened"))],
        },
        "flattenedList2": {
            "target": RENAMED_LIST_MEMBERS,
            "traits": [
                Trait.new(id=ShapeID("smithy.api#xmlName"), value="customName"),
                Trait.new(id=ShapeID("smithy.api#xmlFlattened")),
            ],
        },
        "flattenedListWithMemberNamespace": {
            "target": LIST_WITH_MEMBER_NAMESPACE,
            "traits": [Trait.new(id=ShapeID("smithy.api#xmlFlattened"))],
        },
        "flattenedListWithNamespace": {
            "target": LIST_WITH_NAMESPACE,
            "traits": [Trait.new(id=ShapeID("smithy.api#xmlFlattened"))],
        },
        "structureList": {
            "target": STRUCTURE_LIST,
            "traits": [
                Trait.new(id=ShapeID("smithy.api#xmlName"), value="myStructureList")
            ],
        },
    },
)

XML_EMPTY_LISTS = Schema(
    id=ShapeID("aws.protocoltests.query#XmlEmptyLists"), shape_type=ShapeType.OPERATION
)

XML_EMPTY_MAPS_INPUT = Schema.collection(
    id=ShapeID("aws.protocoltests.query#XmlEmptyMapsInput"),
    traits=[
        Trait.new(
            id=ShapeID("smithy.synthetic#originalShapeId"), value="smithy.api#Unit"
        )
    ],
)

XML_MAPS_OUTPUT_MAP = Schema.collection(
    id=ShapeID("aws.protocoltests.query#XmlMapsOutputMap"),
    shape_type=ShapeType.MAP,
    members={"key": {"target": STRING}, "value": {"target": GREETING_STRUCT}},
)

XML_EMPTY_MAPS_OUTPUT = Schema.collection(
    id=ShapeID("aws.protocoltests.query#XmlEmptyMapsOutput"),
    traits=[
        Trait.new(
            id=ShapeID("smithy.synthetic#originalShapeId"),
            value="aws.protocoltests.query#XmlMapsOutput",
        )
    ],
    members={"myMap": {"target": XML_MAPS_OUTPUT_MAP}},
)

XML_EMPTY_MAPS = Schema(
    id=ShapeID("aws.protocoltests.query#XmlEmptyMaps"), shape_type=ShapeType.OPERATION
)

XML_ENUMS_INPUT = Schema.collection(
    id=ShapeID("aws.protocoltests.query#XmlEnumsInput"),
    traits=[
        Trait.new(
            id=ShapeID("smithy.synthetic#originalShapeId"), value="smithy.api#Unit"
        )
    ],
)

FOO_ENUM_SET = Schema.collection(
    id=ShapeID("aws.protocoltests.shared#FooEnumSet"),
    shape_type=ShapeType.LIST,
    members={"member": {"target": FOO_ENUM}},
)

XML_ENUMS_OUTPUT = Schema.collection(
    id=ShapeID("aws.protocoltests.query#XmlEnumsOutput"),
    members={
        "fooEnum1": {"target": FOO_ENUM},
        "fooEnum2": {"target": FOO_ENUM},
        "fooEnum3": {"target": FOO_ENUM},
        "fooEnumList": {"target": FOO_ENUM_LIST},
        "fooEnumSet": {"target": FOO_ENUM_SET},
        "fooEnumMap": {"target": FOO_ENUM_MAP},
    },
)

XML_ENUMS = Schema(
    id=ShapeID("aws.protocoltests.query#XmlEnums"), shape_type=ShapeType.OPERATION
)

XML_INT_ENUMS_INPUT = Schema.collection(
    id=ShapeID("aws.protocoltests.query#XmlIntEnumsInput"),
    traits=[
        Trait.new(
            id=ShapeID("smithy.synthetic#originalShapeId"), value="smithy.api#Unit"
        )
    ],
)

INTEGER_ENUM_MAP = Schema.collection(
    id=ShapeID("aws.protocoltests.shared#IntegerEnumMap"),
    shape_type=ShapeType.MAP,
    members={"key": {"target": STRING}, "value": {"target": INTEGER_ENUM}},
)

INTEGER_ENUM_SET = Schema.collection(
    id=ShapeID("aws.protocoltests.shared#IntegerEnumSet"),
    shape_type=ShapeType.LIST,
    members={"member": {"target": INTEGER_ENUM}},
)

XML_INT_ENUMS_OUTPUT = Schema.collection(
    id=ShapeID("aws.protocoltests.query#XmlIntEnumsOutput"),
    members={
        "intEnum1": {"target": INTEGER_ENUM},
        "intEnum2": {"target": INTEGER_ENUM},
        "intEnum3": {"target": INTEGER_ENUM},
        "intEnumList": {"target": INTEGER_ENUM_LIST},
        "intEnumSet": {"target": INTEGER_ENUM_SET},
        "intEnumMap": {"target": INTEGER_ENUM_MAP},
    },
)

XML_INT_ENUMS = Schema(
    id=ShapeID("aws.protocoltests.query#XmlIntEnums"), shape_type=ShapeType.OPERATION
)

XML_LISTS_INPUT = Schema.collection(
    id=ShapeID("aws.protocoltests.query#XmlListsInput"),
    traits=[
        Trait.new(
            id=ShapeID("smithy.synthetic#originalShapeId"), value="smithy.api#Unit"
        )
    ],
)

XML_LISTS_OPERATION_OUTPUT = Schema.collection(
    id=ShapeID("aws.protocoltests.query#XmlListsOperationOutput"),
    traits=[
        Trait.new(
            id=ShapeID("smithy.synthetic#originalShapeId"),
            value="aws.protocoltests.query#XmlListsOutput",
        )
    ],
    members={
        "stringList": {"target": STRING_LIST},
        "stringSet": {"target": STRING_SET},
        "integerList": {"target": INTEGER_LIST},
        "booleanList": {"target": BOOLEAN_LIST},
        "timestampList": {"target": TIMESTAMP_LIST},
        "enumList": {"target": FOO_ENUM_LIST},
        "intEnumList": {"target": INTEGER_ENUM_LIST},
        "nestedStringList": {"target": NESTED_STRING_LIST},
        "renamedListMembers": {
            "target": RENAMED_LIST_MEMBERS,
            "traits": [Trait.new(id=ShapeID("smithy.api#xmlName"), value="renamed")],
        },
        "flattenedList": {
            "target": RENAMED_LIST_MEMBERS,
            "traits": [Trait.new(id=ShapeID("smithy.api#xmlFlattened"))],
        },
        "flattenedList2": {
            "target": RENAMED_LIST_MEMBERS,
            "traits": [
                Trait.new(id=ShapeID("smithy.api#xmlName"), value="customName"),
                Trait.new(id=ShapeID("smithy.api#xmlFlattened")),
            ],
        },
        "flattenedListWithMemberNamespace": {
            "target": LIST_WITH_MEMBER_NAMESPACE,
            "traits": [Trait.new(id=ShapeID("smithy.api#xmlFlattened"))],
        },
        "flattenedListWithNamespace": {
            "target": LIST_WITH_NAMESPACE,
            "traits": [Trait.new(id=ShapeID("smithy.api#xmlFlattened"))],
        },
        "structureList": {
            "target": STRUCTURE_LIST,
            "traits": [
                Trait.new(id=ShapeID("smithy.api#xmlName"), value="myStructureList")
            ],
        },
    },
)

XML_LISTS = Schema(
    id=ShapeID("aws.protocoltests.query#XmlLists"), shape_type=ShapeType.OPERATION
)

XML_MAPS_INPUT = Schema.collection(
    id=ShapeID("aws.protocoltests.query#XmlMapsInput"),
    traits=[
        Trait.new(
            id=ShapeID("smithy.synthetic#originalShapeId"), value="smithy.api#Unit"
        )
    ],
)

XML_MAPS_OPERATION_OUTPUT = Schema.collection(
    id=ShapeID("aws.protocoltests.query#XmlMapsOperationOutput"),
    traits=[
        Trait.new(
            id=ShapeID("smithy.synthetic#originalShapeId"),
            value="aws.protocoltests.query#XmlMapsOutput",
        )
    ],
    members={"myMap": {"target": XML_MAPS_OUTPUT_MAP}},
)

XML_MAPS = Schema(
    id=ShapeID("aws.protocoltests.query#XmlMaps"), shape_type=ShapeType.OPERATION
)

XML_MAPS_XML_NAME_INPUT = Schema.collection(
    id=ShapeID("aws.protocoltests.query#XmlMapsXmlNameInput"),
    traits=[
        Trait.new(
            id=ShapeID("smithy.synthetic#originalShapeId"), value="smithy.api#Unit"
        )
    ],
)

XML_MAPS_XML_NAME_OUTPUT_MAP = Schema.collection(
    id=ShapeID("aws.protocoltests.query#XmlMapsXmlNameOutputMap"),
    shape_type=ShapeType.MAP,
    members={
        "key": {
            "target": STRING,
            "traits": [Trait.new(id=ShapeID("smithy.api#xmlName"), value="Attribute")],
        },
        "value": {
            "target": GREETING_STRUCT,
            "traits": [Trait.new(id=ShapeID("smithy.api#xmlName"), value="Setting")],
        },
    },
)

XML_MAPS_XML_NAME_OUTPUT = Schema.collection(
    id=ShapeID("aws.protocoltests.query#XmlMapsXmlNameOutput"),
    members={"myMap": {"target": XML_MAPS_XML_NAME_OUTPUT_MAP}},
)

XML_MAPS_XML_NAME = Schema(
    id=ShapeID("aws.protocoltests.query#XmlMapsXmlName"), shape_type=ShapeType.OPERATION
)

XML_NAMESPACES_INPUT = Schema.collection(
    id=ShapeID("aws.protocoltests.query#XmlNamespacesInput"),
    traits=[
        Trait.new(
            id=ShapeID("smithy.synthetic#originalShapeId"), value="smithy.api#Unit"
        )
    ],
)

XML_NAMESPACED_LIST = Schema.collection(
    id=ShapeID("aws.protocoltests.query#XmlNamespacedList"),
    shape_type=ShapeType.LIST,
    members={
        "member": {
            "target": STRING,
            "traits": [
                Trait.new(
                    id=ShapeID("smithy.api#xmlNamespace"),
                    value=MappingProxyType({"uri": "http://bux.com"}),
                )
            ],
        }
    },
)

XML_NAMESPACE_NESTED = Schema.collection(
    id=ShapeID("aws.protocoltests.query#XmlNamespaceNested"),
    traits=[
        Trait.new(
            id=ShapeID("smithy.api#xmlNamespace"),
            value=MappingProxyType({"uri": "http://boo.com"}),
        )
    ],
    members={
        "foo": {
            "target": STRING,
            "traits": [
                Trait.new(
                    id=ShapeID("smithy.api#xmlNamespace"),
                    value=MappingProxyType({"uri": "http://baz.com", "prefix": "baz"}),
                )
            ],
        },
        "values": {
            "target": XML_NAMESPACED_LIST,
            "traits": [
                Trait.new(
                    id=ShapeID("smithy.api#xmlNamespace"),
                    value=MappingProxyType({"uri": "http://qux.com"}),
                )
            ],
        },
    },
)

XML_NAMESPACES_OUTPUT = Schema.collection(
    id=ShapeID("aws.protocoltests.query#XmlNamespacesOutput"),
    traits=[
        Trait.new(
            id=ShapeID("smithy.api#xmlNamespace"),
            value=MappingProxyType({"uri": "http://foo.com"}),
        )
    ],
    members={"nested": {"target": XML_NAMESPACE_NESTED}},
)

XML_NAMESPACES = Schema(
    id=ShapeID("aws.protocoltests.query#XmlNamespaces"), shape_type=ShapeType.OPERATION
)

XML_TIMESTAMPS_INPUT = Schema.collection(
    id=ShapeID("aws.protocoltests.query#XmlTimestampsInput"),
    traits=[
        Trait.new(
            id=ShapeID("smithy.synthetic#originalShapeId"), value="smithy.api#Unit"
        )
    ],
)

HTTP_DATE = Schema(
    id=ShapeID("aws.protocoltests.shared#HttpDate"),
    shape_type=ShapeType.TIMESTAMP,
    traits=[Trait.new(id=ShapeID("smithy.api#timestampFormat"), value="http-date")],
)

XML_TIMESTAMPS_OUTPUT = Schema.collection(
    id=ShapeID("aws.protocoltests.query#XmlTimestampsOutput"),
    members={
        "normal": {"target": TIMESTAMP},
        "dateTime": {
            "target": TIMESTAMP,
            "traits": [
                Trait.new(id=ShapeID("smithy.api#timestampFormat"), value="date-time")
            ],
        },
        "dateTimeOnTarget": {"target": DATE_TIME},
        "epochSeconds": {
            "target": TIMESTAMP,
            "traits": [
                Trait.new(
                    id=ShapeID("smithy.api#timestampFormat"), value="epoch-seconds"
                )
            ],
        },
        "epochSecondsOnTarget": {"target": EPOCH_SECONDS},
        "httpDate": {
            "target": TIMESTAMP,
            "traits": [
                Trait.new(id=ShapeID("smithy.api#timestampFormat"), value="http-date")
            ],
        },
        "httpDateOnTarget": {"target": HTTP_DATE},
    },
)

XML_TIMESTAMPS = Schema(
    id=ShapeID("aws.protocoltests.query#XmlTimestamps"), shape_type=ShapeType.OPERATION
)

STRUCT_ARG = Schema.collection(
    id=ShapeID("aws.protocoltests.query#StructArg"),
    members={
        "StringArg": {"target": STRING},
        "OtherArg": {"target": BOOLEAN},
        # This needs to reference a schema that isn't defined yet.
        # It will be populated with a non-null value at the end of the file.
        "RecursiveArg": None,
    },
)

NESTED_STRUCTURES_INPUT = Schema.collection(
    id=ShapeID("aws.protocoltests.query#NestedStructuresInput"),
    members={"Nested": {"target": STRUCT_ARG}},
)

RECURSIVE_XML_SHAPES_OUTPUT_NESTED1 = Schema.collection(
    id=ShapeID("aws.protocoltests.query#RecursiveXmlShapesOutputNested1"),
    members={
        "foo": {"target": STRING},
        # This needs to reference a schema that isn't defined yet.
        # It will be populated with a non-null value at the end of the file.
        "nested": None,
    },
)

RECURSIVE_XML_SHAPES_OUTPUT_NESTED2 = Schema.collection(
    id=ShapeID("aws.protocoltests.query#RecursiveXmlShapesOutputNested2"),
    members={
        "bar": {"target": STRING},
        "recursiveMember": {"target": RECURSIVE_XML_SHAPES_OUTPUT_NESTED1},
    },
)

NESTED_STRUCTURES = Schema(
    id=ShapeID("aws.protocoltests.query#NestedStructures"),
    shape_type=ShapeType.OPERATION,
)

RECURSIVE_XML_SHAPES_OUTPUT = Schema.collection(
    id=ShapeID("aws.protocoltests.query#RecursiveXmlShapesOutput"),
    members={"nested": {"target": RECURSIVE_XML_SHAPES_OUTPUT_NESTED1}},
)

RECURSIVE_XML_SHAPES = Schema(
    id=ShapeID("aws.protocoltests.query#RecursiveXmlShapes"),
    shape_type=ShapeType.OPERATION,
)

AWS_QUERY = Schema(
    id=ShapeID("aws.protocoltests.query#AwsQuery"),
    shape_type=ShapeType.SERVICE,
    traits=[
        Trait.new(
            id=ShapeID("smithy.api#xmlNamespace"),
            value=MappingProxyType({"uri": "https://example.com/"}),
        )
    ],
)

RECURSIVE_XML_SHAPES_OUTPUT_NESTED1.members["nested"] = Schema.member(
    id=RECURSIVE_XML_SHAPES_OUTPUT_NESTED1.id.with_member("nested"),
    target=RECURSIVE_XML_SHAPES_OUTPUT_NESTED2,
    index=1,
)

STRUCT_ARG.members["RecursiveArg"] = Schema.member(
    id=STRUCT_ARG.id.with_member("RecursiveArg"), target=STRUCT_ARG, index=2
)
