# Code generated by smithy-python-codegen DO NOT EDIT.

from dataclasses import dataclass, field
import logging
from typing import Any, Self

from smithy_core.deserializers import ShapeDeserializer
from smithy_core.documents import TypeRegistry
from smithy_core.exceptions import ModeledError
from smithy_core.response import EMPTY_RESPONSE_METADATA, ResponseMetadata
from smithy_core.schemas import APIOperation, Schema
from smithy_core.serializers import ShapeSerializer
from smithy_core.shapes import ShapeID

from ._private.schemas import (
    NESTED_WITH_NAMESPACE as _SCHEMA_NESTED_WITH_NAMESPACE,
    SIMPLE_SCALAR_PROPERTIES as _SCHEMA_SIMPLE_SCALAR_PROPERTIES,
    SIMPLE_SCALAR_PROPERTIES_INPUT as _SCHEMA_SIMPLE_SCALAR_PROPERTIES_INPUT,
    SIMPLE_SCALAR_PROPERTIES_OUTPUT as _SCHEMA_SIMPLE_SCALAR_PROPERTIES_OUTPUT,
)


logger = logging.getLogger(__name__)


class ServiceError(ModeledError):
    """
    Base error for all errors in the service.

    Some exceptions do not extend from this class, including
    synthetic, implicit, and shared exception types.
    """


@dataclass(kw_only=True)
class NestedWithNamespace:
    """Dataclass for NestedWithNamespace structure."""

    attr_field: str | None = None

    def serialize(self, serializer: ShapeSerializer):
        serializer.write_struct(_SCHEMA_NESTED_WITH_NAMESPACE, self)

    def serialize_members(self, serializer: ShapeSerializer):
        if self.attr_field is not None:
            serializer.write_string(
                _SCHEMA_NESTED_WITH_NAMESPACE.members["attrField"], self.attr_field
            )

    @classmethod
    def deserialize(cls, deserializer: ShapeDeserializer) -> Self:
        return cls(**cls.deserialize_kwargs(deserializer))

    @classmethod
    def deserialize_kwargs(cls, deserializer: ShapeDeserializer) -> dict[str, Any]:
        kwargs: dict[str, Any] = {}

        def _consumer(schema: Schema, de: ShapeDeserializer) -> None:
            match schema.expect_member_index():
                case 0:
                    kwargs["attr_field"] = de.read_string(
                        _SCHEMA_NESTED_WITH_NAMESPACE.members["attrField"]
                    )

                case _:
                    logger.debug("Unexpected member schema: %s", schema)

        deserializer.read_struct(_SCHEMA_NESTED_WITH_NAMESPACE, consumer=_consumer)
        return kwargs


@dataclass(kw_only=True)
class SimpleScalarPropertiesInput:
    """Dataclass for SimpleScalarPropertiesInput structure."""

    foo: str | None = None

    string_value: str | None = None

    true_boolean_value: bool | None = None

    false_boolean_value: bool | None = None

    byte_value: int | None = None

    short_value: int | None = None

    integer_value: int | None = None

    long_value: int | None = None

    float_value: float | None = None

    nested: NestedWithNamespace | None = None

    double_value: float | None = None

    def serialize(self, serializer: ShapeSerializer):
        serializer.write_struct(_SCHEMA_SIMPLE_SCALAR_PROPERTIES_INPUT, self)

    def serialize_members(self, serializer: ShapeSerializer):
        if self.foo is not None:
            serializer.write_string(
                _SCHEMA_SIMPLE_SCALAR_PROPERTIES_INPUT.members["foo"], self.foo
            )

        if self.string_value is not None:
            serializer.write_string(
                _SCHEMA_SIMPLE_SCALAR_PROPERTIES_INPUT.members["stringValue"],
                self.string_value,
            )

        if self.true_boolean_value is not None:
            serializer.write_boolean(
                _SCHEMA_SIMPLE_SCALAR_PROPERTIES_INPUT.members["trueBooleanValue"],
                self.true_boolean_value,
            )

        if self.false_boolean_value is not None:
            serializer.write_boolean(
                _SCHEMA_SIMPLE_SCALAR_PROPERTIES_INPUT.members["falseBooleanValue"],
                self.false_boolean_value,
            )

        if self.byte_value is not None:
            serializer.write_byte(
                _SCHEMA_SIMPLE_SCALAR_PROPERTIES_INPUT.members["byteValue"],
                self.byte_value,
            )

        if self.short_value is not None:
            serializer.write_short(
                _SCHEMA_SIMPLE_SCALAR_PROPERTIES_INPUT.members["shortValue"],
                self.short_value,
            )

        if self.integer_value is not None:
            serializer.write_integer(
                _SCHEMA_SIMPLE_SCALAR_PROPERTIES_INPUT.members["integerValue"],
                self.integer_value,
            )

        if self.long_value is not None:
            serializer.write_long(
                _SCHEMA_SIMPLE_SCALAR_PROPERTIES_INPUT.members["longValue"],
                self.long_value,
            )

        if self.float_value is not None:
            serializer.write_float(
                _SCHEMA_SIMPLE_SCALAR_PROPERTIES_INPUT.members["floatValue"],
                self.float_value,
            )

        if self.nested is not None:
            serializer.write_struct(
                _SCHEMA_SIMPLE_SCALAR_PROPERTIES_INPUT.members["Nested"], self.nested
            )

        if self.double_value is not None:
            serializer.write_double(
                _SCHEMA_SIMPLE_SCALAR_PROPERTIES_INPUT.members["doubleValue"],
                self.double_value,
            )

    @classmethod
    def deserialize(cls, deserializer: ShapeDeserializer) -> Self:
        return cls(**cls.deserialize_kwargs(deserializer))

    @classmethod
    def deserialize_kwargs(cls, deserializer: ShapeDeserializer) -> dict[str, Any]:
        kwargs: dict[str, Any] = {}

        def _consumer(schema: Schema, de: ShapeDeserializer) -> None:
            match schema.expect_member_index():
                case 0:
                    kwargs["foo"] = de.read_string(
                        _SCHEMA_SIMPLE_SCALAR_PROPERTIES_INPUT.members["foo"]
                    )

                case 1:
                    kwargs["string_value"] = de.read_string(
                        _SCHEMA_SIMPLE_SCALAR_PROPERTIES_INPUT.members["stringValue"]
                    )

                case 2:
                    kwargs["true_boolean_value"] = de.read_boolean(
                        _SCHEMA_SIMPLE_SCALAR_PROPERTIES_INPUT.members[
                            "trueBooleanValue"
                        ]
                    )

                case 3:
                    kwargs["false_boolean_value"] = de.read_boolean(
                        _SCHEMA_SIMPLE_SCALAR_PROPERTIES_INPUT.members[
                            "falseBooleanValue"
                        ]
                    )

                case 4:
                    kwargs["byte_value"] = de.read_byte(
                        _SCHEMA_SIMPLE_SCALAR_PROPERTIES_INPUT.members["byteValue"]
                    )

                case 5:
                    kwargs["short_value"] = de.read_short(
                        _SCHEMA_SIMPLE_SCALAR_PROPERTIES_INPUT.members["shortValue"]
                    )

                case 6:
                    kwargs["integer_value"] = de.read_integer(
                        _SCHEMA_SIMPLE_SCALAR_PROPERTIES_INPUT.members["integerValue"]
                    )

                case 7:
                    kwargs["long_value"] = de.read_long(
                        _SCHEMA_SIMPLE_SCALAR_PROPERTIES_INPUT.members["longValue"]
                    )

                case 8:
                    kwargs["float_value"] = de.read_float(
                        _SCHEMA_SIMPLE_SCALAR_PROPERTIES_INPUT.members["floatValue"]
                    )

                case 9:
                    kwargs["nested"] = NestedWithNamespace.deserialize(de)

                case 10:
                    kwargs["double_value"] = de.read_double(
                        _SCHEMA_SIMPLE_SCALAR_PROPERTIES_INPUT.members["doubleValue"]
                    )

                case _:
                    logger.debug("Unexpected member schema: %s", schema)

        deserializer.read_struct(
            _SCHEMA_SIMPLE_SCALAR_PROPERTIES_INPUT, consumer=_consumer
        )
        return kwargs


@dataclass(kw_only=True)
class SimpleScalarPropertiesOutput:
    """Dataclass for SimpleScalarPropertiesOutput structure."""

    foo: str | None = None

    string_value: str | None = None

    true_boolean_value: bool | None = None

    false_boolean_value: bool | None = None

    byte_value: int | None = None

    short_value: int | None = None

    integer_value: int | None = None

    long_value: int | None = None

    float_value: float | None = None

    nested: NestedWithNamespace | None = None

    double_value: float | None = None

    response_metadata: ResponseMetadata = field(
        default=EMPTY_RESPONSE_METADATA, repr=False, compare=False
    )
    """
    Metadata about the response that produced this output. Use this to
    recover the request identifiers a service's support team needs in order
    to investigate a call. Members of the metadata are individually
    optional.
    """

    def serialize(self, serializer: ShapeSerializer):
        serializer.write_struct(_SCHEMA_SIMPLE_SCALAR_PROPERTIES_OUTPUT, self)

    def serialize_members(self, serializer: ShapeSerializer):
        if self.foo is not None:
            serializer.write_string(
                _SCHEMA_SIMPLE_SCALAR_PROPERTIES_OUTPUT.members["foo"], self.foo
            )

        if self.string_value is not None:
            serializer.write_string(
                _SCHEMA_SIMPLE_SCALAR_PROPERTIES_OUTPUT.members["stringValue"],
                self.string_value,
            )

        if self.true_boolean_value is not None:
            serializer.write_boolean(
                _SCHEMA_SIMPLE_SCALAR_PROPERTIES_OUTPUT.members["trueBooleanValue"],
                self.true_boolean_value,
            )

        if self.false_boolean_value is not None:
            serializer.write_boolean(
                _SCHEMA_SIMPLE_SCALAR_PROPERTIES_OUTPUT.members["falseBooleanValue"],
                self.false_boolean_value,
            )

        if self.byte_value is not None:
            serializer.write_byte(
                _SCHEMA_SIMPLE_SCALAR_PROPERTIES_OUTPUT.members["byteValue"],
                self.byte_value,
            )

        if self.short_value is not None:
            serializer.write_short(
                _SCHEMA_SIMPLE_SCALAR_PROPERTIES_OUTPUT.members["shortValue"],
                self.short_value,
            )

        if self.integer_value is not None:
            serializer.write_integer(
                _SCHEMA_SIMPLE_SCALAR_PROPERTIES_OUTPUT.members["integerValue"],
                self.integer_value,
            )

        if self.long_value is not None:
            serializer.write_long(
                _SCHEMA_SIMPLE_SCALAR_PROPERTIES_OUTPUT.members["longValue"],
                self.long_value,
            )

        if self.float_value is not None:
            serializer.write_float(
                _SCHEMA_SIMPLE_SCALAR_PROPERTIES_OUTPUT.members["floatValue"],
                self.float_value,
            )

        if self.nested is not None:
            serializer.write_struct(
                _SCHEMA_SIMPLE_SCALAR_PROPERTIES_OUTPUT.members["Nested"], self.nested
            )

        if self.double_value is not None:
            serializer.write_double(
                _SCHEMA_SIMPLE_SCALAR_PROPERTIES_OUTPUT.members["doubleValue"],
                self.double_value,
            )

    @classmethod
    def deserialize(cls, deserializer: ShapeDeserializer) -> Self:
        return cls(**cls.deserialize_kwargs(deserializer))

    @classmethod
    def deserialize_kwargs(cls, deserializer: ShapeDeserializer) -> dict[str, Any]:
        kwargs: dict[str, Any] = {}

        def _consumer(schema: Schema, de: ShapeDeserializer) -> None:
            match schema.expect_member_index():
                case 0:
                    kwargs["foo"] = de.read_string(
                        _SCHEMA_SIMPLE_SCALAR_PROPERTIES_OUTPUT.members["foo"]
                    )

                case 1:
                    kwargs["string_value"] = de.read_string(
                        _SCHEMA_SIMPLE_SCALAR_PROPERTIES_OUTPUT.members["stringValue"]
                    )

                case 2:
                    kwargs["true_boolean_value"] = de.read_boolean(
                        _SCHEMA_SIMPLE_SCALAR_PROPERTIES_OUTPUT.members[
                            "trueBooleanValue"
                        ]
                    )

                case 3:
                    kwargs["false_boolean_value"] = de.read_boolean(
                        _SCHEMA_SIMPLE_SCALAR_PROPERTIES_OUTPUT.members[
                            "falseBooleanValue"
                        ]
                    )

                case 4:
                    kwargs["byte_value"] = de.read_byte(
                        _SCHEMA_SIMPLE_SCALAR_PROPERTIES_OUTPUT.members["byteValue"]
                    )

                case 5:
                    kwargs["short_value"] = de.read_short(
                        _SCHEMA_SIMPLE_SCALAR_PROPERTIES_OUTPUT.members["shortValue"]
                    )

                case 6:
                    kwargs["integer_value"] = de.read_integer(
                        _SCHEMA_SIMPLE_SCALAR_PROPERTIES_OUTPUT.members["integerValue"]
                    )

                case 7:
                    kwargs["long_value"] = de.read_long(
                        _SCHEMA_SIMPLE_SCALAR_PROPERTIES_OUTPUT.members["longValue"]
                    )

                case 8:
                    kwargs["float_value"] = de.read_float(
                        _SCHEMA_SIMPLE_SCALAR_PROPERTIES_OUTPUT.members["floatValue"]
                    )

                case 9:
                    kwargs["nested"] = NestedWithNamespace.deserialize(de)

                case 10:
                    kwargs["double_value"] = de.read_double(
                        _SCHEMA_SIMPLE_SCALAR_PROPERTIES_OUTPUT.members["doubleValue"]
                    )

                case _:
                    logger.debug("Unexpected member schema: %s", schema)

        deserializer.read_struct(
            _SCHEMA_SIMPLE_SCALAR_PROPERTIES_OUTPUT, consumer=_consumer
        )
        return kwargs


SIMPLE_SCALAR_PROPERTIES = APIOperation(
    input=SimpleScalarPropertiesInput,
    output=SimpleScalarPropertiesOutput,
    schema=_SCHEMA_SIMPLE_SCALAR_PROPERTIES,
    input_schema=_SCHEMA_SIMPLE_SCALAR_PROPERTIES_INPUT,
    output_schema=_SCHEMA_SIMPLE_SCALAR_PROPERTIES_OUTPUT,
    error_registry=TypeRegistry({}),
    effective_auth_schemes=[ShapeID("aws.auth#sigv4")],
    error_schemas=[],
)
