# Code generated by smithy-python-codegen DO NOT EDIT.

import asyncio
from copy import deepcopy as _deepcopy
from datetime import datetime
import logging
from typing import Any, Self, cast

from smithy_aws_core.config import ConfigSource
from smithy_aws_core.identity import AWSCredentialsIdentity
from smithy_aws_core.identity.chain import IdentityChain
from smithy_core.aio.client import ClientCall, RequestPipeline
from smithy_core.aio.retries import RetryStrategyResolver
from smithy_core.aio.utils import close
from smithy_core.exceptions import ExpectationNotMetError
from smithy_core.interceptors import InterceptorChain
from smithy_core.types import TypedProperties
from smithy_http.aio.interfaces import HTTPClient
from smithy_http.plugins import user_agent_plugin as _user_agent_plugin

from .config import AsyncQueryProtocolConfig, Plugin
from .models import (
    DATETIME_OFFSETS,
    DatetimeOffsetsInput,
    DatetimeOffsetsOutput,
    EMPTY_INPUT_AND_EMPTY_OUTPUT,
    ENDPOINT_OPERATION,
    ENDPOINT_WITH_HOST_LABEL_OPERATION,
    EmptyInputAndEmptyOutputInput,
    EmptyInputAndEmptyOutputOutput,
    EndpointOperationInput,
    EndpointOperationOutput,
    EndpointWithHostLabelOperationInput,
    EndpointWithHostLabelOperationOutput,
    FLATTENED_XML_MAP,
    FLATTENED_XML_MAP_WITH_XML_NAME,
    FLATTENED_XML_MAP_WITH_XML_NAMESPACE,
    FRACTIONAL_SECONDS,
    FlattenedXmlMapInput,
    FlattenedXmlMapOutput,
    FlattenedXmlMapWithXmlNameInput,
    FlattenedXmlMapWithXmlNameOutput,
    FlattenedXmlMapWithXmlNamespaceInput,
    FlattenedXmlMapWithXmlNamespaceOutput,
    FractionalSecondsInput,
    FractionalSecondsOutput,
    GREETING_WITH_ERRORS,
    GreetingStruct,
    GreetingWithErrorsInput,
    GreetingWithErrorsOutput,
    HOST_WITH_PATH_OPERATION,
    HostWithPathOperationInput,
    HostWithPathOperationOutput,
    IGNORES_WRAPPING_XML_NAME,
    IgnoresWrappingXmlNameInput,
    IgnoresWrappingXmlNameOutput,
    NESTED_STRUCTURES,
    NO_INPUT_AND_NO_OUTPUT,
    NO_INPUT_AND_OUTPUT,
    NestedStructWithList,
    NestedStructWithMap,
    NestedStructuresInput,
    NestedStructuresOutput,
    NoInputAndNoOutputInput,
    NoInputAndNoOutputOutput,
    NoInputAndOutputInput,
    NoInputAndOutputOutput,
    PUT_WITH_CONTENT_ENCODING,
    PutWithContentEncodingInput,
    PutWithContentEncodingOutput,
    QUERY_IDEMPOTENCY_TOKEN_AUTO_FILL,
    QUERY_LISTS,
    QUERY_MAPS,
    QUERY_TIMESTAMPS,
    QueryIdempotencyTokenAutoFillInput,
    QueryIdempotencyTokenAutoFillOutput,
    QueryListsInput,
    QueryListsOutput,
    QueryMapsInput,
    QueryMapsOutput,
    QueryTimestampsInput,
    QueryTimestampsOutput,
    RECURSIVE_XML_SHAPES,
    RecursiveXmlShapesInput,
    RecursiveXmlShapesOutput,
    SIMPLE_INPUT_PARAMS,
    SIMPLE_SCALAR_XML_PROPERTIES,
    SimpleInputParamsInput,
    SimpleInputParamsOutput,
    SimpleScalarXmlPropertiesInput,
    SimpleScalarXmlPropertiesOutput,
    StructArg,
    XML_BLOBS,
    XML_EMPTY_BLOBS,
    XML_EMPTY_LISTS,
    XML_EMPTY_MAPS,
    XML_ENUMS,
    XML_INT_ENUMS,
    XML_LISTS,
    XML_MAPS,
    XML_MAPS_XML_NAME,
    XML_NAMESPACES,
    XML_TIMESTAMPS,
    XmlBlobsInput,
    XmlBlobsOperationOutput,
    XmlEmptyBlobsInput,
    XmlEmptyBlobsOutput,
    XmlEmptyListsInput,
    XmlEmptyListsOutput,
    XmlEmptyMapsInput,
    XmlEmptyMapsOutput,
    XmlEnumsInput,
    XmlEnumsOutput,
    XmlIntEnumsInput,
    XmlIntEnumsOutput,
    XmlListsInput,
    XmlListsOperationOutput,
    XmlMapsInput,
    XmlMapsOperationOutput,
    XmlMapsXmlNameInput,
    XmlMapsXmlNameOutput,
    XmlNamespacesInput,
    XmlNamespacesOutput,
    XmlTimestampsInput,
    XmlTimestampsOutput,
)
from .user_agent import aws_user_agent_plugin as _aws_user_agent_plugin


logger = logging.getLogger(__name__)


class AsyncQueryProtocolClient:
    """A query service that sends query requests and XML responses."""

    def __init__(
        self,
        config: AsyncQueryProtocolConfig | None = None,
        plugins: list[Plugin] | None = None,
    ):
        """
        Constructor for `AsyncQueryProtocolClient`.

        Args:
            config:
                Optional configuration for the client. Here you can set things like
                the endpoint for HTTP services or auth credentials.
            plugins:
                A list of callables applied once to the client's base configuration.
                Their changes are inherited by every operation invocation.
        """
        self._config = config
        self._plugins = plugins
        self._derive_lock = asyncio.Lock()
        self._setup_done = False
        self._closed = False
        self._retry_strategy_resolver = RetryStrategyResolver()
        self._client_plugins: list[Plugin] = [
            _aws_user_agent_plugin,
            _user_agent_plugin,
        ]

    async def _ensure_setup(self) -> None:
        if not self._setup_done:
            async with self._derive_lock:
                if not self._setup_done:
                    if self._config is None:
                        config = await AsyncQueryProtocolConfig.resolve()
                    else:
                        # Copy so plugins don't mutate the caller's config.
                        config = _deepcopy(self._config)
                    for plugin in self._client_plugins:
                        plugin(config)
                    if self._plugins:
                        for plugin in self._plugins:
                            plugin(config)
                    self._config = config

                    if self._config.aws_credentials_identity_resolver is None:
                        config_context = self._config.resolution_context()
                        config_file = None
                        profile_name = None
                        if config_context is not None:
                            config_file = await config_context.parsed_profiles()
                            if config_context.profile_source is ConfigSource.OVERRIDE:
                                profile_name = config_context.profile_name
                        self._config.aws_credentials_identity_resolver = (
                            await IdentityChain.create(
                                AWSCredentialsIdentity,
                                config_file=config_file,
                                profile_name=profile_name,
                                region_override=self._config.region,
                                http_client=cast(
                                    HTTPClient | None, self._config.transport
                                ),
                            )
                        )
                    self._setup_done = True

    async def close(self) -> None:
        """Close this client and any resources held by its transport."""
        if self._closed:
            return
        async with self._derive_lock:
            if self._closed:
                return
            self._closed = True
            if self._setup_done and self._config is not None:
                await close(self._config.transport)

    async def __aenter__(self) -> Self:
        if self._closed:
            raise RuntimeError("Cannot enter a client that has been closed.")
        return self

    async def __aexit__(self, exc_type: Any, exc_value: Any, traceback: Any) -> None:
        await self.close()

    async def datetime_offsets(
        self, *, plugins: list[Plugin] | None = None
    ) -> DatetimeOffsetsOutput:
        """
        Invokes the DatetimeOffsets operation.

        Args:
            plugins:
                A list of callables that modify the configuration dynamically.
                Changes made by these plugins only apply for the duration of the
                operation execution and will not affect any other operation
                invocations.

        Returns:
            An instance of `DatetimeOffsetsOutput`.
        """
        if self._closed:
            raise RuntimeError(
                "Cannot invoke an operation on a client that has been closed."
            )

        _input = DatetimeOffsetsInput()
        _operation_plugins: list[Plugin] = []
        if plugins:
            _operation_plugins.extend(plugins)
        await self._ensure_setup()
        assert self._config is not None
        if _operation_plugins:
            # Keep operation-plugin mutations scoped to this call.
            _config = _deepcopy(self._config)
            for _plugin in _operation_plugins:
                _plugin(_config)
        else:
            _config = self._config
        if (
            _config.protocol is None
            or _config.transport is None
            or _config.endpoint_resolver is None
            or _config.auth_scheme_resolver is None
            or _config.auth_schemes is None
        ):
            raise ExpectationNotMetError(
                "protocol, transport, endpoint_resolver, auth_scheme_resolver,"
                " and auth_schemes MUST be set on the config to make calls."
            )

        _retry_strategy = await self._retry_strategy_resolver.resolve_retry_strategy(
            retry_strategy=_config.retry_strategy,
            retry_mode=_config.retry_mode,
            max_attempts=_config.max_attempts,
        )

        _pipeline = RequestPipeline(
            protocol=_config.protocol, transport=_config.transport
        )
        _call = ClientCall(
            input=_input,
            operation=DATETIME_OFFSETS,
            context=TypedProperties({"config": _config}),
            interceptor=InterceptorChain(_config.interceptors),
            auth_scheme_resolver=_config.auth_scheme_resolver,
            supported_auth_schemes=_config.auth_schemes,
            endpoint_resolver=_config.endpoint_resolver,
            retry_strategy=_retry_strategy,
        )

        return await _pipeline(_call)

    async def empty_input_and_empty_output(
        self, *, plugins: list[Plugin] | None = None
    ) -> EmptyInputAndEmptyOutputOutput:
        """
        The example tests how requests and responses are serialized when
        there's no request or response members. While this should be rare, code
        generators must support this.

        Args:
            plugins:
                A list of callables that modify the configuration dynamically.
                Changes made by these plugins only apply for the duration of the
                operation execution and will not affect any other operation
                invocations.

        Returns:
            An instance of `EmptyInputAndEmptyOutputOutput`.
        """
        if self._closed:
            raise RuntimeError(
                "Cannot invoke an operation on a client that has been closed."
            )

        _input = EmptyInputAndEmptyOutputInput()
        _operation_plugins: list[Plugin] = []
        if plugins:
            _operation_plugins.extend(plugins)
        await self._ensure_setup()
        assert self._config is not None
        if _operation_plugins:
            # Keep operation-plugin mutations scoped to this call.
            _config = _deepcopy(self._config)
            for _plugin in _operation_plugins:
                _plugin(_config)
        else:
            _config = self._config
        if (
            _config.protocol is None
            or _config.transport is None
            or _config.endpoint_resolver is None
            or _config.auth_scheme_resolver is None
            or _config.auth_schemes is None
        ):
            raise ExpectationNotMetError(
                "protocol, transport, endpoint_resolver, auth_scheme_resolver,"
                " and auth_schemes MUST be set on the config to make calls."
            )

        _retry_strategy = await self._retry_strategy_resolver.resolve_retry_strategy(
            retry_strategy=_config.retry_strategy,
            retry_mode=_config.retry_mode,
            max_attempts=_config.max_attempts,
        )

        _pipeline = RequestPipeline(
            protocol=_config.protocol, transport=_config.transport
        )
        _call = ClientCall(
            input=_input,
            operation=EMPTY_INPUT_AND_EMPTY_OUTPUT,
            context=TypedProperties({"config": _config}),
            interceptor=InterceptorChain(_config.interceptors),
            auth_scheme_resolver=_config.auth_scheme_resolver,
            supported_auth_schemes=_config.auth_schemes,
            endpoint_resolver=_config.endpoint_resolver,
            retry_strategy=_retry_strategy,
        )

        return await _pipeline(_call)

    async def endpoint_operation(
        self, *, plugins: list[Plugin] | None = None
    ) -> EndpointOperationOutput:
        """
        Invokes the EndpointOperation operation.

        Args:
            plugins:
                A list of callables that modify the configuration dynamically.
                Changes made by these plugins only apply for the duration of the
                operation execution and will not affect any other operation
                invocations.

        Returns:
            An instance of `EndpointOperationOutput`.
        """
        if self._closed:
            raise RuntimeError(
                "Cannot invoke an operation on a client that has been closed."
            )

        _input = EndpointOperationInput()
        _operation_plugins: list[Plugin] = []
        if plugins:
            _operation_plugins.extend(plugins)
        await self._ensure_setup()
        assert self._config is not None
        if _operation_plugins:
            # Keep operation-plugin mutations scoped to this call.
            _config = _deepcopy(self._config)
            for _plugin in _operation_plugins:
                _plugin(_config)
        else:
            _config = self._config
        if (
            _config.protocol is None
            or _config.transport is None
            or _config.endpoint_resolver is None
            or _config.auth_scheme_resolver is None
            or _config.auth_schemes is None
        ):
            raise ExpectationNotMetError(
                "protocol, transport, endpoint_resolver, auth_scheme_resolver,"
                " and auth_schemes MUST be set on the config to make calls."
            )

        _retry_strategy = await self._retry_strategy_resolver.resolve_retry_strategy(
            retry_strategy=_config.retry_strategy,
            retry_mode=_config.retry_mode,
            max_attempts=_config.max_attempts,
        )

        _pipeline = RequestPipeline(
            protocol=_config.protocol, transport=_config.transport
        )
        _call = ClientCall(
            input=_input,
            operation=ENDPOINT_OPERATION,
            context=TypedProperties({"config": _config}),
            interceptor=InterceptorChain(_config.interceptors),
            auth_scheme_resolver=_config.auth_scheme_resolver,
            supported_auth_schemes=_config.auth_schemes,
            endpoint_resolver=_config.endpoint_resolver,
            retry_strategy=_retry_strategy,
        )

        return await _pipeline(_call)

    async def endpoint_with_host_label_operation(
        self, *, label: str | None = None, plugins: list[Plugin] | None = None
    ) -> EndpointWithHostLabelOperationOutput:
        """
        Invokes the EndpointWithHostLabelOperation operation.

        Args:
            plugins:
                A list of callables that modify the configuration dynamically.
                Changes made by these plugins only apply for the duration of the
                operation execution and will not affect any other operation
                invocations.

        Returns:
            An instance of `EndpointWithHostLabelOperationOutput`.
        """
        if self._closed:
            raise RuntimeError(
                "Cannot invoke an operation on a client that has been closed."
            )

        _input = EndpointWithHostLabelOperationInput(label=label)
        _operation_plugins: list[Plugin] = []
        if plugins:
            _operation_plugins.extend(plugins)
        await self._ensure_setup()
        assert self._config is not None
        if _operation_plugins:
            # Keep operation-plugin mutations scoped to this call.
            _config = _deepcopy(self._config)
            for _plugin in _operation_plugins:
                _plugin(_config)
        else:
            _config = self._config
        if (
            _config.protocol is None
            or _config.transport is None
            or _config.endpoint_resolver is None
            or _config.auth_scheme_resolver is None
            or _config.auth_schemes is None
        ):
            raise ExpectationNotMetError(
                "protocol, transport, endpoint_resolver, auth_scheme_resolver,"
                " and auth_schemes MUST be set on the config to make calls."
            )

        _retry_strategy = await self._retry_strategy_resolver.resolve_retry_strategy(
            retry_strategy=_config.retry_strategy,
            retry_mode=_config.retry_mode,
            max_attempts=_config.max_attempts,
        )

        _pipeline = RequestPipeline(
            protocol=_config.protocol, transport=_config.transport
        )
        _call = ClientCall(
            input=_input,
            operation=ENDPOINT_WITH_HOST_LABEL_OPERATION,
            context=TypedProperties({"config": _config}),
            interceptor=InterceptorChain(_config.interceptors),
            auth_scheme_resolver=_config.auth_scheme_resolver,
            supported_auth_schemes=_config.auth_schemes,
            endpoint_resolver=_config.endpoint_resolver,
            retry_strategy=_retry_strategy,
        )

        return await _pipeline(_call)

    async def flattened_xml_map(
        self, *, plugins: list[Plugin] | None = None
    ) -> FlattenedXmlMapOutput:
        """
        Flattened maps

        Args:
            plugins:
                A list of callables that modify the configuration dynamically.
                Changes made by these plugins only apply for the duration of the
                operation execution and will not affect any other operation
                invocations.

        Returns:
            An instance of `FlattenedXmlMapOutput`.
        """
        if self._closed:
            raise RuntimeError(
                "Cannot invoke an operation on a client that has been closed."
            )

        _input = FlattenedXmlMapInput()
        _operation_plugins: list[Plugin] = []
        if plugins:
            _operation_plugins.extend(plugins)
        await self._ensure_setup()
        assert self._config is not None
        if _operation_plugins:
            # Keep operation-plugin mutations scoped to this call.
            _config = _deepcopy(self._config)
            for _plugin in _operation_plugins:
                _plugin(_config)
        else:
            _config = self._config
        if (
            _config.protocol is None
            or _config.transport is None
            or _config.endpoint_resolver is None
            or _config.auth_scheme_resolver is None
            or _config.auth_schemes is None
        ):
            raise ExpectationNotMetError(
                "protocol, transport, endpoint_resolver, auth_scheme_resolver,"
                " and auth_schemes MUST be set on the config to make calls."
            )

        _retry_strategy = await self._retry_strategy_resolver.resolve_retry_strategy(
            retry_strategy=_config.retry_strategy,
            retry_mode=_config.retry_mode,
            max_attempts=_config.max_attempts,
        )

        _pipeline = RequestPipeline(
            protocol=_config.protocol, transport=_config.transport
        )
        _call = ClientCall(
            input=_input,
            operation=FLATTENED_XML_MAP,
            context=TypedProperties({"config": _config}),
            interceptor=InterceptorChain(_config.interceptors),
            auth_scheme_resolver=_config.auth_scheme_resolver,
            supported_auth_schemes=_config.auth_schemes,
            endpoint_resolver=_config.endpoint_resolver,
            retry_strategy=_retry_strategy,
        )

        return await _pipeline(_call)

    async def flattened_xml_map_with_xml_name(
        self, *, plugins: list[Plugin] | None = None
    ) -> FlattenedXmlMapWithXmlNameOutput:
        """
        Flattened maps with @xmlName

        Args:
            plugins:
                A list of callables that modify the configuration dynamically.
                Changes made by these plugins only apply for the duration of the
                operation execution and will not affect any other operation
                invocations.

        Returns:
            An instance of `FlattenedXmlMapWithXmlNameOutput`.
        """
        if self._closed:
            raise RuntimeError(
                "Cannot invoke an operation on a client that has been closed."
            )

        _input = FlattenedXmlMapWithXmlNameInput()
        _operation_plugins: list[Plugin] = []
        if plugins:
            _operation_plugins.extend(plugins)
        await self._ensure_setup()
        assert self._config is not None
        if _operation_plugins:
            # Keep operation-plugin mutations scoped to this call.
            _config = _deepcopy(self._config)
            for _plugin in _operation_plugins:
                _plugin(_config)
        else:
            _config = self._config
        if (
            _config.protocol is None
            or _config.transport is None
            or _config.endpoint_resolver is None
            or _config.auth_scheme_resolver is None
            or _config.auth_schemes is None
        ):
            raise ExpectationNotMetError(
                "protocol, transport, endpoint_resolver, auth_scheme_resolver,"
                " and auth_schemes MUST be set on the config to make calls."
            )

        _retry_strategy = await self._retry_strategy_resolver.resolve_retry_strategy(
            retry_strategy=_config.retry_strategy,
            retry_mode=_config.retry_mode,
            max_attempts=_config.max_attempts,
        )

        _pipeline = RequestPipeline(
            protocol=_config.protocol, transport=_config.transport
        )
        _call = ClientCall(
            input=_input,
            operation=FLATTENED_XML_MAP_WITH_XML_NAME,
            context=TypedProperties({"config": _config}),
            interceptor=InterceptorChain(_config.interceptors),
            auth_scheme_resolver=_config.auth_scheme_resolver,
            supported_auth_schemes=_config.auth_schemes,
            endpoint_resolver=_config.endpoint_resolver,
            retry_strategy=_retry_strategy,
        )

        return await _pipeline(_call)

    async def flattened_xml_map_with_xml_namespace(
        self, *, plugins: list[Plugin] | None = None
    ) -> FlattenedXmlMapWithXmlNamespaceOutput:
        """
        Flattened maps with @xmlNamespace and @xmlName

        Args:
            plugins:
                A list of callables that modify the configuration dynamically.
                Changes made by these plugins only apply for the duration of the
                operation execution and will not affect any other operation
                invocations.

        Returns:
            An instance of `FlattenedXmlMapWithXmlNamespaceOutput`.
        """
        if self._closed:
            raise RuntimeError(
                "Cannot invoke an operation on a client that has been closed."
            )

        _input = FlattenedXmlMapWithXmlNamespaceInput()
        _operation_plugins: list[Plugin] = []
        if plugins:
            _operation_plugins.extend(plugins)
        await self._ensure_setup()
        assert self._config is not None
        if _operation_plugins:
            # Keep operation-plugin mutations scoped to this call.
            _config = _deepcopy(self._config)
            for _plugin in _operation_plugins:
                _plugin(_config)
        else:
            _config = self._config
        if (
            _config.protocol is None
            or _config.transport is None
            or _config.endpoint_resolver is None
            or _config.auth_scheme_resolver is None
            or _config.auth_schemes is None
        ):
            raise ExpectationNotMetError(
                "protocol, transport, endpoint_resolver, auth_scheme_resolver,"
                " and auth_schemes MUST be set on the config to make calls."
            )

        _retry_strategy = await self._retry_strategy_resolver.resolve_retry_strategy(
            retry_strategy=_config.retry_strategy,
            retry_mode=_config.retry_mode,
            max_attempts=_config.max_attempts,
        )

        _pipeline = RequestPipeline(
            protocol=_config.protocol, transport=_config.transport
        )
        _call = ClientCall(
            input=_input,
            operation=FLATTENED_XML_MAP_WITH_XML_NAMESPACE,
            context=TypedProperties({"config": _config}),
            interceptor=InterceptorChain(_config.interceptors),
            auth_scheme_resolver=_config.auth_scheme_resolver,
            supported_auth_schemes=_config.auth_schemes,
            endpoint_resolver=_config.endpoint_resolver,
            retry_strategy=_retry_strategy,
        )

        return await _pipeline(_call)

    async def fractional_seconds(
        self, *, plugins: list[Plugin] | None = None
    ) -> FractionalSecondsOutput:
        """
        Invokes the FractionalSeconds operation.

        Args:
            plugins:
                A list of callables that modify the configuration dynamically.
                Changes made by these plugins only apply for the duration of the
                operation execution and will not affect any other operation
                invocations.

        Returns:
            An instance of `FractionalSecondsOutput`.
        """
        if self._closed:
            raise RuntimeError(
                "Cannot invoke an operation on a client that has been closed."
            )

        _input = FractionalSecondsInput()
        _operation_plugins: list[Plugin] = []
        if plugins:
            _operation_plugins.extend(plugins)
        await self._ensure_setup()
        assert self._config is not None
        if _operation_plugins:
            # Keep operation-plugin mutations scoped to this call.
            _config = _deepcopy(self._config)
            for _plugin in _operation_plugins:
                _plugin(_config)
        else:
            _config = self._config
        if (
            _config.protocol is None
            or _config.transport is None
            or _config.endpoint_resolver is None
            or _config.auth_scheme_resolver is None
            or _config.auth_schemes is None
        ):
            raise ExpectationNotMetError(
                "protocol, transport, endpoint_resolver, auth_scheme_resolver,"
                " and auth_schemes MUST be set on the config to make calls."
            )

        _retry_strategy = await self._retry_strategy_resolver.resolve_retry_strategy(
            retry_strategy=_config.retry_strategy,
            retry_mode=_config.retry_mode,
            max_attempts=_config.max_attempts,
        )

        _pipeline = RequestPipeline(
            protocol=_config.protocol, transport=_config.transport
        )
        _call = ClientCall(
            input=_input,
            operation=FRACTIONAL_SECONDS,
            context=TypedProperties({"config": _config}),
            interceptor=InterceptorChain(_config.interceptors),
            auth_scheme_resolver=_config.auth_scheme_resolver,
            supported_auth_schemes=_config.auth_schemes,
            endpoint_resolver=_config.endpoint_resolver,
            retry_strategy=_retry_strategy,
        )

        return await _pipeline(_call)

    async def greeting_with_errors(
        self, *, plugins: list[Plugin] | None = None
    ) -> GreetingWithErrorsOutput:
        """
        This operation has three possible return values: 1. A successful
        response in the form of GreetingWithErrorsOutput 2. An InvalidGreeting
        error. 3. A BadRequest error.

        Args:
            plugins:
                A list of callables that modify the configuration dynamically.
                Changes made by these plugins only apply for the duration of the
                operation execution and will not affect any other operation
                invocations.

        Returns:
            An instance of `GreetingWithErrorsOutput`.
        """
        if self._closed:
            raise RuntimeError(
                "Cannot invoke an operation on a client that has been closed."
            )

        _input = GreetingWithErrorsInput()
        _operation_plugins: list[Plugin] = []
        if plugins:
            _operation_plugins.extend(plugins)
        await self._ensure_setup()
        assert self._config is not None
        if _operation_plugins:
            # Keep operation-plugin mutations scoped to this call.
            _config = _deepcopy(self._config)
            for _plugin in _operation_plugins:
                _plugin(_config)
        else:
            _config = self._config
        if (
            _config.protocol is None
            or _config.transport is None
            or _config.endpoint_resolver is None
            or _config.auth_scheme_resolver is None
            or _config.auth_schemes is None
        ):
            raise ExpectationNotMetError(
                "protocol, transport, endpoint_resolver, auth_scheme_resolver,"
                " and auth_schemes MUST be set on the config to make calls."
            )

        _retry_strategy = await self._retry_strategy_resolver.resolve_retry_strategy(
            retry_strategy=_config.retry_strategy,
            retry_mode=_config.retry_mode,
            max_attempts=_config.max_attempts,
        )

        _pipeline = RequestPipeline(
            protocol=_config.protocol, transport=_config.transport
        )
        _call = ClientCall(
            input=_input,
            operation=GREETING_WITH_ERRORS,
            context=TypedProperties({"config": _config}),
            interceptor=InterceptorChain(_config.interceptors),
            auth_scheme_resolver=_config.auth_scheme_resolver,
            supported_auth_schemes=_config.auth_schemes,
            endpoint_resolver=_config.endpoint_resolver,
            retry_strategy=_retry_strategy,
        )

        return await _pipeline(_call)

    async def host_with_path_operation(
        self, *, plugins: list[Plugin] | None = None
    ) -> HostWithPathOperationOutput:
        """
        Invokes the HostWithPathOperation operation.

        Args:
            plugins:
                A list of callables that modify the configuration dynamically.
                Changes made by these plugins only apply for the duration of the
                operation execution and will not affect any other operation
                invocations.

        Returns:
            An instance of `HostWithPathOperationOutput`.
        """
        if self._closed:
            raise RuntimeError(
                "Cannot invoke an operation on a client that has been closed."
            )

        _input = HostWithPathOperationInput()
        _operation_plugins: list[Plugin] = []
        if plugins:
            _operation_plugins.extend(plugins)
        await self._ensure_setup()
        assert self._config is not None
        if _operation_plugins:
            # Keep operation-plugin mutations scoped to this call.
            _config = _deepcopy(self._config)
            for _plugin in _operation_plugins:
                _plugin(_config)
        else:
            _config = self._config
        if (
            _config.protocol is None
            or _config.transport is None
            or _config.endpoint_resolver is None
            or _config.auth_scheme_resolver is None
            or _config.auth_schemes is None
        ):
            raise ExpectationNotMetError(
                "protocol, transport, endpoint_resolver, auth_scheme_resolver,"
                " and auth_schemes MUST be set on the config to make calls."
            )

        _retry_strategy = await self._retry_strategy_resolver.resolve_retry_strategy(
            retry_strategy=_config.retry_strategy,
            retry_mode=_config.retry_mode,
            max_attempts=_config.max_attempts,
        )

        _pipeline = RequestPipeline(
            protocol=_config.protocol, transport=_config.transport
        )
        _call = ClientCall(
            input=_input,
            operation=HOST_WITH_PATH_OPERATION,
            context=TypedProperties({"config": _config}),
            interceptor=InterceptorChain(_config.interceptors),
            auth_scheme_resolver=_config.auth_scheme_resolver,
            supported_auth_schemes=_config.auth_schemes,
            endpoint_resolver=_config.endpoint_resolver,
            retry_strategy=_retry_strategy,
        )

        return await _pipeline(_call)

    async def ignores_wrapping_xml_name(
        self, *, plugins: list[Plugin] | None = None
    ) -> IgnoresWrappingXmlNameOutput:
        """
        The xmlName trait on the output structure is ignored in AWS Query. The
        wrapping element is always operation name + \"Response\", and inside of
        that wrapper is another wrapper named operation name + \"Result\".

        Args:
            plugins:
                A list of callables that modify the configuration dynamically.
                Changes made by these plugins only apply for the duration of the
                operation execution and will not affect any other operation
                invocations.

        Returns:
            An instance of `IgnoresWrappingXmlNameOutput`.
        """
        if self._closed:
            raise RuntimeError(
                "Cannot invoke an operation on a client that has been closed."
            )

        _input = IgnoresWrappingXmlNameInput()
        _operation_plugins: list[Plugin] = []
        if plugins:
            _operation_plugins.extend(plugins)
        await self._ensure_setup()
        assert self._config is not None
        if _operation_plugins:
            # Keep operation-plugin mutations scoped to this call.
            _config = _deepcopy(self._config)
            for _plugin in _operation_plugins:
                _plugin(_config)
        else:
            _config = self._config
        if (
            _config.protocol is None
            or _config.transport is None
            or _config.endpoint_resolver is None
            or _config.auth_scheme_resolver is None
            or _config.auth_schemes is None
        ):
            raise ExpectationNotMetError(
                "protocol, transport, endpoint_resolver, auth_scheme_resolver,"
                " and auth_schemes MUST be set on the config to make calls."
            )

        _retry_strategy = await self._retry_strategy_resolver.resolve_retry_strategy(
            retry_strategy=_config.retry_strategy,
            retry_mode=_config.retry_mode,
            max_attempts=_config.max_attempts,
        )

        _pipeline = RequestPipeline(
            protocol=_config.protocol, transport=_config.transport
        )
        _call = ClientCall(
            input=_input,
            operation=IGNORES_WRAPPING_XML_NAME,
            context=TypedProperties({"config": _config}),
            interceptor=InterceptorChain(_config.interceptors),
            auth_scheme_resolver=_config.auth_scheme_resolver,
            supported_auth_schemes=_config.auth_schemes,
            endpoint_resolver=_config.endpoint_resolver,
            retry_strategy=_retry_strategy,
        )

        return await _pipeline(_call)

    async def nested_structures(
        self, *, nested: StructArg | None = None, plugins: list[Plugin] | None = None
    ) -> NestedStructuresOutput:
        """
        This test serializes nested and recursive structure members.

        Args:
            plugins:
                A list of callables that modify the configuration dynamically.
                Changes made by these plugins only apply for the duration of the
                operation execution and will not affect any other operation
                invocations.

        Returns:
            An instance of `NestedStructuresOutput`.
        """
        if self._closed:
            raise RuntimeError(
                "Cannot invoke an operation on a client that has been closed."
            )

        _input = NestedStructuresInput(nested=nested)
        _operation_plugins: list[Plugin] = []
        if plugins:
            _operation_plugins.extend(plugins)
        await self._ensure_setup()
        assert self._config is not None
        if _operation_plugins:
            # Keep operation-plugin mutations scoped to this call.
            _config = _deepcopy(self._config)
            for _plugin in _operation_plugins:
                _plugin(_config)
        else:
            _config = self._config
        if (
            _config.protocol is None
            or _config.transport is None
            or _config.endpoint_resolver is None
            or _config.auth_scheme_resolver is None
            or _config.auth_schemes is None
        ):
            raise ExpectationNotMetError(
                "protocol, transport, endpoint_resolver, auth_scheme_resolver,"
                " and auth_schemes MUST be set on the config to make calls."
            )

        _retry_strategy = await self._retry_strategy_resolver.resolve_retry_strategy(
            retry_strategy=_config.retry_strategy,
            retry_mode=_config.retry_mode,
            max_attempts=_config.max_attempts,
        )

        _pipeline = RequestPipeline(
            protocol=_config.protocol, transport=_config.transport
        )
        _call = ClientCall(
            input=_input,
            operation=NESTED_STRUCTURES,
            context=TypedProperties({"config": _config}),
            interceptor=InterceptorChain(_config.interceptors),
            auth_scheme_resolver=_config.auth_scheme_resolver,
            supported_auth_schemes=_config.auth_schemes,
            endpoint_resolver=_config.endpoint_resolver,
            retry_strategy=_retry_strategy,
        )

        return await _pipeline(_call)

    async def no_input_and_no_output(
        self, *, plugins: list[Plugin] | None = None
    ) -> NoInputAndNoOutputOutput:
        """
        The example tests how requests and responses are serialized when
        there's no request or response payload because the operation has no
        input or output. While this should be rare, code generators must support
        this.

        Args:
            plugins:
                A list of callables that modify the configuration dynamically.
                Changes made by these plugins only apply for the duration of the
                operation execution and will not affect any other operation
                invocations.

        Returns:
            An instance of `NoInputAndNoOutputOutput`.
        """
        if self._closed:
            raise RuntimeError(
                "Cannot invoke an operation on a client that has been closed."
            )

        _input = NoInputAndNoOutputInput()
        _operation_plugins: list[Plugin] = []
        if plugins:
            _operation_plugins.extend(plugins)
        await self._ensure_setup()
        assert self._config is not None
        if _operation_plugins:
            # Keep operation-plugin mutations scoped to this call.
            _config = _deepcopy(self._config)
            for _plugin in _operation_plugins:
                _plugin(_config)
        else:
            _config = self._config
        if (
            _config.protocol is None
            or _config.transport is None
            or _config.endpoint_resolver is None
            or _config.auth_scheme_resolver is None
            or _config.auth_schemes is None
        ):
            raise ExpectationNotMetError(
                "protocol, transport, endpoint_resolver, auth_scheme_resolver,"
                " and auth_schemes MUST be set on the config to make calls."
            )

        _retry_strategy = await self._retry_strategy_resolver.resolve_retry_strategy(
            retry_strategy=_config.retry_strategy,
            retry_mode=_config.retry_mode,
            max_attempts=_config.max_attempts,
        )

        _pipeline = RequestPipeline(
            protocol=_config.protocol, transport=_config.transport
        )
        _call = ClientCall(
            input=_input,
            operation=NO_INPUT_AND_NO_OUTPUT,
            context=TypedProperties({"config": _config}),
            interceptor=InterceptorChain(_config.interceptors),
            auth_scheme_resolver=_config.auth_scheme_resolver,
            supported_auth_schemes=_config.auth_schemes,
            endpoint_resolver=_config.endpoint_resolver,
            retry_strategy=_retry_strategy,
        )

        return await _pipeline(_call)

    async def no_input_and_output(
        self, *, plugins: list[Plugin] | None = None
    ) -> NoInputAndOutputOutput:
        """
        The example tests how requests and responses are serialized when
        there's no request payload or response members. While this should be
        rare, code generators must support this.

        Args:
            plugins:
                A list of callables that modify the configuration dynamically.
                Changes made by these plugins only apply for the duration of the
                operation execution and will not affect any other operation
                invocations.

        Returns:
            An instance of `NoInputAndOutputOutput`.
        """
        if self._closed:
            raise RuntimeError(
                "Cannot invoke an operation on a client that has been closed."
            )

        _input = NoInputAndOutputInput()
        _operation_plugins: list[Plugin] = []
        if plugins:
            _operation_plugins.extend(plugins)
        await self._ensure_setup()
        assert self._config is not None
        if _operation_plugins:
            # Keep operation-plugin mutations scoped to this call.
            _config = _deepcopy(self._config)
            for _plugin in _operation_plugins:
                _plugin(_config)
        else:
            _config = self._config
        if (
            _config.protocol is None
            or _config.transport is None
            or _config.endpoint_resolver is None
            or _config.auth_scheme_resolver is None
            or _config.auth_schemes is None
        ):
            raise ExpectationNotMetError(
                "protocol, transport, endpoint_resolver, auth_scheme_resolver,"
                " and auth_schemes MUST be set on the config to make calls."
            )

        _retry_strategy = await self._retry_strategy_resolver.resolve_retry_strategy(
            retry_strategy=_config.retry_strategy,
            retry_mode=_config.retry_mode,
            max_attempts=_config.max_attempts,
        )

        _pipeline = RequestPipeline(
            protocol=_config.protocol, transport=_config.transport
        )
        _call = ClientCall(
            input=_input,
            operation=NO_INPUT_AND_OUTPUT,
            context=TypedProperties({"config": _config}),
            interceptor=InterceptorChain(_config.interceptors),
            auth_scheme_resolver=_config.auth_scheme_resolver,
            supported_auth_schemes=_config.auth_schemes,
            endpoint_resolver=_config.endpoint_resolver,
            retry_strategy=_retry_strategy,
        )

        return await _pipeline(_call)

    async def put_with_content_encoding(
        self,
        *,
        encoding: str | None = None,
        data: str | None = None,
        plugins: list[Plugin] | None = None,
    ) -> PutWithContentEncodingOutput:
        """
        Invokes the PutWithContentEncoding operation.

        Args:
            plugins:
                A list of callables that modify the configuration dynamically.
                Changes made by these plugins only apply for the duration of the
                operation execution and will not affect any other operation
                invocations.

        Returns:
            An instance of `PutWithContentEncodingOutput`.
        """
        if self._closed:
            raise RuntimeError(
                "Cannot invoke an operation on a client that has been closed."
            )

        _input = PutWithContentEncodingInput(encoding=encoding, data=data)
        _operation_plugins: list[Plugin] = []
        if plugins:
            _operation_plugins.extend(plugins)
        await self._ensure_setup()
        assert self._config is not None
        if _operation_plugins:
            # Keep operation-plugin mutations scoped to this call.
            _config = _deepcopy(self._config)
            for _plugin in _operation_plugins:
                _plugin(_config)
        else:
            _config = self._config
        if (
            _config.protocol is None
            or _config.transport is None
            or _config.endpoint_resolver is None
            or _config.auth_scheme_resolver is None
            or _config.auth_schemes is None
        ):
            raise ExpectationNotMetError(
                "protocol, transport, endpoint_resolver, auth_scheme_resolver,"
                " and auth_schemes MUST be set on the config to make calls."
            )

        _retry_strategy = await self._retry_strategy_resolver.resolve_retry_strategy(
            retry_strategy=_config.retry_strategy,
            retry_mode=_config.retry_mode,
            max_attempts=_config.max_attempts,
        )

        _pipeline = RequestPipeline(
            protocol=_config.protocol, transport=_config.transport
        )
        _call = ClientCall(
            input=_input,
            operation=PUT_WITH_CONTENT_ENCODING,
            context=TypedProperties({"config": _config}),
            interceptor=InterceptorChain(_config.interceptors),
            auth_scheme_resolver=_config.auth_scheme_resolver,
            supported_auth_schemes=_config.auth_schemes,
            endpoint_resolver=_config.endpoint_resolver,
            retry_strategy=_retry_strategy,
        )

        return await _pipeline(_call)

    async def query_idempotency_token_auto_fill(
        self, *, token: str | None = None, plugins: list[Plugin] | None = None
    ) -> QueryIdempotencyTokenAutoFillOutput:
        """
        Automatically adds idempotency tokens.

        Args:
            plugins:
                A list of callables that modify the configuration dynamically.
                Changes made by these plugins only apply for the duration of the
                operation execution and will not affect any other operation
                invocations.

        Returns:
            An instance of `QueryIdempotencyTokenAutoFillOutput`.
        """
        if self._closed:
            raise RuntimeError(
                "Cannot invoke an operation on a client that has been closed."
            )

        _input = QueryIdempotencyTokenAutoFillInput(token=token)
        _operation_plugins: list[Plugin] = []
        if plugins:
            _operation_plugins.extend(plugins)
        await self._ensure_setup()
        assert self._config is not None
        if _operation_plugins:
            # Keep operation-plugin mutations scoped to this call.
            _config = _deepcopy(self._config)
            for _plugin in _operation_plugins:
                _plugin(_config)
        else:
            _config = self._config
        if (
            _config.protocol is None
            or _config.transport is None
            or _config.endpoint_resolver is None
            or _config.auth_scheme_resolver is None
            or _config.auth_schemes is None
        ):
            raise ExpectationNotMetError(
                "protocol, transport, endpoint_resolver, auth_scheme_resolver,"
                " and auth_schemes MUST be set on the config to make calls."
            )

        _retry_strategy = await self._retry_strategy_resolver.resolve_retry_strategy(
            retry_strategy=_config.retry_strategy,
            retry_mode=_config.retry_mode,
            max_attempts=_config.max_attempts,
        )

        _pipeline = RequestPipeline(
            protocol=_config.protocol, transport=_config.transport
        )
        _call = ClientCall(
            input=_input,
            operation=QUERY_IDEMPOTENCY_TOKEN_AUTO_FILL,
            context=TypedProperties({"config": _config}),
            interceptor=InterceptorChain(_config.interceptors),
            auth_scheme_resolver=_config.auth_scheme_resolver,
            supported_auth_schemes=_config.auth_schemes,
            endpoint_resolver=_config.endpoint_resolver,
            retry_strategy=_retry_strategy,
        )

        return await _pipeline(_call)

    async def query_lists(
        self,
        *,
        list_arg: list[str] | None = None,
        complex_list_arg: list[GreetingStruct] | None = None,
        flattened_list_arg: list[str] | None = None,
        list_arg_with_xml_name_member: list[str] | None = None,
        flattened_list_arg_with_xml_name: list[str] | None = None,
        nested_with_list: NestedStructWithList | None = None,
        plugins: list[Plugin] | None = None,
    ) -> QueryListsOutput:
        """
        This test serializes simple and complex lists.

        Args:
            plugins:
                A list of callables that modify the configuration dynamically.
                Changes made by these plugins only apply for the duration of the
                operation execution and will not affect any other operation
                invocations.

        Returns:
            An instance of `QueryListsOutput`.
        """
        if self._closed:
            raise RuntimeError(
                "Cannot invoke an operation on a client that has been closed."
            )

        _input = QueryListsInput(
            list_arg=list_arg,
            complex_list_arg=complex_list_arg,
            flattened_list_arg=flattened_list_arg,
            list_arg_with_xml_name_member=list_arg_with_xml_name_member,
            flattened_list_arg_with_xml_name=flattened_list_arg_with_xml_name,
            nested_with_list=nested_with_list,
        )
        _operation_plugins: list[Plugin] = []
        if plugins:
            _operation_plugins.extend(plugins)
        await self._ensure_setup()
        assert self._config is not None
        if _operation_plugins:
            # Keep operation-plugin mutations scoped to this call.
            _config = _deepcopy(self._config)
            for _plugin in _operation_plugins:
                _plugin(_config)
        else:
            _config = self._config
        if (
            _config.protocol is None
            or _config.transport is None
            or _config.endpoint_resolver is None
            or _config.auth_scheme_resolver is None
            or _config.auth_schemes is None
        ):
            raise ExpectationNotMetError(
                "protocol, transport, endpoint_resolver, auth_scheme_resolver,"
                " and auth_schemes MUST be set on the config to make calls."
            )

        _retry_strategy = await self._retry_strategy_resolver.resolve_retry_strategy(
            retry_strategy=_config.retry_strategy,
            retry_mode=_config.retry_mode,
            max_attempts=_config.max_attempts,
        )

        _pipeline = RequestPipeline(
            protocol=_config.protocol, transport=_config.transport
        )
        _call = ClientCall(
            input=_input,
            operation=QUERY_LISTS,
            context=TypedProperties({"config": _config}),
            interceptor=InterceptorChain(_config.interceptors),
            auth_scheme_resolver=_config.auth_scheme_resolver,
            supported_auth_schemes=_config.auth_schemes,
            endpoint_resolver=_config.endpoint_resolver,
            retry_strategy=_retry_strategy,
        )

        return await _pipeline(_call)

    async def query_maps(
        self,
        *,
        map_arg: dict[str, str] | None = None,
        renamed_map_arg: dict[str, str] | None = None,
        complex_map_arg: dict[str, GreetingStruct] | None = None,
        map_with_xml_member_name: dict[str, str] | None = None,
        flattened_map: dict[str, str] | None = None,
        flattened_map_with_xml_name: dict[str, str] | None = None,
        map_of_lists: dict[str, list[str]] | None = None,
        nested_struct_with_map: NestedStructWithMap | None = None,
        plugins: list[Plugin] | None = None,
    ) -> QueryMapsOutput:
        """
        This test serializes simple and complex maps.

        Args:
            plugins:
                A list of callables that modify the configuration dynamically.
                Changes made by these plugins only apply for the duration of the
                operation execution and will not affect any other operation
                invocations.

        Returns:
            An instance of `QueryMapsOutput`.
        """
        if self._closed:
            raise RuntimeError(
                "Cannot invoke an operation on a client that has been closed."
            )

        _input = QueryMapsInput(
            map_arg=map_arg,
            renamed_map_arg=renamed_map_arg,
            complex_map_arg=complex_map_arg,
            map_with_xml_member_name=map_with_xml_member_name,
            flattened_map=flattened_map,
            flattened_map_with_xml_name=flattened_map_with_xml_name,
            map_of_lists=map_of_lists,
            nested_struct_with_map=nested_struct_with_map,
        )
        _operation_plugins: list[Plugin] = []
        if plugins:
            _operation_plugins.extend(plugins)
        await self._ensure_setup()
        assert self._config is not None
        if _operation_plugins:
            # Keep operation-plugin mutations scoped to this call.
            _config = _deepcopy(self._config)
            for _plugin in _operation_plugins:
                _plugin(_config)
        else:
            _config = self._config
        if (
            _config.protocol is None
            or _config.transport is None
            or _config.endpoint_resolver is None
            or _config.auth_scheme_resolver is None
            or _config.auth_schemes is None
        ):
            raise ExpectationNotMetError(
                "protocol, transport, endpoint_resolver, auth_scheme_resolver,"
                " and auth_schemes MUST be set on the config to make calls."
            )

        _retry_strategy = await self._retry_strategy_resolver.resolve_retry_strategy(
            retry_strategy=_config.retry_strategy,
            retry_mode=_config.retry_mode,
            max_attempts=_config.max_attempts,
        )

        _pipeline = RequestPipeline(
            protocol=_config.protocol, transport=_config.transport
        )
        _call = ClientCall(
            input=_input,
            operation=QUERY_MAPS,
            context=TypedProperties({"config": _config}),
            interceptor=InterceptorChain(_config.interceptors),
            auth_scheme_resolver=_config.auth_scheme_resolver,
            supported_auth_schemes=_config.auth_schemes,
            endpoint_resolver=_config.endpoint_resolver,
            retry_strategy=_retry_strategy,
        )

        return await _pipeline(_call)

    async def query_timestamps(
        self,
        *,
        normal_format: datetime | None = None,
        epoch_member: datetime | None = None,
        epoch_target: datetime | None = None,
        plugins: list[Plugin] | None = None,
    ) -> QueryTimestampsOutput:
        """
        This test serializes timestamps. 1. Timestamps are serialized as RFC
        3339 date-time values by default. 2. A timestampFormat trait on a member
        changes the format. 3. A timestampFormat trait on the shape targeted by
        the member changes the format.

        Args:
            plugins:
                A list of callables that modify the configuration dynamically.
                Changes made by these plugins only apply for the duration of the
                operation execution and will not affect any other operation
                invocations.

        Returns:
            An instance of `QueryTimestampsOutput`.
        """
        if self._closed:
            raise RuntimeError(
                "Cannot invoke an operation on a client that has been closed."
            )

        _input = QueryTimestampsInput(
            normal_format=normal_format,
            epoch_member=epoch_member,
            epoch_target=epoch_target,
        )
        _operation_plugins: list[Plugin] = []
        if plugins:
            _operation_plugins.extend(plugins)
        await self._ensure_setup()
        assert self._config is not None
        if _operation_plugins:
            # Keep operation-plugin mutations scoped to this call.
            _config = _deepcopy(self._config)
            for _plugin in _operation_plugins:
                _plugin(_config)
        else:
            _config = self._config
        if (
            _config.protocol is None
            or _config.transport is None
            or _config.endpoint_resolver is None
            or _config.auth_scheme_resolver is None
            or _config.auth_schemes is None
        ):
            raise ExpectationNotMetError(
                "protocol, transport, endpoint_resolver, auth_scheme_resolver,"
                " and auth_schemes MUST be set on the config to make calls."
            )

        _retry_strategy = await self._retry_strategy_resolver.resolve_retry_strategy(
            retry_strategy=_config.retry_strategy,
            retry_mode=_config.retry_mode,
            max_attempts=_config.max_attempts,
        )

        _pipeline = RequestPipeline(
            protocol=_config.protocol, transport=_config.transport
        )
        _call = ClientCall(
            input=_input,
            operation=QUERY_TIMESTAMPS,
            context=TypedProperties({"config": _config}),
            interceptor=InterceptorChain(_config.interceptors),
            auth_scheme_resolver=_config.auth_scheme_resolver,
            supported_auth_schemes=_config.auth_schemes,
            endpoint_resolver=_config.endpoint_resolver,
            retry_strategy=_retry_strategy,
        )

        return await _pipeline(_call)

    async def recursive_xml_shapes(
        self, *, plugins: list[Plugin] | None = None
    ) -> RecursiveXmlShapesOutput:
        """
        Recursive shapes

        Args:
            plugins:
                A list of callables that modify the configuration dynamically.
                Changes made by these plugins only apply for the duration of the
                operation execution and will not affect any other operation
                invocations.

        Returns:
            An instance of `RecursiveXmlShapesOutput`.
        """
        if self._closed:
            raise RuntimeError(
                "Cannot invoke an operation on a client that has been closed."
            )

        _input = RecursiveXmlShapesInput()
        _operation_plugins: list[Plugin] = []
        if plugins:
            _operation_plugins.extend(plugins)
        await self._ensure_setup()
        assert self._config is not None
        if _operation_plugins:
            # Keep operation-plugin mutations scoped to this call.
            _config = _deepcopy(self._config)
            for _plugin in _operation_plugins:
                _plugin(_config)
        else:
            _config = self._config
        if (
            _config.protocol is None
            or _config.transport is None
            or _config.endpoint_resolver is None
            or _config.auth_scheme_resolver is None
            or _config.auth_schemes is None
        ):
            raise ExpectationNotMetError(
                "protocol, transport, endpoint_resolver, auth_scheme_resolver,"
                " and auth_schemes MUST be set on the config to make calls."
            )

        _retry_strategy = await self._retry_strategy_resolver.resolve_retry_strategy(
            retry_strategy=_config.retry_strategy,
            retry_mode=_config.retry_mode,
            max_attempts=_config.max_attempts,
        )

        _pipeline = RequestPipeline(
            protocol=_config.protocol, transport=_config.transport
        )
        _call = ClientCall(
            input=_input,
            operation=RECURSIVE_XML_SHAPES,
            context=TypedProperties({"config": _config}),
            interceptor=InterceptorChain(_config.interceptors),
            auth_scheme_resolver=_config.auth_scheme_resolver,
            supported_auth_schemes=_config.auth_schemes,
            endpoint_resolver=_config.endpoint_resolver,
            retry_strategy=_retry_strategy,
        )

        return await _pipeline(_call)

    async def simple_input_params(
        self,
        *,
        foo: str | None = None,
        bar: str | None = None,
        baz: bool | None = None,
        bam: int | None = None,
        float_value: float | None = None,
        boo: float | None = None,
        qux: bytes | None = None,
        foo_enum: str | None = None,
        integer_enum: int | None = None,
        plugins: list[Plugin] | None = None,
    ) -> SimpleInputParamsOutput:
        """
        This test serializes strings, numbers, and boolean values.

        Args:
            plugins:
                A list of callables that modify the configuration dynamically.
                Changes made by these plugins only apply for the duration of the
                operation execution and will not affect any other operation
                invocations.

        Returns:
            An instance of `SimpleInputParamsOutput`.
        """
        if self._closed:
            raise RuntimeError(
                "Cannot invoke an operation on a client that has been closed."
            )

        _input = SimpleInputParamsInput(
            foo=foo,
            bar=bar,
            baz=baz,
            bam=bam,
            float_value=float_value,
            boo=boo,
            qux=qux,
            foo_enum=foo_enum,
            integer_enum=integer_enum,
        )
        _operation_plugins: list[Plugin] = []
        if plugins:
            _operation_plugins.extend(plugins)
        await self._ensure_setup()
        assert self._config is not None
        if _operation_plugins:
            # Keep operation-plugin mutations scoped to this call.
            _config = _deepcopy(self._config)
            for _plugin in _operation_plugins:
                _plugin(_config)
        else:
            _config = self._config
        if (
            _config.protocol is None
            or _config.transport is None
            or _config.endpoint_resolver is None
            or _config.auth_scheme_resolver is None
            or _config.auth_schemes is None
        ):
            raise ExpectationNotMetError(
                "protocol, transport, endpoint_resolver, auth_scheme_resolver,"
                " and auth_schemes MUST be set on the config to make calls."
            )

        _retry_strategy = await self._retry_strategy_resolver.resolve_retry_strategy(
            retry_strategy=_config.retry_strategy,
            retry_mode=_config.retry_mode,
            max_attempts=_config.max_attempts,
        )

        _pipeline = RequestPipeline(
            protocol=_config.protocol, transport=_config.transport
        )
        _call = ClientCall(
            input=_input,
            operation=SIMPLE_INPUT_PARAMS,
            context=TypedProperties({"config": _config}),
            interceptor=InterceptorChain(_config.interceptors),
            auth_scheme_resolver=_config.auth_scheme_resolver,
            supported_auth_schemes=_config.auth_schemes,
            endpoint_resolver=_config.endpoint_resolver,
            retry_strategy=_retry_strategy,
        )

        return await _pipeline(_call)

    async def simple_scalar_xml_properties(
        self, *, plugins: list[Plugin] | None = None
    ) -> SimpleScalarXmlPropertiesOutput:
        """
        Invokes the SimpleScalarXmlProperties operation.

        Args:
            plugins:
                A list of callables that modify the configuration dynamically.
                Changes made by these plugins only apply for the duration of the
                operation execution and will not affect any other operation
                invocations.

        Returns:
            An instance of `SimpleScalarXmlPropertiesOutput`.
        """
        if self._closed:
            raise RuntimeError(
                "Cannot invoke an operation on a client that has been closed."
            )

        _input = SimpleScalarXmlPropertiesInput()
        _operation_plugins: list[Plugin] = []
        if plugins:
            _operation_plugins.extend(plugins)
        await self._ensure_setup()
        assert self._config is not None
        if _operation_plugins:
            # Keep operation-plugin mutations scoped to this call.
            _config = _deepcopy(self._config)
            for _plugin in _operation_plugins:
                _plugin(_config)
        else:
            _config = self._config
        if (
            _config.protocol is None
            or _config.transport is None
            or _config.endpoint_resolver is None
            or _config.auth_scheme_resolver is None
            or _config.auth_schemes is None
        ):
            raise ExpectationNotMetError(
                "protocol, transport, endpoint_resolver, auth_scheme_resolver,"
                " and auth_schemes MUST be set on the config to make calls."
            )

        _retry_strategy = await self._retry_strategy_resolver.resolve_retry_strategy(
            retry_strategy=_config.retry_strategy,
            retry_mode=_config.retry_mode,
            max_attempts=_config.max_attempts,
        )

        _pipeline = RequestPipeline(
            protocol=_config.protocol, transport=_config.transport
        )
        _call = ClientCall(
            input=_input,
            operation=SIMPLE_SCALAR_XML_PROPERTIES,
            context=TypedProperties({"config": _config}),
            interceptor=InterceptorChain(_config.interceptors),
            auth_scheme_resolver=_config.auth_scheme_resolver,
            supported_auth_schemes=_config.auth_schemes,
            endpoint_resolver=_config.endpoint_resolver,
            retry_strategy=_retry_strategy,
        )

        return await _pipeline(_call)

    async def xml_blobs(
        self, *, plugins: list[Plugin] | None = None
    ) -> XmlBlobsOperationOutput:
        """
        Blobs are base64 encoded

        Args:
            plugins:
                A list of callables that modify the configuration dynamically.
                Changes made by these plugins only apply for the duration of the
                operation execution and will not affect any other operation
                invocations.

        Returns:
            An instance of `XmlBlobsOperationOutput`.
        """
        if self._closed:
            raise RuntimeError(
                "Cannot invoke an operation on a client that has been closed."
            )

        _input = XmlBlobsInput()
        _operation_plugins: list[Plugin] = []
        if plugins:
            _operation_plugins.extend(plugins)
        await self._ensure_setup()
        assert self._config is not None
        if _operation_plugins:
            # Keep operation-plugin mutations scoped to this call.
            _config = _deepcopy(self._config)
            for _plugin in _operation_plugins:
                _plugin(_config)
        else:
            _config = self._config
        if (
            _config.protocol is None
            or _config.transport is None
            or _config.endpoint_resolver is None
            or _config.auth_scheme_resolver is None
            or _config.auth_schemes is None
        ):
            raise ExpectationNotMetError(
                "protocol, transport, endpoint_resolver, auth_scheme_resolver,"
                " and auth_schemes MUST be set on the config to make calls."
            )

        _retry_strategy = await self._retry_strategy_resolver.resolve_retry_strategy(
            retry_strategy=_config.retry_strategy,
            retry_mode=_config.retry_mode,
            max_attempts=_config.max_attempts,
        )

        _pipeline = RequestPipeline(
            protocol=_config.protocol, transport=_config.transport
        )
        _call = ClientCall(
            input=_input,
            operation=XML_BLOBS,
            context=TypedProperties({"config": _config}),
            interceptor=InterceptorChain(_config.interceptors),
            auth_scheme_resolver=_config.auth_scheme_resolver,
            supported_auth_schemes=_config.auth_schemes,
            endpoint_resolver=_config.endpoint_resolver,
            retry_strategy=_retry_strategy,
        )

        return await _pipeline(_call)

    async def xml_empty_blobs(
        self, *, plugins: list[Plugin] | None = None
    ) -> XmlEmptyBlobsOutput:
        """
        Invokes the XmlEmptyBlobs operation.

        Args:
            plugins:
                A list of callables that modify the configuration dynamically.
                Changes made by these plugins only apply for the duration of the
                operation execution and will not affect any other operation
                invocations.

        Returns:
            An instance of `XmlEmptyBlobsOutput`.
        """
        if self._closed:
            raise RuntimeError(
                "Cannot invoke an operation on a client that has been closed."
            )

        _input = XmlEmptyBlobsInput()
        _operation_plugins: list[Plugin] = []
        if plugins:
            _operation_plugins.extend(plugins)
        await self._ensure_setup()
        assert self._config is not None
        if _operation_plugins:
            # Keep operation-plugin mutations scoped to this call.
            _config = _deepcopy(self._config)
            for _plugin in _operation_plugins:
                _plugin(_config)
        else:
            _config = self._config
        if (
            _config.protocol is None
            or _config.transport is None
            or _config.endpoint_resolver is None
            or _config.auth_scheme_resolver is None
            or _config.auth_schemes is None
        ):
            raise ExpectationNotMetError(
                "protocol, transport, endpoint_resolver, auth_scheme_resolver,"
                " and auth_schemes MUST be set on the config to make calls."
            )

        _retry_strategy = await self._retry_strategy_resolver.resolve_retry_strategy(
            retry_strategy=_config.retry_strategy,
            retry_mode=_config.retry_mode,
            max_attempts=_config.max_attempts,
        )

        _pipeline = RequestPipeline(
            protocol=_config.protocol, transport=_config.transport
        )
        _call = ClientCall(
            input=_input,
            operation=XML_EMPTY_BLOBS,
            context=TypedProperties({"config": _config}),
            interceptor=InterceptorChain(_config.interceptors),
            auth_scheme_resolver=_config.auth_scheme_resolver,
            supported_auth_schemes=_config.auth_schemes,
            endpoint_resolver=_config.endpoint_resolver,
            retry_strategy=_retry_strategy,
        )

        return await _pipeline(_call)

    async def xml_empty_lists(
        self, *, plugins: list[Plugin] | None = None
    ) -> XmlEmptyListsOutput:
        """
        Invokes the XmlEmptyLists operation.

        Args:
            plugins:
                A list of callables that modify the configuration dynamically.
                Changes made by these plugins only apply for the duration of the
                operation execution and will not affect any other operation
                invocations.

        Returns:
            An instance of `XmlEmptyListsOutput`.
        """
        if self._closed:
            raise RuntimeError(
                "Cannot invoke an operation on a client that has been closed."
            )

        _input = XmlEmptyListsInput()
        _operation_plugins: list[Plugin] = []
        if plugins:
            _operation_plugins.extend(plugins)
        await self._ensure_setup()
        assert self._config is not None
        if _operation_plugins:
            # Keep operation-plugin mutations scoped to this call.
            _config = _deepcopy(self._config)
            for _plugin in _operation_plugins:
                _plugin(_config)
        else:
            _config = self._config
        if (
            _config.protocol is None
            or _config.transport is None
            or _config.endpoint_resolver is None
            or _config.auth_scheme_resolver is None
            or _config.auth_schemes is None
        ):
            raise ExpectationNotMetError(
                "protocol, transport, endpoint_resolver, auth_scheme_resolver,"
                " and auth_schemes MUST be set on the config to make calls."
            )

        _retry_strategy = await self._retry_strategy_resolver.resolve_retry_strategy(
            retry_strategy=_config.retry_strategy,
            retry_mode=_config.retry_mode,
            max_attempts=_config.max_attempts,
        )

        _pipeline = RequestPipeline(
            protocol=_config.protocol, transport=_config.transport
        )
        _call = ClientCall(
            input=_input,
            operation=XML_EMPTY_LISTS,
            context=TypedProperties({"config": _config}),
            interceptor=InterceptorChain(_config.interceptors),
            auth_scheme_resolver=_config.auth_scheme_resolver,
            supported_auth_schemes=_config.auth_schemes,
            endpoint_resolver=_config.endpoint_resolver,
            retry_strategy=_retry_strategy,
        )

        return await _pipeline(_call)

    async def xml_empty_maps(
        self, *, plugins: list[Plugin] | None = None
    ) -> XmlEmptyMapsOutput:
        """
        Invokes the XmlEmptyMaps operation.

        Args:
            plugins:
                A list of callables that modify the configuration dynamically.
                Changes made by these plugins only apply for the duration of the
                operation execution and will not affect any other operation
                invocations.

        Returns:
            An instance of `XmlEmptyMapsOutput`.
        """
        if self._closed:
            raise RuntimeError(
                "Cannot invoke an operation on a client that has been closed."
            )

        _input = XmlEmptyMapsInput()
        _operation_plugins: list[Plugin] = []
        if plugins:
            _operation_plugins.extend(plugins)
        await self._ensure_setup()
        assert self._config is not None
        if _operation_plugins:
            # Keep operation-plugin mutations scoped to this call.
            _config = _deepcopy(self._config)
            for _plugin in _operation_plugins:
                _plugin(_config)
        else:
            _config = self._config
        if (
            _config.protocol is None
            or _config.transport is None
            or _config.endpoint_resolver is None
            or _config.auth_scheme_resolver is None
            or _config.auth_schemes is None
        ):
            raise ExpectationNotMetError(
                "protocol, transport, endpoint_resolver, auth_scheme_resolver,"
                " and auth_schemes MUST be set on the config to make calls."
            )

        _retry_strategy = await self._retry_strategy_resolver.resolve_retry_strategy(
            retry_strategy=_config.retry_strategy,
            retry_mode=_config.retry_mode,
            max_attempts=_config.max_attempts,
        )

        _pipeline = RequestPipeline(
            protocol=_config.protocol, transport=_config.transport
        )
        _call = ClientCall(
            input=_input,
            operation=XML_EMPTY_MAPS,
            context=TypedProperties({"config": _config}),
            interceptor=InterceptorChain(_config.interceptors),
            auth_scheme_resolver=_config.auth_scheme_resolver,
            supported_auth_schemes=_config.auth_schemes,
            endpoint_resolver=_config.endpoint_resolver,
            retry_strategy=_retry_strategy,
        )

        return await _pipeline(_call)

    async def xml_enums(self, *, plugins: list[Plugin] | None = None) -> XmlEnumsOutput:
        """
        This example serializes enums as top level properties, in lists, sets,
        and maps.

        Args:
            plugins:
                A list of callables that modify the configuration dynamically.
                Changes made by these plugins only apply for the duration of the
                operation execution and will not affect any other operation
                invocations.

        Returns:
            An instance of `XmlEnumsOutput`.
        """
        if self._closed:
            raise RuntimeError(
                "Cannot invoke an operation on a client that has been closed."
            )

        _input = XmlEnumsInput()
        _operation_plugins: list[Plugin] = []
        if plugins:
            _operation_plugins.extend(plugins)
        await self._ensure_setup()
        assert self._config is not None
        if _operation_plugins:
            # Keep operation-plugin mutations scoped to this call.
            _config = _deepcopy(self._config)
            for _plugin in _operation_plugins:
                _plugin(_config)
        else:
            _config = self._config
        if (
            _config.protocol is None
            or _config.transport is None
            or _config.endpoint_resolver is None
            or _config.auth_scheme_resolver is None
            or _config.auth_schemes is None
        ):
            raise ExpectationNotMetError(
                "protocol, transport, endpoint_resolver, auth_scheme_resolver,"
                " and auth_schemes MUST be set on the config to make calls."
            )

        _retry_strategy = await self._retry_strategy_resolver.resolve_retry_strategy(
            retry_strategy=_config.retry_strategy,
            retry_mode=_config.retry_mode,
            max_attempts=_config.max_attempts,
        )

        _pipeline = RequestPipeline(
            protocol=_config.protocol, transport=_config.transport
        )
        _call = ClientCall(
            input=_input,
            operation=XML_ENUMS,
            context=TypedProperties({"config": _config}),
            interceptor=InterceptorChain(_config.interceptors),
            auth_scheme_resolver=_config.auth_scheme_resolver,
            supported_auth_schemes=_config.auth_schemes,
            endpoint_resolver=_config.endpoint_resolver,
            retry_strategy=_retry_strategy,
        )

        return await _pipeline(_call)

    async def xml_int_enums(
        self, *, plugins: list[Plugin] | None = None
    ) -> XmlIntEnumsOutput:
        """
        This example serializes enums as top level properties, in lists, sets,
        and maps.

        Args:
            plugins:
                A list of callables that modify the configuration dynamically.
                Changes made by these plugins only apply for the duration of the
                operation execution and will not affect any other operation
                invocations.

        Returns:
            An instance of `XmlIntEnumsOutput`.
        """
        if self._closed:
            raise RuntimeError(
                "Cannot invoke an operation on a client that has been closed."
            )

        _input = XmlIntEnumsInput()
        _operation_plugins: list[Plugin] = []
        if plugins:
            _operation_plugins.extend(plugins)
        await self._ensure_setup()
        assert self._config is not None
        if _operation_plugins:
            # Keep operation-plugin mutations scoped to this call.
            _config = _deepcopy(self._config)
            for _plugin in _operation_plugins:
                _plugin(_config)
        else:
            _config = self._config
        if (
            _config.protocol is None
            or _config.transport is None
            or _config.endpoint_resolver is None
            or _config.auth_scheme_resolver is None
            or _config.auth_schemes is None
        ):
            raise ExpectationNotMetError(
                "protocol, transport, endpoint_resolver, auth_scheme_resolver,"
                " and auth_schemes MUST be set on the config to make calls."
            )

        _retry_strategy = await self._retry_strategy_resolver.resolve_retry_strategy(
            retry_strategy=_config.retry_strategy,
            retry_mode=_config.retry_mode,
            max_attempts=_config.max_attempts,
        )

        _pipeline = RequestPipeline(
            protocol=_config.protocol, transport=_config.transport
        )
        _call = ClientCall(
            input=_input,
            operation=XML_INT_ENUMS,
            context=TypedProperties({"config": _config}),
            interceptor=InterceptorChain(_config.interceptors),
            auth_scheme_resolver=_config.auth_scheme_resolver,
            supported_auth_schemes=_config.auth_schemes,
            endpoint_resolver=_config.endpoint_resolver,
            retry_strategy=_retry_strategy,
        )

        return await _pipeline(_call)

    async def xml_lists(
        self, *, plugins: list[Plugin] | None = None
    ) -> XmlListsOperationOutput:
        """
        This test case serializes XML lists for the following cases for both
        input and output: 1. Normal XML lists. 2. Normal XML sets. 3. XML lists
        of lists. 4. XML lists with @xmlName on its members 5. Flattened XML
        lists. 6. Flattened XML lists with @xmlName. 7. Lists of structures.

        Args:
            plugins:
                A list of callables that modify the configuration dynamically.
                Changes made by these plugins only apply for the duration of the
                operation execution and will not affect any other operation
                invocations.

        Returns:
            An instance of `XmlListsOperationOutput`.
        """
        if self._closed:
            raise RuntimeError(
                "Cannot invoke an operation on a client that has been closed."
            )

        _input = XmlListsInput()
        _operation_plugins: list[Plugin] = []
        if plugins:
            _operation_plugins.extend(plugins)
        await self._ensure_setup()
        assert self._config is not None
        if _operation_plugins:
            # Keep operation-plugin mutations scoped to this call.
            _config = _deepcopy(self._config)
            for _plugin in _operation_plugins:
                _plugin(_config)
        else:
            _config = self._config
        if (
            _config.protocol is None
            or _config.transport is None
            or _config.endpoint_resolver is None
            or _config.auth_scheme_resolver is None
            or _config.auth_schemes is None
        ):
            raise ExpectationNotMetError(
                "protocol, transport, endpoint_resolver, auth_scheme_resolver,"
                " and auth_schemes MUST be set on the config to make calls."
            )

        _retry_strategy = await self._retry_strategy_resolver.resolve_retry_strategy(
            retry_strategy=_config.retry_strategy,
            retry_mode=_config.retry_mode,
            max_attempts=_config.max_attempts,
        )

        _pipeline = RequestPipeline(
            protocol=_config.protocol, transport=_config.transport
        )
        _call = ClientCall(
            input=_input,
            operation=XML_LISTS,
            context=TypedProperties({"config": _config}),
            interceptor=InterceptorChain(_config.interceptors),
            auth_scheme_resolver=_config.auth_scheme_resolver,
            supported_auth_schemes=_config.auth_schemes,
            endpoint_resolver=_config.endpoint_resolver,
            retry_strategy=_retry_strategy,
        )

        return await _pipeline(_call)

    async def xml_maps(
        self, *, plugins: list[Plugin] | None = None
    ) -> XmlMapsOperationOutput:
        """
        The example tests basic map serialization.

        Args:
            plugins:
                A list of callables that modify the configuration dynamically.
                Changes made by these plugins only apply for the duration of the
                operation execution and will not affect any other operation
                invocations.

        Returns:
            An instance of `XmlMapsOperationOutput`.
        """
        if self._closed:
            raise RuntimeError(
                "Cannot invoke an operation on a client that has been closed."
            )

        _input = XmlMapsInput()
        _operation_plugins: list[Plugin] = []
        if plugins:
            _operation_plugins.extend(plugins)
        await self._ensure_setup()
        assert self._config is not None
        if _operation_plugins:
            # Keep operation-plugin mutations scoped to this call.
            _config = _deepcopy(self._config)
            for _plugin in _operation_plugins:
                _plugin(_config)
        else:
            _config = self._config
        if (
            _config.protocol is None
            or _config.transport is None
            or _config.endpoint_resolver is None
            or _config.auth_scheme_resolver is None
            or _config.auth_schemes is None
        ):
            raise ExpectationNotMetError(
                "protocol, transport, endpoint_resolver, auth_scheme_resolver,"
                " and auth_schemes MUST be set on the config to make calls."
            )

        _retry_strategy = await self._retry_strategy_resolver.resolve_retry_strategy(
            retry_strategy=_config.retry_strategy,
            retry_mode=_config.retry_mode,
            max_attempts=_config.max_attempts,
        )

        _pipeline = RequestPipeline(
            protocol=_config.protocol, transport=_config.transport
        )
        _call = ClientCall(
            input=_input,
            operation=XML_MAPS,
            context=TypedProperties({"config": _config}),
            interceptor=InterceptorChain(_config.interceptors),
            auth_scheme_resolver=_config.auth_scheme_resolver,
            supported_auth_schemes=_config.auth_schemes,
            endpoint_resolver=_config.endpoint_resolver,
            retry_strategy=_retry_strategy,
        )

        return await _pipeline(_call)

    async def xml_maps_xml_name(
        self, *, plugins: list[Plugin] | None = None
    ) -> XmlMapsXmlNameOutput:
        """
        Invokes the XmlMapsXmlName operation.

        Args:
            plugins:
                A list of callables that modify the configuration dynamically.
                Changes made by these plugins only apply for the duration of the
                operation execution and will not affect any other operation
                invocations.

        Returns:
            An instance of `XmlMapsXmlNameOutput`.
        """
        if self._closed:
            raise RuntimeError(
                "Cannot invoke an operation on a client that has been closed."
            )

        _input = XmlMapsXmlNameInput()
        _operation_plugins: list[Plugin] = []
        if plugins:
            _operation_plugins.extend(plugins)
        await self._ensure_setup()
        assert self._config is not None
        if _operation_plugins:
            # Keep operation-plugin mutations scoped to this call.
            _config = _deepcopy(self._config)
            for _plugin in _operation_plugins:
                _plugin(_config)
        else:
            _config = self._config
        if (
            _config.protocol is None
            or _config.transport is None
            or _config.endpoint_resolver is None
            or _config.auth_scheme_resolver is None
            or _config.auth_schemes is None
        ):
            raise ExpectationNotMetError(
                "protocol, transport, endpoint_resolver, auth_scheme_resolver,"
                " and auth_schemes MUST be set on the config to make calls."
            )

        _retry_strategy = await self._retry_strategy_resolver.resolve_retry_strategy(
            retry_strategy=_config.retry_strategy,
            retry_mode=_config.retry_mode,
            max_attempts=_config.max_attempts,
        )

        _pipeline = RequestPipeline(
            protocol=_config.protocol, transport=_config.transport
        )
        _call = ClientCall(
            input=_input,
            operation=XML_MAPS_XML_NAME,
            context=TypedProperties({"config": _config}),
            interceptor=InterceptorChain(_config.interceptors),
            auth_scheme_resolver=_config.auth_scheme_resolver,
            supported_auth_schemes=_config.auth_schemes,
            endpoint_resolver=_config.endpoint_resolver,
            retry_strategy=_retry_strategy,
        )

        return await _pipeline(_call)

    async def xml_namespaces(
        self, *, plugins: list[Plugin] | None = None
    ) -> XmlNamespacesOutput:
        """
        Invokes the XmlNamespaces operation.

        Args:
            plugins:
                A list of callables that modify the configuration dynamically.
                Changes made by these plugins only apply for the duration of the
                operation execution and will not affect any other operation
                invocations.

        Returns:
            An instance of `XmlNamespacesOutput`.
        """
        if self._closed:
            raise RuntimeError(
                "Cannot invoke an operation on a client that has been closed."
            )

        _input = XmlNamespacesInput()
        _operation_plugins: list[Plugin] = []
        if plugins:
            _operation_plugins.extend(plugins)
        await self._ensure_setup()
        assert self._config is not None
        if _operation_plugins:
            # Keep operation-plugin mutations scoped to this call.
            _config = _deepcopy(self._config)
            for _plugin in _operation_plugins:
                _plugin(_config)
        else:
            _config = self._config
        if (
            _config.protocol is None
            or _config.transport is None
            or _config.endpoint_resolver is None
            or _config.auth_scheme_resolver is None
            or _config.auth_schemes is None
        ):
            raise ExpectationNotMetError(
                "protocol, transport, endpoint_resolver, auth_scheme_resolver,"
                " and auth_schemes MUST be set on the config to make calls."
            )

        _retry_strategy = await self._retry_strategy_resolver.resolve_retry_strategy(
            retry_strategy=_config.retry_strategy,
            retry_mode=_config.retry_mode,
            max_attempts=_config.max_attempts,
        )

        _pipeline = RequestPipeline(
            protocol=_config.protocol, transport=_config.transport
        )
        _call = ClientCall(
            input=_input,
            operation=XML_NAMESPACES,
            context=TypedProperties({"config": _config}),
            interceptor=InterceptorChain(_config.interceptors),
            auth_scheme_resolver=_config.auth_scheme_resolver,
            supported_auth_schemes=_config.auth_schemes,
            endpoint_resolver=_config.endpoint_resolver,
            retry_strategy=_retry_strategy,
        )

        return await _pipeline(_call)

    async def xml_timestamps(
        self, *, plugins: list[Plugin] | None = None
    ) -> XmlTimestampsOutput:
        """
        This tests how timestamps are serialized, including using the default
        format of date-time and various @timestampFormat trait values.

        Args:
            plugins:
                A list of callables that modify the configuration dynamically.
                Changes made by these plugins only apply for the duration of the
                operation execution and will not affect any other operation
                invocations.

        Returns:
            An instance of `XmlTimestampsOutput`.
        """
        if self._closed:
            raise RuntimeError(
                "Cannot invoke an operation on a client that has been closed."
            )

        _input = XmlTimestampsInput()
        _operation_plugins: list[Plugin] = []
        if plugins:
            _operation_plugins.extend(plugins)
        await self._ensure_setup()
        assert self._config is not None
        if _operation_plugins:
            # Keep operation-plugin mutations scoped to this call.
            _config = _deepcopy(self._config)
            for _plugin in _operation_plugins:
                _plugin(_config)
        else:
            _config = self._config
        if (
            _config.protocol is None
            or _config.transport is None
            or _config.endpoint_resolver is None
            or _config.auth_scheme_resolver is None
            or _config.auth_schemes is None
        ):
            raise ExpectationNotMetError(
                "protocol, transport, endpoint_resolver, auth_scheme_resolver,"
                " and auth_schemes MUST be set on the config to make calls."
            )

        _retry_strategy = await self._retry_strategy_resolver.resolve_retry_strategy(
            retry_strategy=_config.retry_strategy,
            retry_mode=_config.retry_mode,
            max_attempts=_config.max_attempts,
        )

        _pipeline = RequestPipeline(
            protocol=_config.protocol, transport=_config.transport
        )
        _call = ClientCall(
            input=_input,
            operation=XML_TIMESTAMPS,
            context=TypedProperties({"config": _config}),
            interceptor=InterceptorChain(_config.interceptors),
            auth_scheme_resolver=_config.auth_scheme_resolver,
            supported_auth_schemes=_config.auth_schemes,
            endpoint_resolver=_config.endpoint_resolver,
            retry_strategy=_retry_strategy,
        )

        return await _pipeline(_call)
