# Code generated by smithy-python-codegen DO NOT EDIT.

from dataclasses import dataclass, field
from typing import Any, Callable, ClassVar, Self, TypeAlias, Union, Unpack

from smithy_aws_core.aio.protocols import RestXmlClientProtocol
from smithy_aws_core.auth import SigV4AuthScheme
from smithy_aws_core.config import AwsConfigOverrides, FileSystem
from smithy_aws_core.config.aws_config import AsyncAwsConfig
from smithy_aws_core.config.resolvers import EndpointUriResolver
from smithy_aws_core.config.types import FieldSpec
from smithy_aws_core.endpoints.standard_regional import (
    StandardRegionalEndpointsResolver,
)
from smithy_aws_core.identity import AWSCredentialsIdentity, AWSIdentityProperties
from smithy_core.aio.interfaces import (
    ClientProtocol,
    EndpointResolver,
    ProtocolConstructor,
    ProtocolSettings,
)
from smithy_core.aio.interfaces.auth import AuthScheme
from smithy_core.aio.interfaces.identity import IdentityResolver
from smithy_core.interceptors import Interceptor
from smithy_core.interfaces.auth import AuthSchemeResolver
from smithy_core.shapes import ShapeID
from smithy_http.aio.aiohttp import AIOHTTPClient

from .auth import HTTPAuthSchemeResolver
from .models import (
    AllQueryStringTypesInput,
    AllQueryStringTypesOutput,
    BodyWithXmlNameInput,
    BodyWithXmlNameOutput,
    ConstantAndVariableQueryStringInput,
    ConstantAndVariableQueryStringOutput,
    ConstantQueryStringInput,
    ConstantQueryStringOutput,
    ContentTypeParametersInput,
    ContentTypeParametersOutput,
    DatetimeOffsetsInput,
    DatetimeOffsetsOutput,
    EmptyInputAndEmptyOutputInput,
    EmptyInputAndEmptyOutputOutput,
    EndpointOperationInput,
    EndpointOperationOutput,
    EndpointWithHostLabelHeaderOperationInput,
    EndpointWithHostLabelHeaderOperationOutput,
    EndpointWithHostLabelOperationInput,
    EndpointWithHostLabelOperationOutput,
    FlattenedXmlMapInput,
    FlattenedXmlMapOutput,
    FlattenedXmlMapWithXmlNameInput,
    FlattenedXmlMapWithXmlNameOutput,
    FlattenedXmlMapWithXmlNamespaceInput,
    FlattenedXmlMapWithXmlNamespaceOutput,
    FractionalSecondsInput,
    FractionalSecondsOutput,
    GreetingWithErrorsInput,
    GreetingWithErrorsOutput,
    HttpEmptyPrefixHeadersInput,
    HttpEmptyPrefixHeadersOutput,
    HttpEnumPayloadInput,
    HttpEnumPayloadOutput,
    HttpPayloadTraitsInput,
    HttpPayloadTraitsOutput,
    HttpPayloadTraitsWithMediaTypeInput,
    HttpPayloadTraitsWithMediaTypeOutput,
    HttpPayloadWithMemberXmlNameInput,
    HttpPayloadWithMemberXmlNameOutput,
    HttpPayloadWithStructureInput,
    HttpPayloadWithStructureOutput,
    HttpPayloadWithUnionInput,
    HttpPayloadWithUnionOutput,
    HttpPayloadWithXmlNameInput,
    HttpPayloadWithXmlNameOutput,
    HttpPayloadWithXmlNamespaceAndPrefixInput,
    HttpPayloadWithXmlNamespaceAndPrefixOutput,
    HttpPayloadWithXmlNamespaceInput,
    HttpPayloadWithXmlNamespaceOutput,
    HttpPrefixHeadersInput,
    HttpPrefixHeadersOutput,
    HttpRequestWithFloatLabelsInput,
    HttpRequestWithFloatLabelsOutput,
    HttpRequestWithGreedyLabelInPathInput,
    HttpRequestWithGreedyLabelInPathOutput,
    HttpRequestWithLabelsAndTimestampFormatInput,
    HttpRequestWithLabelsAndTimestampFormatOutput,
    HttpRequestWithLabelsInput,
    HttpRequestWithLabelsOutput,
    HttpResponseCodeInput,
    HttpResponseCodeOutput,
    HttpStringPayloadInput,
    HttpStringPayloadOutput,
    IgnoreQueryParamsInResponseInput,
    IgnoreQueryParamsInResponseOutput,
    InputAndOutputWithHeadersInput,
    InputAndOutputWithHeadersOutput,
    NestedXmlMapWithXmlNameInput,
    NestedXmlMapWithXmlNameOutput,
    NestedXmlMapsInput,
    NestedXmlMapsOutput,
    NoInputAndNoOutputInput,
    NoInputAndNoOutputOutput,
    NoInputAndOutputInput,
    NoInputAndOutputOutput,
    NullAndEmptyHeadersClientInput,
    NullAndEmptyHeadersClientOutput,
    NullAndEmptyHeadersServerInput,
    NullAndEmptyHeadersServerOutput,
    OmitsNullSerializesEmptyStringInput,
    OmitsNullSerializesEmptyStringOutput,
    PutWithContentEncodingInput,
    PutWithContentEncodingOutput,
    QueryIdempotencyTokenAutoFillInput,
    QueryIdempotencyTokenAutoFillOutput,
    QueryParamsAsStringListMapInput,
    QueryParamsAsStringListMapOutput,
    QueryPrecedenceInput,
    QueryPrecedenceOutput,
    RecursiveShapesInput,
    RecursiveShapesOutput,
    SimpleScalarPropertiesInput,
    SimpleScalarPropertiesOutput,
    TimestampFormatHeadersInput,
    TimestampFormatHeadersOutput,
    XmlAttributesInMiddleInput,
    XmlAttributesInMiddleOutput,
    XmlAttributesInput,
    XmlAttributesOnPayloadInput,
    XmlAttributesOnPayloadOutput,
    XmlAttributesOutput,
    XmlBlobsInput,
    XmlBlobsOutput,
    XmlEmptyBlobsInput,
    XmlEmptyBlobsOutput,
    XmlEmptyListsInput,
    XmlEmptyListsOutput,
    XmlEmptyMapsInput,
    XmlEmptyMapsOutput,
    XmlEmptyStringsInput,
    XmlEmptyStringsOutput,
    XmlEnumsInput,
    XmlEnumsOutput,
    XmlIntEnumsInput,
    XmlIntEnumsOutput,
    XmlListsInput,
    XmlListsOutput,
    XmlMapWithXmlNamespaceInput,
    XmlMapWithXmlNamespaceOutput,
    XmlMapsInput,
    XmlMapsOutput,
    XmlMapsXmlNameInput,
    XmlMapsXmlNameOutput,
    XmlNamespacesInput,
    XmlNamespacesOutput,
    XmlTimestampsInput,
    XmlTimestampsOutput,
    XmlUnionsInput,
    XmlUnionsOutput,
)


_ServiceInterceptor = Union[
    Interceptor[AllQueryStringTypesInput, AllQueryStringTypesOutput, Any, Any],
    Interceptor[BodyWithXmlNameInput, BodyWithXmlNameOutput, Any, Any],
    Interceptor[
        ConstantAndVariableQueryStringInput,
        ConstantAndVariableQueryStringOutput,
        Any,
        Any,
    ],
    Interceptor[ConstantQueryStringInput, ConstantQueryStringOutput, Any, Any],
    Interceptor[ContentTypeParametersInput, ContentTypeParametersOutput, Any, Any],
    Interceptor[DatetimeOffsetsInput, DatetimeOffsetsOutput, Any, Any],
    Interceptor[
        EmptyInputAndEmptyOutputInput, EmptyInputAndEmptyOutputOutput, Any, Any
    ],
    Interceptor[EndpointOperationInput, EndpointOperationOutput, Any, Any],
    Interceptor[
        EndpointWithHostLabelHeaderOperationInput,
        EndpointWithHostLabelHeaderOperationOutput,
        Any,
        Any,
    ],
    Interceptor[
        EndpointWithHostLabelOperationInput,
        EndpointWithHostLabelOperationOutput,
        Any,
        Any,
    ],
    Interceptor[FlattenedXmlMapInput, FlattenedXmlMapOutput, Any, Any],
    Interceptor[
        FlattenedXmlMapWithXmlNameInput, FlattenedXmlMapWithXmlNameOutput, Any, Any
    ],
    Interceptor[
        FlattenedXmlMapWithXmlNamespaceInput,
        FlattenedXmlMapWithXmlNamespaceOutput,
        Any,
        Any,
    ],
    Interceptor[FractionalSecondsInput, FractionalSecondsOutput, Any, Any],
    Interceptor[GreetingWithErrorsInput, GreetingWithErrorsOutput, Any, Any],
    Interceptor[HttpEmptyPrefixHeadersInput, HttpEmptyPrefixHeadersOutput, Any, Any],
    Interceptor[HttpEnumPayloadInput, HttpEnumPayloadOutput, Any, Any],
    Interceptor[HttpPayloadTraitsInput, HttpPayloadTraitsOutput, Any, Any],
    Interceptor[
        HttpPayloadTraitsWithMediaTypeInput,
        HttpPayloadTraitsWithMediaTypeOutput,
        Any,
        Any,
    ],
    Interceptor[
        HttpPayloadWithMemberXmlNameInput, HttpPayloadWithMemberXmlNameOutput, Any, Any
    ],
    Interceptor[
        HttpPayloadWithStructureInput, HttpPayloadWithStructureOutput, Any, Any
    ],
    Interceptor[HttpPayloadWithUnionInput, HttpPayloadWithUnionOutput, Any, Any],
    Interceptor[HttpPayloadWithXmlNameInput, HttpPayloadWithXmlNameOutput, Any, Any],
    Interceptor[
        HttpPayloadWithXmlNamespaceInput, HttpPayloadWithXmlNamespaceOutput, Any, Any
    ],
    Interceptor[
        HttpPayloadWithXmlNamespaceAndPrefixInput,
        HttpPayloadWithXmlNamespaceAndPrefixOutput,
        Any,
        Any,
    ],
    Interceptor[HttpPrefixHeadersInput, HttpPrefixHeadersOutput, Any, Any],
    Interceptor[
        HttpRequestWithFloatLabelsInput, HttpRequestWithFloatLabelsOutput, Any, Any
    ],
    Interceptor[
        HttpRequestWithGreedyLabelInPathInput,
        HttpRequestWithGreedyLabelInPathOutput,
        Any,
        Any,
    ],
    Interceptor[HttpRequestWithLabelsInput, HttpRequestWithLabelsOutput, Any, Any],
    Interceptor[
        HttpRequestWithLabelsAndTimestampFormatInput,
        HttpRequestWithLabelsAndTimestampFormatOutput,
        Any,
        Any,
    ],
    Interceptor[HttpResponseCodeInput, HttpResponseCodeOutput, Any, Any],
    Interceptor[HttpStringPayloadInput, HttpStringPayloadOutput, Any, Any],
    Interceptor[
        IgnoreQueryParamsInResponseInput, IgnoreQueryParamsInResponseOutput, Any, Any
    ],
    Interceptor[
        InputAndOutputWithHeadersInput, InputAndOutputWithHeadersOutput, Any, Any
    ],
    Interceptor[NestedXmlMapsInput, NestedXmlMapsOutput, Any, Any],
    Interceptor[NestedXmlMapWithXmlNameInput, NestedXmlMapWithXmlNameOutput, Any, Any],
    Interceptor[NoInputAndNoOutputInput, NoInputAndNoOutputOutput, Any, Any],
    Interceptor[NoInputAndOutputInput, NoInputAndOutputOutput, Any, Any],
    Interceptor[
        NullAndEmptyHeadersClientInput, NullAndEmptyHeadersClientOutput, Any, Any
    ],
    Interceptor[
        NullAndEmptyHeadersServerInput, NullAndEmptyHeadersServerOutput, Any, Any
    ],
    Interceptor[
        OmitsNullSerializesEmptyStringInput,
        OmitsNullSerializesEmptyStringOutput,
        Any,
        Any,
    ],
    Interceptor[PutWithContentEncodingInput, PutWithContentEncodingOutput, Any, Any],
    Interceptor[
        QueryIdempotencyTokenAutoFillInput,
        QueryIdempotencyTokenAutoFillOutput,
        Any,
        Any,
    ],
    Interceptor[
        QueryParamsAsStringListMapInput, QueryParamsAsStringListMapOutput, Any, Any
    ],
    Interceptor[QueryPrecedenceInput, QueryPrecedenceOutput, Any, Any],
    Interceptor[RecursiveShapesInput, RecursiveShapesOutput, Any, Any],
    Interceptor[SimpleScalarPropertiesInput, SimpleScalarPropertiesOutput, Any, Any],
    Interceptor[TimestampFormatHeadersInput, TimestampFormatHeadersOutput, Any, Any],
    Interceptor[XmlAttributesInput, XmlAttributesOutput, Any, Any],
    Interceptor[XmlAttributesInMiddleInput, XmlAttributesInMiddleOutput, Any, Any],
    Interceptor[XmlAttributesOnPayloadInput, XmlAttributesOnPayloadOutput, Any, Any],
    Interceptor[XmlBlobsInput, XmlBlobsOutput, Any, Any],
    Interceptor[XmlEmptyBlobsInput, XmlEmptyBlobsOutput, Any, Any],
    Interceptor[XmlEmptyListsInput, XmlEmptyListsOutput, Any, Any],
    Interceptor[XmlEmptyMapsInput, XmlEmptyMapsOutput, Any, Any],
    Interceptor[XmlEmptyStringsInput, XmlEmptyStringsOutput, Any, Any],
    Interceptor[XmlEnumsInput, XmlEnumsOutput, Any, Any],
    Interceptor[XmlIntEnumsInput, XmlIntEnumsOutput, Any, Any],
    Interceptor[XmlListsInput, XmlListsOutput, Any, Any],
    Interceptor[XmlMapsInput, XmlMapsOutput, Any, Any],
    Interceptor[XmlMapsXmlNameInput, XmlMapsXmlNameOutput, Any, Any],
    Interceptor[XmlMapWithXmlNamespaceInput, XmlMapWithXmlNamespaceOutput, Any, Any],
    Interceptor[XmlNamespacesInput, XmlNamespacesOutput, Any, Any],
    Interceptor[XmlTimestampsInput, XmlTimestampsOutput, Any, Any],
    Interceptor[XmlUnionsInput, XmlUnionsOutput, Any, Any],
]
_PROTOCOL_SETTINGS = ProtocolSettings(
    namespace="aws.protocoltests.restxml", service_target="RestXml"
)


class _AsyncRestXmlProtocolConfigOverrides(AwsConfigOverrides, total=False):
    endpoint_resolver: EndpointResolver | None
    protocol: (
        ClientProtocol[Any, Any] | ProtocolConstructor[ClientProtocol[Any, Any]] | None
    )
    auth_schemes: dict[ShapeID, AuthScheme[Any, Any, Any, Any]] | None
    auth_scheme_resolver: AuthSchemeResolver | None


@dataclass(kw_only=True, repr=False, init=False)
class AsyncRestXmlProtocolConfig(AsyncAwsConfig):
    """Rest Xml Protocol configuration (async-resolved)."""

    endpoint_resolver: EndpointResolver | None = None
    """
    The endpoint resolver used to resolve the final endpoint per-operation
    based on the configuration.
    """

    protocol: ClientProtocol[Any, Any] | None = None
    """
    Pass a protocol class reference from smithy_aws_core.aio.protocols to
    select the protocol, e.g. protocol=AwsJson10ClientProtocol. For custom
    protocols a protocol instance may also be passed.
    """

    interceptors: list[_ServiceInterceptor] = field(default_factory=lambda: [])
    """
    The list of interceptors, which are hooks that are called during the
    execution of a request.
    """

    auth_schemes: dict[ShapeID, AuthScheme[Any, Any, Any, Any]] | None = None
    """A map of auth scheme ids to auth schemes."""

    auth_scheme_resolver: AuthSchemeResolver | None = None
    """
    An auth scheme resolver that determines the auth scheme for each
    operation.
    """

    aws_credentials_identity_resolver: (
        IdentityResolver[AWSCredentialsIdentity, AWSIdentityProperties] | None
    ) = None
    """Resolves AWS Credentials. Required for operations that use Sigv4 Auth."""

    region: str | None = None
    """
    The AWS region to connect to. The configured region is used to determine
    the service endpoint.
    """

    aws_access_key_id: str | None = None
    """The identifier for a secret access key."""

    aws_secret_access_key: str | None = None
    """A secret access key that can be used to sign requests."""

    aws_session_token: str | None = None
    """The session token used with temporary AWS credentials."""

    user_agent_extra: str | None = None
    """Additional suffix to be added to the User-Agent header."""

    sdk_ua_app_id: str | None = None
    """
    A unique and opaque application ID that is appended to the User-Agent
    header.
    """

    _FIELDS: ClassVar[dict[str, FieldSpec]] = {
        "aws_credentials_identity_resolver": FieldSpec(default=None),
        "region": FieldSpec(default=None),
        "aws_access_key_id": FieldSpec(default=None),
        "aws_secret_access_key": FieldSpec(default=None),
        "aws_session_token": FieldSpec(default=None),
        "user_agent_extra": FieldSpec(default=None),
        "sdk_ua_app_id": FieldSpec(default=None),
        **AsyncAwsConfig._FIELDS,
        "endpoint_uri": FieldSpec(
            default=None, resolver=EndpointUriResolver("rest_xml_protocol")
        ),
        "endpoint_resolver": FieldSpec(
            default_factory=lambda: StandardRegionalEndpointsResolver(
                endpoint_prefix="restxml"
            )
        ),
        "protocol": FieldSpec(
            default_factory=lambda: RestXmlClientProtocol(_PROTOCOL_SETTINGS),
            converter=lambda p: p(_PROTOCOL_SETTINGS) if isinstance(p, type) else p,
        ),
        "auth_schemes": FieldSpec(
            default_factory=lambda: {
                ShapeID("aws.auth#sigv4"): SigV4AuthScheme(service="restxml")
            }
        ),
        "auth_scheme_resolver": FieldSpec(default_factory=HTTPAuthSchemeResolver),
        "transport": FieldSpec(default_factory=lambda: AIOHTTPClient()),
    }

    def set_auth_scheme(self, scheme: AuthScheme[Any, Any, Any, Any]) -> None:
        """
        Set an auth scheme implementation using its scheme ID. :param scheme:
        The auth scheme to add or replace.
        """
        auth_schemes = dict(self.auth_schemes or {})
        auth_schemes[scheme.scheme_id] = scheme
        self.auth_schemes = auth_schemes

    @classmethod
    async def resolve(  # pyright: ignore[reportIncompatibleMethodOverride]
        cls,
        *,
        profile: str | None = None,
        fs: FileSystem | None = None,
        config_file_path: str | None = None,
        credentials_file_path: str | None = None,
        **overrides: Unpack[_AsyncRestXmlProtocolConfigOverrides],
    ) -> Self:
        """
        Resolve config from environment, config files, defaults, and explicit
        overrides.
        """
        return await cls._resolve(
            profile=profile,
            fs=fs,
            config_file_path=config_file_path,
            credentials_file_path=credentials_file_path,
            overrides=overrides,
        )


Plugin: TypeAlias = Callable[[AsyncRestXmlProtocolConfig], None]
"""
A callable that customizes a client configuration. Service-level plugins
are applied once to the base configuration inherited by every operation.
Operation-level plugins apply only to a single operation invocation.
"""
