# Code generated by smithy-python-codegen DO NOT EDIT.

import asyncio
from copy import deepcopy as _deepcopy
from datetime import datetime
import logging
from typing import Any, Self, cast

from smithy_aws_core.config import ConfigSource
from smithy_aws_core.identity import AWSCredentialsIdentity
from smithy_aws_core.identity.chain import IdentityChain
from smithy_core.aio.client import ClientCall, RequestPipeline
from smithy_core.aio.retries import RetryStrategyResolver
from smithy_core.aio.utils import close
from smithy_core.documents import Document
from smithy_core.exceptions import ExpectationNotMetError
from smithy_core.interceptors import InterceptorChain
from smithy_core.types import JsonString, TypedProperties
from smithy_http.aio.interfaces import HTTPClient
from smithy_http.plugins import user_agent_plugin as _user_agent_plugin

from .config import AsyncJsonProtocolConfig, Plugin
from .models import (
    CONTENT_TYPE_PARAMETERS,
    ContentTypeParametersInput,
    ContentTypeParametersOutput,
    DATETIME_OFFSETS,
    DatetimeOffsetsInput,
    DatetimeOffsetsOutput,
    EMPTY_OPERATION,
    ENDPOINT_OPERATION,
    ENDPOINT_WITH_HOST_LABEL_OPERATION,
    EmptyOperationInput,
    EmptyOperationOutput,
    EmptyStruct,
    EndpointOperationInput,
    EndpointOperationOutput,
    EndpointWithHostLabelOperationInput,
    EndpointWithHostLabelOperationOutput,
    FRACTIONAL_SECONDS,
    FractionalSecondsInput,
    FractionalSecondsOutput,
    GREETING_WITH_ERRORS,
    GreetingWithErrorsInput,
    GreetingWithErrorsOutput,
    HOST_WITH_PATH_OPERATION,
    HostWithPathOperationInput,
    HostWithPathOperationOutput,
    JSON_ENUMS,
    JSON_INT_ENUMS,
    JSON_UNIONS,
    JsonEnumsInput,
    JsonEnumsOutput,
    JsonIntEnumsInput,
    JsonIntEnumsOutput,
    JsonUnionsInput,
    JsonUnionsOutput,
    KITCHEN_SINK_OPERATION,
    KitchenSink,
    KitchenSinkOperationInput,
    KitchenSinkOperationOutput,
    MyUnion,
    NULL_OPERATION,
    NullOperationInput,
    NullOperationOutput,
    OPERATION_WITH_OPTIONAL_INPUT_OUTPUT,
    OperationWithOptionalInputOutputInput,
    OperationWithOptionalInputOutputOutput,
    PUT_AND_GET_INLINE_DOCUMENTS,
    PUT_WITH_CONTENT_ENCODING,
    PutAndGetInlineDocumentsInput,
    PutAndGetInlineDocumentsOutput,
    PutWithContentEncodingInput,
    PutWithContentEncodingOutput,
    SIMPLE_SCALAR_PROPERTIES,
    SPARSE_NULLS_OPERATION,
    SimpleScalarPropertiesInput,
    SimpleScalarPropertiesOutput,
    SimpleStruct,
    SparseNullsOperationInput,
    SparseNullsOperationOutput,
    StructWithJsonName,
)
from .user_agent import aws_user_agent_plugin as _aws_user_agent_plugin


logger = logging.getLogger(__name__)


class AsyncJsonProtocolClient:
    """Client for JsonProtocol"""

    def __init__(
        self,
        config: AsyncJsonProtocolConfig | None = None,
        plugins: list[Plugin] | None = None,
    ):
        """
        Constructor for `AsyncJsonProtocolClient`.

        Args:
            config:
                Optional configuration for the client. Here you can set things like
                the endpoint for HTTP services or auth credentials.
            plugins:
                A list of callables applied once to the client's base configuration.
                Their changes are inherited by every operation invocation.
        """
        self._config = config
        self._plugins = plugins
        self._derive_lock = asyncio.Lock()
        self._setup_done = False
        self._closed = False
        self._retry_strategy_resolver = RetryStrategyResolver()
        self._client_plugins: list[Plugin] = [
            _aws_user_agent_plugin,
            _user_agent_plugin,
        ]

    async def _ensure_setup(self) -> None:
        if not self._setup_done:
            async with self._derive_lock:
                if not self._setup_done:
                    if self._config is None:
                        config = await AsyncJsonProtocolConfig.resolve()
                    else:
                        # Copy so plugins don't mutate the caller's config.
                        config = _deepcopy(self._config)
                    for plugin in self._client_plugins:
                        plugin(config)
                    if self._plugins:
                        for plugin in self._plugins:
                            plugin(config)
                    self._config = config

                    if self._config.aws_credentials_identity_resolver is None:
                        config_context = self._config.resolution_context()
                        config_file = None
                        profile_name = None
                        if config_context is not None:
                            config_file = await config_context.parsed_profiles()
                            if config_context.profile_source is ConfigSource.OVERRIDE:
                                profile_name = config_context.profile_name
                        self._config.aws_credentials_identity_resolver = (
                            await IdentityChain.create(
                                AWSCredentialsIdentity,
                                config_file=config_file,
                                profile_name=profile_name,
                                region_override=self._config.region,
                                http_client=cast(
                                    HTTPClient | None, self._config.transport
                                ),
                            )
                        )
                    self._setup_done = True

    async def close(self) -> None:
        """Close this client and any resources held by its transport."""
        if self._closed:
            return
        async with self._derive_lock:
            if self._closed:
                return
            self._closed = True
            if self._setup_done and self._config is not None:
                await close(self._config.transport)

    async def __aenter__(self) -> Self:
        if self._closed:
            raise RuntimeError("Cannot enter a client that has been closed.")
        return self

    async def __aexit__(self, exc_type: Any, exc_value: Any, traceback: Any) -> None:
        await self.close()

    async def content_type_parameters(
        self, *, value: int | None = None, plugins: list[Plugin] | None = None
    ) -> ContentTypeParametersOutput:
        """
        The example tests how servers must support requests containing a
        `Content-Type` header with parameters.

        Args:
            plugins:
                A list of callables that modify the configuration dynamically.
                Changes made by these plugins only apply for the duration of the
                operation execution and will not affect any other operation
                invocations.

        Returns:
            An instance of `ContentTypeParametersOutput`.
        """
        if self._closed:
            raise RuntimeError(
                "Cannot invoke an operation on a client that has been closed."
            )

        _input = ContentTypeParametersInput(value=value)
        _operation_plugins: list[Plugin] = []
        if plugins:
            _operation_plugins.extend(plugins)
        await self._ensure_setup()
        assert self._config is not None
        if _operation_plugins:
            # Keep operation-plugin mutations scoped to this call.
            _config = _deepcopy(self._config)
            for _plugin in _operation_plugins:
                _plugin(_config)
        else:
            _config = self._config
        if (
            _config.protocol is None
            or _config.transport is None
            or _config.endpoint_resolver is None
            or _config.auth_scheme_resolver is None
            or _config.auth_schemes is None
        ):
            raise ExpectationNotMetError(
                "protocol, transport, endpoint_resolver, auth_scheme_resolver,"
                " and auth_schemes MUST be set on the config to make calls."
            )

        _retry_strategy = await self._retry_strategy_resolver.resolve_retry_strategy(
            retry_strategy=_config.retry_strategy,
            retry_mode=_config.retry_mode,
            max_attempts=_config.max_attempts,
        )

        _pipeline = RequestPipeline(
            protocol=_config.protocol, transport=_config.transport
        )
        _call = ClientCall(
            input=_input,
            operation=CONTENT_TYPE_PARAMETERS,
            context=TypedProperties({"config": _config}),
            interceptor=InterceptorChain(_config.interceptors),
            auth_scheme_resolver=_config.auth_scheme_resolver,
            supported_auth_schemes=_config.auth_schemes,
            endpoint_resolver=_config.endpoint_resolver,
            retry_strategy=_retry_strategy,
        )

        return await _pipeline(_call)

    async def datetime_offsets(
        self, *, plugins: list[Plugin] | None = None
    ) -> DatetimeOffsetsOutput:
        """
        Invokes the DatetimeOffsets operation.

        Args:
            plugins:
                A list of callables that modify the configuration dynamically.
                Changes made by these plugins only apply for the duration of the
                operation execution and will not affect any other operation
                invocations.

        Returns:
            An instance of `DatetimeOffsetsOutput`.
        """
        if self._closed:
            raise RuntimeError(
                "Cannot invoke an operation on a client that has been closed."
            )

        _input = DatetimeOffsetsInput()
        _operation_plugins: list[Plugin] = []
        if plugins:
            _operation_plugins.extend(plugins)
        await self._ensure_setup()
        assert self._config is not None
        if _operation_plugins:
            # Keep operation-plugin mutations scoped to this call.
            _config = _deepcopy(self._config)
            for _plugin in _operation_plugins:
                _plugin(_config)
        else:
            _config = self._config
        if (
            _config.protocol is None
            or _config.transport is None
            or _config.endpoint_resolver is None
            or _config.auth_scheme_resolver is None
            or _config.auth_schemes is None
        ):
            raise ExpectationNotMetError(
                "protocol, transport, endpoint_resolver, auth_scheme_resolver,"
                " and auth_schemes MUST be set on the config to make calls."
            )

        _retry_strategy = await self._retry_strategy_resolver.resolve_retry_strategy(
            retry_strategy=_config.retry_strategy,
            retry_mode=_config.retry_mode,
            max_attempts=_config.max_attempts,
        )

        _pipeline = RequestPipeline(
            protocol=_config.protocol, transport=_config.transport
        )
        _call = ClientCall(
            input=_input,
            operation=DATETIME_OFFSETS,
            context=TypedProperties({"config": _config}),
            interceptor=InterceptorChain(_config.interceptors),
            auth_scheme_resolver=_config.auth_scheme_resolver,
            supported_auth_schemes=_config.auth_schemes,
            endpoint_resolver=_config.endpoint_resolver,
            retry_strategy=_retry_strategy,
        )

        return await _pipeline(_call)

    async def empty_operation(
        self, *, plugins: list[Plugin] | None = None
    ) -> EmptyOperationOutput:
        """
        Invokes the EmptyOperation operation.

        Args:
            plugins:
                A list of callables that modify the configuration dynamically.
                Changes made by these plugins only apply for the duration of the
                operation execution and will not affect any other operation
                invocations.

        Returns:
            An instance of `EmptyOperationOutput`.
        """
        if self._closed:
            raise RuntimeError(
                "Cannot invoke an operation on a client that has been closed."
            )

        _input = EmptyOperationInput()
        _operation_plugins: list[Plugin] = []
        if plugins:
            _operation_plugins.extend(plugins)
        await self._ensure_setup()
        assert self._config is not None
        if _operation_plugins:
            # Keep operation-plugin mutations scoped to this call.
            _config = _deepcopy(self._config)
            for _plugin in _operation_plugins:
                _plugin(_config)
        else:
            _config = self._config
        if (
            _config.protocol is None
            or _config.transport is None
            or _config.endpoint_resolver is None
            or _config.auth_scheme_resolver is None
            or _config.auth_schemes is None
        ):
            raise ExpectationNotMetError(
                "protocol, transport, endpoint_resolver, auth_scheme_resolver,"
                " and auth_schemes MUST be set on the config to make calls."
            )

        _retry_strategy = await self._retry_strategy_resolver.resolve_retry_strategy(
            retry_strategy=_config.retry_strategy,
            retry_mode=_config.retry_mode,
            max_attempts=_config.max_attempts,
        )

        _pipeline = RequestPipeline(
            protocol=_config.protocol, transport=_config.transport
        )
        _call = ClientCall(
            input=_input,
            operation=EMPTY_OPERATION,
            context=TypedProperties({"config": _config}),
            interceptor=InterceptorChain(_config.interceptors),
            auth_scheme_resolver=_config.auth_scheme_resolver,
            supported_auth_schemes=_config.auth_schemes,
            endpoint_resolver=_config.endpoint_resolver,
            retry_strategy=_retry_strategy,
        )

        return await _pipeline(_call)

    async def endpoint_operation(
        self, *, plugins: list[Plugin] | None = None
    ) -> EndpointOperationOutput:
        """
        Invokes the EndpointOperation operation.

        Args:
            plugins:
                A list of callables that modify the configuration dynamically.
                Changes made by these plugins only apply for the duration of the
                operation execution and will not affect any other operation
                invocations.

        Returns:
            An instance of `EndpointOperationOutput`.
        """
        if self._closed:
            raise RuntimeError(
                "Cannot invoke an operation on a client that has been closed."
            )

        _input = EndpointOperationInput()
        _operation_plugins: list[Plugin] = []
        if plugins:
            _operation_plugins.extend(plugins)
        await self._ensure_setup()
        assert self._config is not None
        if _operation_plugins:
            # Keep operation-plugin mutations scoped to this call.
            _config = _deepcopy(self._config)
            for _plugin in _operation_plugins:
                _plugin(_config)
        else:
            _config = self._config
        if (
            _config.protocol is None
            or _config.transport is None
            or _config.endpoint_resolver is None
            or _config.auth_scheme_resolver is None
            or _config.auth_schemes is None
        ):
            raise ExpectationNotMetError(
                "protocol, transport, endpoint_resolver, auth_scheme_resolver,"
                " and auth_schemes MUST be set on the config to make calls."
            )

        _retry_strategy = await self._retry_strategy_resolver.resolve_retry_strategy(
            retry_strategy=_config.retry_strategy,
            retry_mode=_config.retry_mode,
            max_attempts=_config.max_attempts,
        )

        _pipeline = RequestPipeline(
            protocol=_config.protocol, transport=_config.transport
        )
        _call = ClientCall(
            input=_input,
            operation=ENDPOINT_OPERATION,
            context=TypedProperties({"config": _config}),
            interceptor=InterceptorChain(_config.interceptors),
            auth_scheme_resolver=_config.auth_scheme_resolver,
            supported_auth_schemes=_config.auth_schemes,
            endpoint_resolver=_config.endpoint_resolver,
            retry_strategy=_retry_strategy,
        )

        return await _pipeline(_call)

    async def endpoint_with_host_label_operation(
        self, *, label: str | None = None, plugins: list[Plugin] | None = None
    ) -> EndpointWithHostLabelOperationOutput:
        """
        Invokes the EndpointWithHostLabelOperation operation.

        Args:
            plugins:
                A list of callables that modify the configuration dynamically.
                Changes made by these plugins only apply for the duration of the
                operation execution and will not affect any other operation
                invocations.

        Returns:
            An instance of `EndpointWithHostLabelOperationOutput`.
        """
        if self._closed:
            raise RuntimeError(
                "Cannot invoke an operation on a client that has been closed."
            )

        _input = EndpointWithHostLabelOperationInput(label=label)
        _operation_plugins: list[Plugin] = []
        if plugins:
            _operation_plugins.extend(plugins)
        await self._ensure_setup()
        assert self._config is not None
        if _operation_plugins:
            # Keep operation-plugin mutations scoped to this call.
            _config = _deepcopy(self._config)
            for _plugin in _operation_plugins:
                _plugin(_config)
        else:
            _config = self._config
        if (
            _config.protocol is None
            or _config.transport is None
            or _config.endpoint_resolver is None
            or _config.auth_scheme_resolver is None
            or _config.auth_schemes is None
        ):
            raise ExpectationNotMetError(
                "protocol, transport, endpoint_resolver, auth_scheme_resolver,"
                " and auth_schemes MUST be set on the config to make calls."
            )

        _retry_strategy = await self._retry_strategy_resolver.resolve_retry_strategy(
            retry_strategy=_config.retry_strategy,
            retry_mode=_config.retry_mode,
            max_attempts=_config.max_attempts,
        )

        _pipeline = RequestPipeline(
            protocol=_config.protocol, transport=_config.transport
        )
        _call = ClientCall(
            input=_input,
            operation=ENDPOINT_WITH_HOST_LABEL_OPERATION,
            context=TypedProperties({"config": _config}),
            interceptor=InterceptorChain(_config.interceptors),
            auth_scheme_resolver=_config.auth_scheme_resolver,
            supported_auth_schemes=_config.auth_schemes,
            endpoint_resolver=_config.endpoint_resolver,
            retry_strategy=_retry_strategy,
        )

        return await _pipeline(_call)

    async def fractional_seconds(
        self, *, plugins: list[Plugin] | None = None
    ) -> FractionalSecondsOutput:
        """
        Invokes the FractionalSeconds operation.

        Args:
            plugins:
                A list of callables that modify the configuration dynamically.
                Changes made by these plugins only apply for the duration of the
                operation execution and will not affect any other operation
                invocations.

        Returns:
            An instance of `FractionalSecondsOutput`.
        """
        if self._closed:
            raise RuntimeError(
                "Cannot invoke an operation on a client that has been closed."
            )

        _input = FractionalSecondsInput()
        _operation_plugins: list[Plugin] = []
        if plugins:
            _operation_plugins.extend(plugins)
        await self._ensure_setup()
        assert self._config is not None
        if _operation_plugins:
            # Keep operation-plugin mutations scoped to this call.
            _config = _deepcopy(self._config)
            for _plugin in _operation_plugins:
                _plugin(_config)
        else:
            _config = self._config
        if (
            _config.protocol is None
            or _config.transport is None
            or _config.endpoint_resolver is None
            or _config.auth_scheme_resolver is None
            or _config.auth_schemes is None
        ):
            raise ExpectationNotMetError(
                "protocol, transport, endpoint_resolver, auth_scheme_resolver,"
                " and auth_schemes MUST be set on the config to make calls."
            )

        _retry_strategy = await self._retry_strategy_resolver.resolve_retry_strategy(
            retry_strategy=_config.retry_strategy,
            retry_mode=_config.retry_mode,
            max_attempts=_config.max_attempts,
        )

        _pipeline = RequestPipeline(
            protocol=_config.protocol, transport=_config.transport
        )
        _call = ClientCall(
            input=_input,
            operation=FRACTIONAL_SECONDS,
            context=TypedProperties({"config": _config}),
            interceptor=InterceptorChain(_config.interceptors),
            auth_scheme_resolver=_config.auth_scheme_resolver,
            supported_auth_schemes=_config.auth_schemes,
            endpoint_resolver=_config.endpoint_resolver,
            retry_strategy=_retry_strategy,
        )

        return await _pipeline(_call)

    async def greeting_with_errors(
        self, *, plugins: list[Plugin] | None = None
    ) -> GreetingWithErrorsOutput:
        """
        This operation has three possible return values: 1. A successful
        response in the form of GreetingWithErrorsOutput 2. An InvalidGreeting
        error. 3. A ComplexError error. Implementations must be able to
        successfully take a response and properly deserialize successful and
        error responses.

        Args:
            plugins:
                A list of callables that modify the configuration dynamically.
                Changes made by these plugins only apply for the duration of the
                operation execution and will not affect any other operation
                invocations.

        Returns:
            An instance of `GreetingWithErrorsOutput`.
        """
        if self._closed:
            raise RuntimeError(
                "Cannot invoke an operation on a client that has been closed."
            )

        _input = GreetingWithErrorsInput()
        _operation_plugins: list[Plugin] = []
        if plugins:
            _operation_plugins.extend(plugins)
        await self._ensure_setup()
        assert self._config is not None
        if _operation_plugins:
            # Keep operation-plugin mutations scoped to this call.
            _config = _deepcopy(self._config)
            for _plugin in _operation_plugins:
                _plugin(_config)
        else:
            _config = self._config
        if (
            _config.protocol is None
            or _config.transport is None
            or _config.endpoint_resolver is None
            or _config.auth_scheme_resolver is None
            or _config.auth_schemes is None
        ):
            raise ExpectationNotMetError(
                "protocol, transport, endpoint_resolver, auth_scheme_resolver,"
                " and auth_schemes MUST be set on the config to make calls."
            )

        _retry_strategy = await self._retry_strategy_resolver.resolve_retry_strategy(
            retry_strategy=_config.retry_strategy,
            retry_mode=_config.retry_mode,
            max_attempts=_config.max_attempts,
        )

        _pipeline = RequestPipeline(
            protocol=_config.protocol, transport=_config.transport
        )
        _call = ClientCall(
            input=_input,
            operation=GREETING_WITH_ERRORS,
            context=TypedProperties({"config": _config}),
            interceptor=InterceptorChain(_config.interceptors),
            auth_scheme_resolver=_config.auth_scheme_resolver,
            supported_auth_schemes=_config.auth_schemes,
            endpoint_resolver=_config.endpoint_resolver,
            retry_strategy=_retry_strategy,
        )

        return await _pipeline(_call)

    async def host_with_path_operation(
        self, *, plugins: list[Plugin] | None = None
    ) -> HostWithPathOperationOutput:
        """
        Invokes the HostWithPathOperation operation.

        Args:
            plugins:
                A list of callables that modify the configuration dynamically.
                Changes made by these plugins only apply for the duration of the
                operation execution and will not affect any other operation
                invocations.

        Returns:
            An instance of `HostWithPathOperationOutput`.
        """
        if self._closed:
            raise RuntimeError(
                "Cannot invoke an operation on a client that has been closed."
            )

        _input = HostWithPathOperationInput()
        _operation_plugins: list[Plugin] = []
        if plugins:
            _operation_plugins.extend(plugins)
        await self._ensure_setup()
        assert self._config is not None
        if _operation_plugins:
            # Keep operation-plugin mutations scoped to this call.
            _config = _deepcopy(self._config)
            for _plugin in _operation_plugins:
                _plugin(_config)
        else:
            _config = self._config
        if (
            _config.protocol is None
            or _config.transport is None
            or _config.endpoint_resolver is None
            or _config.auth_scheme_resolver is None
            or _config.auth_schemes is None
        ):
            raise ExpectationNotMetError(
                "protocol, transport, endpoint_resolver, auth_scheme_resolver,"
                " and auth_schemes MUST be set on the config to make calls."
            )

        _retry_strategy = await self._retry_strategy_resolver.resolve_retry_strategy(
            retry_strategy=_config.retry_strategy,
            retry_mode=_config.retry_mode,
            max_attempts=_config.max_attempts,
        )

        _pipeline = RequestPipeline(
            protocol=_config.protocol, transport=_config.transport
        )
        _call = ClientCall(
            input=_input,
            operation=HOST_WITH_PATH_OPERATION,
            context=TypedProperties({"config": _config}),
            interceptor=InterceptorChain(_config.interceptors),
            auth_scheme_resolver=_config.auth_scheme_resolver,
            supported_auth_schemes=_config.auth_schemes,
            endpoint_resolver=_config.endpoint_resolver,
            retry_strategy=_retry_strategy,
        )

        return await _pipeline(_call)

    async def json_enums(
        self,
        *,
        foo_enum1: str | None = None,
        foo_enum2: str | None = None,
        foo_enum3: str | None = None,
        foo_enum_list: list[str] | None = None,
        foo_enum_set: list[str] | None = None,
        foo_enum_map: dict[str, str] | None = None,
        plugins: list[Plugin] | None = None,
    ) -> JsonEnumsOutput:
        """
        This example serializes enums as top level properties, in lists, sets,
        and maps.

        Args:
            plugins:
                A list of callables that modify the configuration dynamically.
                Changes made by these plugins only apply for the duration of the
                operation execution and will not affect any other operation
                invocations.

        Returns:
            An instance of `JsonEnumsOutput`.
        """
        if self._closed:
            raise RuntimeError(
                "Cannot invoke an operation on a client that has been closed."
            )

        _input = JsonEnumsInput(
            foo_enum1=foo_enum1,
            foo_enum2=foo_enum2,
            foo_enum3=foo_enum3,
            foo_enum_list=foo_enum_list,
            foo_enum_set=foo_enum_set,
            foo_enum_map=foo_enum_map,
        )
        _operation_plugins: list[Plugin] = []
        if plugins:
            _operation_plugins.extend(plugins)
        await self._ensure_setup()
        assert self._config is not None
        if _operation_plugins:
            # Keep operation-plugin mutations scoped to this call.
            _config = _deepcopy(self._config)
            for _plugin in _operation_plugins:
                _plugin(_config)
        else:
            _config = self._config
        if (
            _config.protocol is None
            or _config.transport is None
            or _config.endpoint_resolver is None
            or _config.auth_scheme_resolver is None
            or _config.auth_schemes is None
        ):
            raise ExpectationNotMetError(
                "protocol, transport, endpoint_resolver, auth_scheme_resolver,"
                " and auth_schemes MUST be set on the config to make calls."
            )

        _retry_strategy = await self._retry_strategy_resolver.resolve_retry_strategy(
            retry_strategy=_config.retry_strategy,
            retry_mode=_config.retry_mode,
            max_attempts=_config.max_attempts,
        )

        _pipeline = RequestPipeline(
            protocol=_config.protocol, transport=_config.transport
        )
        _call = ClientCall(
            input=_input,
            operation=JSON_ENUMS,
            context=TypedProperties({"config": _config}),
            interceptor=InterceptorChain(_config.interceptors),
            auth_scheme_resolver=_config.auth_scheme_resolver,
            supported_auth_schemes=_config.auth_schemes,
            endpoint_resolver=_config.endpoint_resolver,
            retry_strategy=_retry_strategy,
        )

        return await _pipeline(_call)

    async def json_int_enums(
        self,
        *,
        int_enum1: int | None = None,
        int_enum2: int | None = None,
        int_enum3: int | None = None,
        int_enum_list: list[int] | None = None,
        int_enum_set: list[int] | None = None,
        int_enum_map: dict[str, int] | None = None,
        plugins: list[Plugin] | None = None,
    ) -> JsonIntEnumsOutput:
        """
        This example serializes intEnums as top level properties, in lists,
        sets, and maps.

        Args:
            plugins:
                A list of callables that modify the configuration dynamically.
                Changes made by these plugins only apply for the duration of the
                operation execution and will not affect any other operation
                invocations.

        Returns:
            An instance of `JsonIntEnumsOutput`.
        """
        if self._closed:
            raise RuntimeError(
                "Cannot invoke an operation on a client that has been closed."
            )

        _input = JsonIntEnumsInput(
            int_enum1=int_enum1,
            int_enum2=int_enum2,
            int_enum3=int_enum3,
            int_enum_list=int_enum_list,
            int_enum_set=int_enum_set,
            int_enum_map=int_enum_map,
        )
        _operation_plugins: list[Plugin] = []
        if plugins:
            _operation_plugins.extend(plugins)
        await self._ensure_setup()
        assert self._config is not None
        if _operation_plugins:
            # Keep operation-plugin mutations scoped to this call.
            _config = _deepcopy(self._config)
            for _plugin in _operation_plugins:
                _plugin(_config)
        else:
            _config = self._config
        if (
            _config.protocol is None
            or _config.transport is None
            or _config.endpoint_resolver is None
            or _config.auth_scheme_resolver is None
            or _config.auth_schemes is None
        ):
            raise ExpectationNotMetError(
                "protocol, transport, endpoint_resolver, auth_scheme_resolver,"
                " and auth_schemes MUST be set on the config to make calls."
            )

        _retry_strategy = await self._retry_strategy_resolver.resolve_retry_strategy(
            retry_strategy=_config.retry_strategy,
            retry_mode=_config.retry_mode,
            max_attempts=_config.max_attempts,
        )

        _pipeline = RequestPipeline(
            protocol=_config.protocol, transport=_config.transport
        )
        _call = ClientCall(
            input=_input,
            operation=JSON_INT_ENUMS,
            context=TypedProperties({"config": _config}),
            interceptor=InterceptorChain(_config.interceptors),
            auth_scheme_resolver=_config.auth_scheme_resolver,
            supported_auth_schemes=_config.auth_schemes,
            endpoint_resolver=_config.endpoint_resolver,
            retry_strategy=_retry_strategy,
        )

        return await _pipeline(_call)

    async def json_unions(
        self, *, contents: MyUnion | None = None, plugins: list[Plugin] | None = None
    ) -> JsonUnionsOutput:
        """
        This operation uses unions for inputs and outputs.

        Args:
            contents:
                A union with a representative set of types for members.
            plugins:
                A list of callables that modify the configuration dynamically.
                Changes made by these plugins only apply for the duration of the
                operation execution and will not affect any other operation
                invocations.

        Returns:
            An instance of `JsonUnionsOutput`.
        """
        if self._closed:
            raise RuntimeError(
                "Cannot invoke an operation on a client that has been closed."
            )

        _input = JsonUnionsInput(contents=contents)
        _operation_plugins: list[Plugin] = []
        if plugins:
            _operation_plugins.extend(plugins)
        await self._ensure_setup()
        assert self._config is not None
        if _operation_plugins:
            # Keep operation-plugin mutations scoped to this call.
            _config = _deepcopy(self._config)
            for _plugin in _operation_plugins:
                _plugin(_config)
        else:
            _config = self._config
        if (
            _config.protocol is None
            or _config.transport is None
            or _config.endpoint_resolver is None
            or _config.auth_scheme_resolver is None
            or _config.auth_schemes is None
        ):
            raise ExpectationNotMetError(
                "protocol, transport, endpoint_resolver, auth_scheme_resolver,"
                " and auth_schemes MUST be set on the config to make calls."
            )

        _retry_strategy = await self._retry_strategy_resolver.resolve_retry_strategy(
            retry_strategy=_config.retry_strategy,
            retry_mode=_config.retry_mode,
            max_attempts=_config.max_attempts,
        )

        _pipeline = RequestPipeline(
            protocol=_config.protocol, transport=_config.transport
        )
        _call = ClientCall(
            input=_input,
            operation=JSON_UNIONS,
            context=TypedProperties({"config": _config}),
            interceptor=InterceptorChain(_config.interceptors),
            auth_scheme_resolver=_config.auth_scheme_resolver,
            supported_auth_schemes=_config.auth_schemes,
            endpoint_resolver=_config.endpoint_resolver,
            retry_strategy=_retry_strategy,
        )

        return await _pipeline(_call)

    async def kitchen_sink_operation(
        self,
        *,
        blob: bytes | None = None,
        boolean: bool | None = None,
        double: float | None = None,
        empty_struct: EmptyStruct | None = None,
        float_: float | None = None,
        httpdate_timestamp: datetime | None = None,
        integer: int | None = None,
        iso8601_timestamp: datetime | None = None,
        json_value: str | JsonString | None = None,
        list_of_lists: list[list[str]] | None = None,
        list_of_maps_of_strings: list[dict[str, str]] | None = None,
        list_of_strings: list[str] | None = None,
        list_of_structs: list[SimpleStruct] | None = None,
        long: int | None = None,
        map_of_lists_of_strings: dict[str, list[str]] | None = None,
        map_of_maps: dict[str, dict[str, str]] | None = None,
        map_of_strings: dict[str, str] | None = None,
        map_of_structs: dict[str, SimpleStruct] | None = None,
        recursive_list: list[KitchenSink] | None = None,
        recursive_map: dict[str, KitchenSink] | None = None,
        recursive_struct: KitchenSink | None = None,
        simple_struct: SimpleStruct | None = None,
        string: str | None = None,
        struct_with_json_name: StructWithJsonName | None = None,
        timestamp: datetime | None = None,
        unix_timestamp: datetime | None = None,
        plugins: list[Plugin] | None = None,
    ) -> KitchenSinkOperationOutput:
        """
        Invokes the KitchenSinkOperation operation.

        Args:
            plugins:
                A list of callables that modify the configuration dynamically.
                Changes made by these plugins only apply for the duration of the
                operation execution and will not affect any other operation
                invocations.

        Returns:
            An instance of `KitchenSinkOperationOutput`.
        """
        if self._closed:
            raise RuntimeError(
                "Cannot invoke an operation on a client that has been closed."
            )

        _input = KitchenSinkOperationInput(
            blob=blob,
            boolean=boolean,
            double=double,
            empty_struct=empty_struct,
            float_=float_,
            httpdate_timestamp=httpdate_timestamp,
            integer=integer,
            iso8601_timestamp=iso8601_timestamp,
            json_value=json_value,
            list_of_lists=list_of_lists,
            list_of_maps_of_strings=list_of_maps_of_strings,
            list_of_strings=list_of_strings,
            list_of_structs=list_of_structs,
            long=long,
            map_of_lists_of_strings=map_of_lists_of_strings,
            map_of_maps=map_of_maps,
            map_of_strings=map_of_strings,
            map_of_structs=map_of_structs,
            recursive_list=recursive_list,
            recursive_map=recursive_map,
            recursive_struct=recursive_struct,
            simple_struct=simple_struct,
            string=string,
            struct_with_json_name=struct_with_json_name,
            timestamp=timestamp,
            unix_timestamp=unix_timestamp,
        )
        _operation_plugins: list[Plugin] = []
        if plugins:
            _operation_plugins.extend(plugins)
        await self._ensure_setup()
        assert self._config is not None
        if _operation_plugins:
            # Keep operation-plugin mutations scoped to this call.
            _config = _deepcopy(self._config)
            for _plugin in _operation_plugins:
                _plugin(_config)
        else:
            _config = self._config
        if (
            _config.protocol is None
            or _config.transport is None
            or _config.endpoint_resolver is None
            or _config.auth_scheme_resolver is None
            or _config.auth_schemes is None
        ):
            raise ExpectationNotMetError(
                "protocol, transport, endpoint_resolver, auth_scheme_resolver,"
                " and auth_schemes MUST be set on the config to make calls."
            )

        _retry_strategy = await self._retry_strategy_resolver.resolve_retry_strategy(
            retry_strategy=_config.retry_strategy,
            retry_mode=_config.retry_mode,
            max_attempts=_config.max_attempts,
        )

        _pipeline = RequestPipeline(
            protocol=_config.protocol, transport=_config.transport
        )
        _call = ClientCall(
            input=_input,
            operation=KITCHEN_SINK_OPERATION,
            context=TypedProperties({"config": _config}),
            interceptor=InterceptorChain(_config.interceptors),
            auth_scheme_resolver=_config.auth_scheme_resolver,
            supported_auth_schemes=_config.auth_schemes,
            endpoint_resolver=_config.endpoint_resolver,
            retry_strategy=_retry_strategy,
        )

        return await _pipeline(_call)

    async def null_operation(
        self, *, string: str | None = None, plugins: list[Plugin] | None = None
    ) -> NullOperationOutput:
        """
        Invokes the NullOperation operation.

        Args:
            plugins:
                A list of callables that modify the configuration dynamically.
                Changes made by these plugins only apply for the duration of the
                operation execution and will not affect any other operation
                invocations.

        Returns:
            An instance of `NullOperationOutput`.
        """
        if self._closed:
            raise RuntimeError(
                "Cannot invoke an operation on a client that has been closed."
            )

        _input = NullOperationInput(string=string)
        _operation_plugins: list[Plugin] = []
        if plugins:
            _operation_plugins.extend(plugins)
        await self._ensure_setup()
        assert self._config is not None
        if _operation_plugins:
            # Keep operation-plugin mutations scoped to this call.
            _config = _deepcopy(self._config)
            for _plugin in _operation_plugins:
                _plugin(_config)
        else:
            _config = self._config
        if (
            _config.protocol is None
            or _config.transport is None
            or _config.endpoint_resolver is None
            or _config.auth_scheme_resolver is None
            or _config.auth_schemes is None
        ):
            raise ExpectationNotMetError(
                "protocol, transport, endpoint_resolver, auth_scheme_resolver,"
                " and auth_schemes MUST be set on the config to make calls."
            )

        _retry_strategy = await self._retry_strategy_resolver.resolve_retry_strategy(
            retry_strategy=_config.retry_strategy,
            retry_mode=_config.retry_mode,
            max_attempts=_config.max_attempts,
        )

        _pipeline = RequestPipeline(
            protocol=_config.protocol, transport=_config.transport
        )
        _call = ClientCall(
            input=_input,
            operation=NULL_OPERATION,
            context=TypedProperties({"config": _config}),
            interceptor=InterceptorChain(_config.interceptors),
            auth_scheme_resolver=_config.auth_scheme_resolver,
            supported_auth_schemes=_config.auth_schemes,
            endpoint_resolver=_config.endpoint_resolver,
            retry_strategy=_retry_strategy,
        )

        return await _pipeline(_call)

    async def operation_with_optional_input_output(
        self, *, value: str | None = None, plugins: list[Plugin] | None = None
    ) -> OperationWithOptionalInputOutputOutput:
        """
        Invokes the OperationWithOptionalInputOutput operation.

        Args:
            plugins:
                A list of callables that modify the configuration dynamically.
                Changes made by these plugins only apply for the duration of the
                operation execution and will not affect any other operation
                invocations.

        Returns:
            An instance of `OperationWithOptionalInputOutputOutput`.
        """
        if self._closed:
            raise RuntimeError(
                "Cannot invoke an operation on a client that has been closed."
            )

        _input = OperationWithOptionalInputOutputInput(value=value)
        _operation_plugins: list[Plugin] = []
        if plugins:
            _operation_plugins.extend(plugins)
        await self._ensure_setup()
        assert self._config is not None
        if _operation_plugins:
            # Keep operation-plugin mutations scoped to this call.
            _config = _deepcopy(self._config)
            for _plugin in _operation_plugins:
                _plugin(_config)
        else:
            _config = self._config
        if (
            _config.protocol is None
            or _config.transport is None
            or _config.endpoint_resolver is None
            or _config.auth_scheme_resolver is None
            or _config.auth_schemes is None
        ):
            raise ExpectationNotMetError(
                "protocol, transport, endpoint_resolver, auth_scheme_resolver,"
                " and auth_schemes MUST be set on the config to make calls."
            )

        _retry_strategy = await self._retry_strategy_resolver.resolve_retry_strategy(
            retry_strategy=_config.retry_strategy,
            retry_mode=_config.retry_mode,
            max_attempts=_config.max_attempts,
        )

        _pipeline = RequestPipeline(
            protocol=_config.protocol, transport=_config.transport
        )
        _call = ClientCall(
            input=_input,
            operation=OPERATION_WITH_OPTIONAL_INPUT_OUTPUT,
            context=TypedProperties({"config": _config}),
            interceptor=InterceptorChain(_config.interceptors),
            auth_scheme_resolver=_config.auth_scheme_resolver,
            supported_auth_schemes=_config.auth_schemes,
            endpoint_resolver=_config.endpoint_resolver,
            retry_strategy=_retry_strategy,
        )

        return await _pipeline(_call)

    async def put_and_get_inline_documents(
        self,
        *,
        inline_document: Document | None = None,
        plugins: list[Plugin] | None = None,
    ) -> PutAndGetInlineDocumentsOutput:
        """
        This example serializes an inline document as part of the payload.

        Args:
            plugins:
                A list of callables that modify the configuration dynamically.
                Changes made by these plugins only apply for the duration of the
                operation execution and will not affect any other operation
                invocations.

        Returns:
            An instance of `PutAndGetInlineDocumentsOutput`.
        """
        if self._closed:
            raise RuntimeError(
                "Cannot invoke an operation on a client that has been closed."
            )

        _input = PutAndGetInlineDocumentsInput(inline_document=inline_document)
        _operation_plugins: list[Plugin] = []
        if plugins:
            _operation_plugins.extend(plugins)
        await self._ensure_setup()
        assert self._config is not None
        if _operation_plugins:
            # Keep operation-plugin mutations scoped to this call.
            _config = _deepcopy(self._config)
            for _plugin in _operation_plugins:
                _plugin(_config)
        else:
            _config = self._config
        if (
            _config.protocol is None
            or _config.transport is None
            or _config.endpoint_resolver is None
            or _config.auth_scheme_resolver is None
            or _config.auth_schemes is None
        ):
            raise ExpectationNotMetError(
                "protocol, transport, endpoint_resolver, auth_scheme_resolver,"
                " and auth_schemes MUST be set on the config to make calls."
            )

        _retry_strategy = await self._retry_strategy_resolver.resolve_retry_strategy(
            retry_strategy=_config.retry_strategy,
            retry_mode=_config.retry_mode,
            max_attempts=_config.max_attempts,
        )

        _pipeline = RequestPipeline(
            protocol=_config.protocol, transport=_config.transport
        )
        _call = ClientCall(
            input=_input,
            operation=PUT_AND_GET_INLINE_DOCUMENTS,
            context=TypedProperties({"config": _config}),
            interceptor=InterceptorChain(_config.interceptors),
            auth_scheme_resolver=_config.auth_scheme_resolver,
            supported_auth_schemes=_config.auth_schemes,
            endpoint_resolver=_config.endpoint_resolver,
            retry_strategy=_retry_strategy,
        )

        return await _pipeline(_call)

    async def put_with_content_encoding(
        self,
        *,
        encoding: str | None = None,
        data: str | None = None,
        plugins: list[Plugin] | None = None,
    ) -> PutWithContentEncodingOutput:
        """
        Invokes the PutWithContentEncoding operation.

        Args:
            plugins:
                A list of callables that modify the configuration dynamically.
                Changes made by these plugins only apply for the duration of the
                operation execution and will not affect any other operation
                invocations.

        Returns:
            An instance of `PutWithContentEncodingOutput`.
        """
        if self._closed:
            raise RuntimeError(
                "Cannot invoke an operation on a client that has been closed."
            )

        _input = PutWithContentEncodingInput(encoding=encoding, data=data)
        _operation_plugins: list[Plugin] = []
        if plugins:
            _operation_plugins.extend(plugins)
        await self._ensure_setup()
        assert self._config is not None
        if _operation_plugins:
            # Keep operation-plugin mutations scoped to this call.
            _config = _deepcopy(self._config)
            for _plugin in _operation_plugins:
                _plugin(_config)
        else:
            _config = self._config
        if (
            _config.protocol is None
            or _config.transport is None
            or _config.endpoint_resolver is None
            or _config.auth_scheme_resolver is None
            or _config.auth_schemes is None
        ):
            raise ExpectationNotMetError(
                "protocol, transport, endpoint_resolver, auth_scheme_resolver,"
                " and auth_schemes MUST be set on the config to make calls."
            )

        _retry_strategy = await self._retry_strategy_resolver.resolve_retry_strategy(
            retry_strategy=_config.retry_strategy,
            retry_mode=_config.retry_mode,
            max_attempts=_config.max_attempts,
        )

        _pipeline = RequestPipeline(
            protocol=_config.protocol, transport=_config.transport
        )
        _call = ClientCall(
            input=_input,
            operation=PUT_WITH_CONTENT_ENCODING,
            context=TypedProperties({"config": _config}),
            interceptor=InterceptorChain(_config.interceptors),
            auth_scheme_resolver=_config.auth_scheme_resolver,
            supported_auth_schemes=_config.auth_schemes,
            endpoint_resolver=_config.endpoint_resolver,
            retry_strategy=_retry_strategy,
        )

        return await _pipeline(_call)

    async def simple_scalar_properties(
        self,
        *,
        float_value: float | None = None,
        double_value: float | None = None,
        plugins: list[Plugin] | None = None,
    ) -> SimpleScalarPropertiesOutput:
        """
        Invokes the SimpleScalarProperties operation.

        Args:
            plugins:
                A list of callables that modify the configuration dynamically.
                Changes made by these plugins only apply for the duration of the
                operation execution and will not affect any other operation
                invocations.

        Returns:
            An instance of `SimpleScalarPropertiesOutput`.
        """
        if self._closed:
            raise RuntimeError(
                "Cannot invoke an operation on a client that has been closed."
            )

        _input = SimpleScalarPropertiesInput(
            float_value=float_value, double_value=double_value
        )
        _operation_plugins: list[Plugin] = []
        if plugins:
            _operation_plugins.extend(plugins)
        await self._ensure_setup()
        assert self._config is not None
        if _operation_plugins:
            # Keep operation-plugin mutations scoped to this call.
            _config = _deepcopy(self._config)
            for _plugin in _operation_plugins:
                _plugin(_config)
        else:
            _config = self._config
        if (
            _config.protocol is None
            or _config.transport is None
            or _config.endpoint_resolver is None
            or _config.auth_scheme_resolver is None
            or _config.auth_schemes is None
        ):
            raise ExpectationNotMetError(
                "protocol, transport, endpoint_resolver, auth_scheme_resolver,"
                " and auth_schemes MUST be set on the config to make calls."
            )

        _retry_strategy = await self._retry_strategy_resolver.resolve_retry_strategy(
            retry_strategy=_config.retry_strategy,
            retry_mode=_config.retry_mode,
            max_attempts=_config.max_attempts,
        )

        _pipeline = RequestPipeline(
            protocol=_config.protocol, transport=_config.transport
        )
        _call = ClientCall(
            input=_input,
            operation=SIMPLE_SCALAR_PROPERTIES,
            context=TypedProperties({"config": _config}),
            interceptor=InterceptorChain(_config.interceptors),
            auth_scheme_resolver=_config.auth_scheme_resolver,
            supported_auth_schemes=_config.auth_schemes,
            endpoint_resolver=_config.endpoint_resolver,
            retry_strategy=_retry_strategy,
        )

        return await _pipeline(_call)

    async def sparse_nulls_operation(
        self,
        *,
        sparse_string_list: list[str | None] | None = None,
        sparse_string_map: dict[str, str | None] | None = None,
        plugins: list[Plugin] | None = None,
    ) -> SparseNullsOperationOutput:
        """
        Invokes the SparseNullsOperation operation.

        Args:
            plugins:
                A list of callables that modify the configuration dynamically.
                Changes made by these plugins only apply for the duration of the
                operation execution and will not affect any other operation
                invocations.

        Returns:
            An instance of `SparseNullsOperationOutput`.
        """
        if self._closed:
            raise RuntimeError(
                "Cannot invoke an operation on a client that has been closed."
            )

        _input = SparseNullsOperationInput(
            sparse_string_list=sparse_string_list, sparse_string_map=sparse_string_map
        )
        _operation_plugins: list[Plugin] = []
        if plugins:
            _operation_plugins.extend(plugins)
        await self._ensure_setup()
        assert self._config is not None
        if _operation_plugins:
            # Keep operation-plugin mutations scoped to this call.
            _config = _deepcopy(self._config)
            for _plugin in _operation_plugins:
                _plugin(_config)
        else:
            _config = self._config
        if (
            _config.protocol is None
            or _config.transport is None
            or _config.endpoint_resolver is None
            or _config.auth_scheme_resolver is None
            or _config.auth_schemes is None
        ):
            raise ExpectationNotMetError(
                "protocol, transport, endpoint_resolver, auth_scheme_resolver,"
                " and auth_schemes MUST be set on the config to make calls."
            )

        _retry_strategy = await self._retry_strategy_resolver.resolve_retry_strategy(
            retry_strategy=_config.retry_strategy,
            retry_mode=_config.retry_mode,
            max_attempts=_config.max_attempts,
        )

        _pipeline = RequestPipeline(
            protocol=_config.protocol, transport=_config.transport
        )
        _call = ClientCall(
            input=_input,
            operation=SPARSE_NULLS_OPERATION,
            context=TypedProperties({"config": _config}),
            interceptor=InterceptorChain(_config.interceptors),
            auth_scheme_resolver=_config.auth_scheme_resolver,
            supported_auth_schemes=_config.auth_schemes,
            endpoint_resolver=_config.endpoint_resolver,
            retry_strategy=_retry_strategy,
        )

        return await _pipeline(_call)
