# Code generated by smithy-python-codegen DO NOT EDIT.

from copy import deepcopy
import logging
from typing import Any, cast

from smithy_aws_core.config import ConfigSource
from smithy_aws_core.identity import AWSCredentialsIdentity
from smithy_aws_core.identity.chain import IdentityChain
from smithy_core.aio.client import AsyncClient, ClientCall, RequestPipeline
from smithy_core.deserializers import DeserializeableShape
from smithy_core.exceptions import ExpectationNotMetError
from smithy_core.schemas import APIOperation
from smithy_core.serializers import SerializeableShape
from smithy_http.aio.interfaces import HTTPClient
from smithy_http.plugins import user_agent_plugin

from .config import AsyncJsonProtocolConfig, Plugin
from .models import (
    CONTENT_TYPE_PARAMETERS,
    ContentTypeParametersInput,
    ContentTypeParametersOutput,
    DATETIME_OFFSETS,
    DatetimeOffsetsInput,
    DatetimeOffsetsOutput,
    EMPTY_OPERATION,
    ENDPOINT_OPERATION,
    ENDPOINT_WITH_HOST_LABEL_OPERATION,
    EmptyOperationInput,
    EmptyOperationOutput,
    EndpointOperationInput,
    EndpointOperationOutput,
    EndpointWithHostLabelOperationInput,
    EndpointWithHostLabelOperationOutput,
    FRACTIONAL_SECONDS,
    FractionalSecondsInput,
    FractionalSecondsOutput,
    GREETING_WITH_ERRORS,
    GreetingWithErrorsInput,
    GreetingWithErrorsOutput,
    HOST_WITH_PATH_OPERATION,
    HostWithPathOperationInput,
    HostWithPathOperationOutput,
    JSON_ENUMS,
    JSON_INT_ENUMS,
    JSON_UNIONS,
    JsonEnumsInput,
    JsonEnumsOutput,
    JsonIntEnumsInput,
    JsonIntEnumsOutput,
    JsonUnionsInput,
    JsonUnionsOutput,
    KITCHEN_SINK_OPERATION,
    KitchenSinkOperationInput,
    KitchenSinkOperationOutput,
    NULL_OPERATION,
    NullOperationInput,
    NullOperationOutput,
    OPERATION_WITH_OPTIONAL_INPUT_OUTPUT,
    OperationWithOptionalInputOutputInput,
    OperationWithOptionalInputOutputOutput,
    PUT_AND_GET_INLINE_DOCUMENTS,
    PUT_WITH_CONTENT_ENCODING,
    PutAndGetInlineDocumentsInput,
    PutAndGetInlineDocumentsOutput,
    PutWithContentEncodingInput,
    PutWithContentEncodingOutput,
    SIMPLE_SCALAR_PROPERTIES,
    SPARSE_NULLS_OPERATION,
    SimpleScalarPropertiesInput,
    SimpleScalarPropertiesOutput,
    SparseNullsOperationInput,
    SparseNullsOperationOutput,
)
from .user_agent import aws_user_agent_plugin


logger = logging.getLogger(__name__)


class AsyncJsonProtocolClient(AsyncClient):
    """Client for JsonProtocol"""

    def __init__(
        self,
        config: AsyncJsonProtocolConfig | None = None,
        plugins: list[Plugin] | None = None,
    ):
        """
        Constructor for `AsyncJsonProtocolClient`.

        Args:
            config:
                Optional configuration for the client. Here you can set things like
                the endpoint for HTTP services or auth credentials.
            plugins:
                A list of callables applied once to the client's base configuration.
                Their changes are inherited by every operation invocation.
        """
        super().__init__()
        self._config = config
        self._plugins = plugins
        self._client_plugins: list[Plugin] = [aws_user_agent_plugin, user_agent_plugin]

    async def _ensure_setup(self) -> AsyncJsonProtocolConfig:
        if not self._setup_done:
            async with self._derive_lock:
                if self._closed:
                    raise RuntimeError(
                        "Cannot invoke an operation on a client that has been closed."
                    )
                if not self._setup_done:
                    if self._config is None:
                        config = await AsyncJsonProtocolConfig.resolve()
                    else:
                        # Copy so plugins don't mutate the caller's config.
                        config = deepcopy(self._config)
                    for plugin in self._client_plugins:
                        plugin(config)
                    if self._plugins:
                        for plugin in self._plugins:
                            plugin(config)
                    # Publish state only after setup fully succeeds, so a
                    # failed _post_setup leaves the caller's config untouched
                    # (no re-applied plugins) and the transport closeable.
                    await self._post_setup(config)
                    self._transport = config.transport
                    self._config = config
                    self._setup_done = True
        assert self._config is not None
        return self._config

    async def _post_setup(self, config: AsyncJsonProtocolConfig) -> None:
        pass

        if config.aws_credentials_identity_resolver is None:
            config_context = config.resolution_context()
            config_file = None
            profile_name = None
            if config_context is not None:
                config_file = await config_context.parsed_profiles()
                if config_context.profile_source is ConfigSource.OVERRIDE:
                    profile_name = config_context.profile_name
            config.aws_credentials_identity_resolver = await IdentityChain.create(
                AWSCredentialsIdentity,
                config_file=config_file,
                profile_name=profile_name,
                region_override=config.region,
                http_client=cast(HTTPClient | None, config.transport),
            )

    async def _prepare_call[I: SerializeableShape, O: DeserializeableShape](
        self,
        input: I,
        operation: APIOperation[I, O],
        default_plugins: list[Plugin],
        plugins: list[Plugin] | None,
    ) -> tuple[RequestPipeline[Any, Any], ClientCall[I, O]]:
        if self._closed:
            raise RuntimeError(
                "Cannot invoke an operation on a client that has been closed."
            )
        config = await self._ensure_setup()
        if default_plugins or plugins:
            # Keep operation-plugin mutations scoped to this call.
            config = deepcopy(config)
            for plugin in default_plugins:
                plugin(config)
            if plugins:
                for plugin in plugins:
                    plugin(config)
        if (
            config.protocol is None
            or config.transport is None
            or config.endpoint_resolver is None
            or config.auth_scheme_resolver is None
            or config.auth_schemes is None
        ):
            raise ExpectationNotMetError(
                "protocol, transport, endpoint_resolver, auth_scheme_resolver,"
                " and auth_schemes MUST be set on the config to make calls."
            )
        retry_strategy = await self._retry_strategy_resolver.resolve_retry_strategy(
            retry_strategy=config.retry_strategy,
            retry_mode=config.retry_mode,
            max_attempts=config.max_attempts,
        )
        return self._build_call(
            input, operation, config=config, retry_strategy=retry_strategy
        )

    async def content_type_parameters(
        self, input: ContentTypeParametersInput, plugins: list[Plugin] | None = None
    ) -> ContentTypeParametersOutput:
        """
        The example tests how servers must support requests containing a
        `Content-Type` header with parameters.

        Args:
            input:
                An instance of `ContentTypeParametersInput`.
            plugins:
                A list of callables that modify the configuration dynamically.
                Changes made by these plugins only apply for the duration of the
                operation execution and will not affect any other operation
                invocations.

        Returns:
            An instance of `ContentTypeParametersOutput`.
        """
        pipeline, call = await self._prepare_call(
            input, CONTENT_TYPE_PARAMETERS, [], plugins
        )
        return await pipeline(call)

    async def datetime_offsets(
        self, input: DatetimeOffsetsInput, plugins: list[Plugin] | None = None
    ) -> DatetimeOffsetsOutput:
        """
        Invokes the DatetimeOffsets operation.

        Args:
            input:
                An instance of `DatetimeOffsetsInput`.
            plugins:
                A list of callables that modify the configuration dynamically.
                Changes made by these plugins only apply for the duration of the
                operation execution and will not affect any other operation
                invocations.

        Returns:
            An instance of `DatetimeOffsetsOutput`.
        """
        pipeline, call = await self._prepare_call(input, DATETIME_OFFSETS, [], plugins)
        return await pipeline(call)

    async def empty_operation(
        self, input: EmptyOperationInput, plugins: list[Plugin] | None = None
    ) -> EmptyOperationOutput:
        """
        Invokes the EmptyOperation operation.

        Args:
            input:
                An instance of `EmptyOperationInput`.
            plugins:
                A list of callables that modify the configuration dynamically.
                Changes made by these plugins only apply for the duration of the
                operation execution and will not affect any other operation
                invocations.

        Returns:
            An instance of `EmptyOperationOutput`.
        """
        pipeline, call = await self._prepare_call(input, EMPTY_OPERATION, [], plugins)
        return await pipeline(call)

    async def endpoint_operation(
        self, input: EndpointOperationInput, plugins: list[Plugin] | None = None
    ) -> EndpointOperationOutput:
        """
        Invokes the EndpointOperation operation.

        Args:
            input:
                An instance of `EndpointOperationInput`.
            plugins:
                A list of callables that modify the configuration dynamically.
                Changes made by these plugins only apply for the duration of the
                operation execution and will not affect any other operation
                invocations.

        Returns:
            An instance of `EndpointOperationOutput`.
        """
        pipeline, call = await self._prepare_call(
            input, ENDPOINT_OPERATION, [], plugins
        )
        return await pipeline(call)

    async def endpoint_with_host_label_operation(
        self,
        input: EndpointWithHostLabelOperationInput,
        plugins: list[Plugin] | None = None,
    ) -> EndpointWithHostLabelOperationOutput:
        """
        Invokes the EndpointWithHostLabelOperation operation.

        Args:
            input:
                An instance of `EndpointWithHostLabelOperationInput`.
            plugins:
                A list of callables that modify the configuration dynamically.
                Changes made by these plugins only apply for the duration of the
                operation execution and will not affect any other operation
                invocations.

        Returns:
            An instance of `EndpointWithHostLabelOperationOutput`.
        """
        pipeline, call = await self._prepare_call(
            input, ENDPOINT_WITH_HOST_LABEL_OPERATION, [], plugins
        )
        return await pipeline(call)

    async def fractional_seconds(
        self, input: FractionalSecondsInput, plugins: list[Plugin] | None = None
    ) -> FractionalSecondsOutput:
        """
        Invokes the FractionalSeconds operation.

        Args:
            input:
                An instance of `FractionalSecondsInput`.
            plugins:
                A list of callables that modify the configuration dynamically.
                Changes made by these plugins only apply for the duration of the
                operation execution and will not affect any other operation
                invocations.

        Returns:
            An instance of `FractionalSecondsOutput`.
        """
        pipeline, call = await self._prepare_call(
            input, FRACTIONAL_SECONDS, [], plugins
        )
        return await pipeline(call)

    async def greeting_with_errors(
        self, input: GreetingWithErrorsInput, plugins: list[Plugin] | None = None
    ) -> GreetingWithErrorsOutput:
        """
        This operation has three possible return values: 1. A successful
        response in the form of GreetingWithErrorsOutput 2. An InvalidGreeting
        error. 3. A ComplexError error. Implementations must be able to
        successfully take a response and properly deserialize successful and
        error responses.

        Args:
            input:
                An instance of `GreetingWithErrorsInput`.
            plugins:
                A list of callables that modify the configuration dynamically.
                Changes made by these plugins only apply for the duration of the
                operation execution and will not affect any other operation
                invocations.

        Returns:
            An instance of `GreetingWithErrorsOutput`.
        """
        pipeline, call = await self._prepare_call(
            input, GREETING_WITH_ERRORS, [], plugins
        )
        return await pipeline(call)

    async def host_with_path_operation(
        self, input: HostWithPathOperationInput, plugins: list[Plugin] | None = None
    ) -> HostWithPathOperationOutput:
        """
        Invokes the HostWithPathOperation operation.

        Args:
            input:
                An instance of `HostWithPathOperationInput`.
            plugins:
                A list of callables that modify the configuration dynamically.
                Changes made by these plugins only apply for the duration of the
                operation execution and will not affect any other operation
                invocations.

        Returns:
            An instance of `HostWithPathOperationOutput`.
        """
        pipeline, call = await self._prepare_call(
            input, HOST_WITH_PATH_OPERATION, [], plugins
        )
        return await pipeline(call)

    async def json_enums(
        self, input: JsonEnumsInput, plugins: list[Plugin] | None = None
    ) -> JsonEnumsOutput:
        """
        This example serializes enums as top level properties, in lists, sets,
        and maps.

        Args:
            input:
                An instance of `JsonEnumsInput`.
            plugins:
                A list of callables that modify the configuration dynamically.
                Changes made by these plugins only apply for the duration of the
                operation execution and will not affect any other operation
                invocations.

        Returns:
            An instance of `JsonEnumsOutput`.
        """
        pipeline, call = await self._prepare_call(input, JSON_ENUMS, [], plugins)
        return await pipeline(call)

    async def json_int_enums(
        self, input: JsonIntEnumsInput, plugins: list[Plugin] | None = None
    ) -> JsonIntEnumsOutput:
        """
        This example serializes intEnums as top level properties, in lists,
        sets, and maps.

        Args:
            input:
                An instance of `JsonIntEnumsInput`.
            plugins:
                A list of callables that modify the configuration dynamically.
                Changes made by these plugins only apply for the duration of the
                operation execution and will not affect any other operation
                invocations.

        Returns:
            An instance of `JsonIntEnumsOutput`.
        """
        pipeline, call = await self._prepare_call(input, JSON_INT_ENUMS, [], plugins)
        return await pipeline(call)

    async def json_unions(
        self, input: JsonUnionsInput, plugins: list[Plugin] | None = None
    ) -> JsonUnionsOutput:
        """
        This operation uses unions for inputs and outputs.

        Args:
            input:
                An instance of `JsonUnionsInput`.
            plugins:
                A list of callables that modify the configuration dynamically.
                Changes made by these plugins only apply for the duration of the
                operation execution and will not affect any other operation
                invocations.

        Returns:
            An instance of `JsonUnionsOutput`.
        """
        pipeline, call = await self._prepare_call(input, JSON_UNIONS, [], plugins)
        return await pipeline(call)

    async def kitchen_sink_operation(
        self, input: KitchenSinkOperationInput, plugins: list[Plugin] | None = None
    ) -> KitchenSinkOperationOutput:
        """
        Invokes the KitchenSinkOperation operation.

        Args:
            input:
                An instance of `KitchenSinkOperationInput`.
            plugins:
                A list of callables that modify the configuration dynamically.
                Changes made by these plugins only apply for the duration of the
                operation execution and will not affect any other operation
                invocations.

        Returns:
            An instance of `KitchenSinkOperationOutput`.
        """
        pipeline, call = await self._prepare_call(
            input, KITCHEN_SINK_OPERATION, [], plugins
        )
        return await pipeline(call)

    async def null_operation(
        self, input: NullOperationInput, plugins: list[Plugin] | None = None
    ) -> NullOperationOutput:
        """
        Invokes the NullOperation operation.

        Args:
            input:
                An instance of `NullOperationInput`.
            plugins:
                A list of callables that modify the configuration dynamically.
                Changes made by these plugins only apply for the duration of the
                operation execution and will not affect any other operation
                invocations.

        Returns:
            An instance of `NullOperationOutput`.
        """
        pipeline, call = await self._prepare_call(input, NULL_OPERATION, [], plugins)
        return await pipeline(call)

    async def operation_with_optional_input_output(
        self,
        input: OperationWithOptionalInputOutputInput,
        plugins: list[Plugin] | None = None,
    ) -> OperationWithOptionalInputOutputOutput:
        """
        Invokes the OperationWithOptionalInputOutput operation.

        Args:
            input:
                An instance of `OperationWithOptionalInputOutputInput`.
            plugins:
                A list of callables that modify the configuration dynamically.
                Changes made by these plugins only apply for the duration of the
                operation execution and will not affect any other operation
                invocations.

        Returns:
            An instance of `OperationWithOptionalInputOutputOutput`.
        """
        pipeline, call = await self._prepare_call(
            input, OPERATION_WITH_OPTIONAL_INPUT_OUTPUT, [], plugins
        )
        return await pipeline(call)

    async def put_and_get_inline_documents(
        self, input: PutAndGetInlineDocumentsInput, plugins: list[Plugin] | None = None
    ) -> PutAndGetInlineDocumentsOutput:
        """
        This example serializes an inline document as part of the payload.

        Args:
            input:
                An instance of `PutAndGetInlineDocumentsInput`.
            plugins:
                A list of callables that modify the configuration dynamically.
                Changes made by these plugins only apply for the duration of the
                operation execution and will not affect any other operation
                invocations.

        Returns:
            An instance of `PutAndGetInlineDocumentsOutput`.
        """
        pipeline, call = await self._prepare_call(
            input, PUT_AND_GET_INLINE_DOCUMENTS, [], plugins
        )
        return await pipeline(call)

    async def put_with_content_encoding(
        self, input: PutWithContentEncodingInput, plugins: list[Plugin] | None = None
    ) -> PutWithContentEncodingOutput:
        """
        Invokes the PutWithContentEncoding operation.

        Args:
            input:
                An instance of `PutWithContentEncodingInput`.
            plugins:
                A list of callables that modify the configuration dynamically.
                Changes made by these plugins only apply for the duration of the
                operation execution and will not affect any other operation
                invocations.

        Returns:
            An instance of `PutWithContentEncodingOutput`.
        """
        pipeline, call = await self._prepare_call(
            input, PUT_WITH_CONTENT_ENCODING, [], plugins
        )
        return await pipeline(call)

    async def simple_scalar_properties(
        self, input: SimpleScalarPropertiesInput, plugins: list[Plugin] | None = None
    ) -> SimpleScalarPropertiesOutput:
        """
        Invokes the SimpleScalarProperties operation.

        Args:
            input:
                An instance of `SimpleScalarPropertiesInput`.
            plugins:
                A list of callables that modify the configuration dynamically.
                Changes made by these plugins only apply for the duration of the
                operation execution and will not affect any other operation
                invocations.

        Returns:
            An instance of `SimpleScalarPropertiesOutput`.
        """
        pipeline, call = await self._prepare_call(
            input, SIMPLE_SCALAR_PROPERTIES, [], plugins
        )
        return await pipeline(call)

    async def sparse_nulls_operation(
        self, input: SparseNullsOperationInput, plugins: list[Plugin] | None = None
    ) -> SparseNullsOperationOutput:
        """
        Invokes the SparseNullsOperation operation.

        Args:
            input:
                An instance of `SparseNullsOperationInput`.
            plugins:
                A list of callables that modify the configuration dynamically.
                Changes made by these plugins only apply for the duration of the
                operation execution and will not affect any other operation
                invocations.

        Returns:
            An instance of `SparseNullsOperationOutput`.
        """
        pipeline, call = await self._prepare_call(
            input, SPARSE_NULLS_OPERATION, [], plugins
        )
        return await pipeline(call)
