[project]
name = "aws-event-stream"
version = "0.0.1"
description = "Core Smithy components for AWS services and protocols."
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "smithy-core",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build]
exclude = [
  "tests",
]

[tool.ruff]
src = ["src"]
