[project]
name = "aws-event-stream"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Hayden Baker", email = "haydebak@amazon.com" }
]
requires-python = ">=3.12"
dependencies = [
    "smithy-core",
    "smithy-event-stream",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build]
exclude = [
  "tests",
]
