name: License Header Check

on:
  pull_request:
  push:
    branches:
      - develop

permissions:
  contents: read

jobs:
  check-license-header: 
    name: Check License Header
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10
        with:
          persist-credentials: false

      - uses: apache/skywalking-eyes/header@ab3d1fe50d23f9c82eff489297167e2dde8ba6cb
        with:
          mode: check 
