name: License Header Check

on:
  pull_request:
  push:
    branches:
      - develop

permissions:
  contents: read

jobs:
  check-license-header: 
    name: Check License Header
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10
        with:
          persist-credentials: false

      - uses: apache/skywalking-eyes/header@8e837beb243c264ffcd5ea3abd3d5d8975cd0077
        with:
          mode: check 
