name: Lint code

on:
    push:
        branches: develop
    pull_request:
        branches: develop

jobs:
  lint:
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.11
      uses: actions/setup-python@v2
      with:
        python-version: "3.11"
    - name: Run pre-commit
      uses: pre-commit/action@v2.0.0
